digitalocean/doctl

- README.md
- account.go
- action.go
- domain.go
- droplet.go
- godo_ext.go
- main.go
- main_test.go
- region.go
- size.go
- sshkey.go
- util.go
Swaps for for fatalf, fatalln, printf, etc.
cc @aybabtme @bryanl @macb
> Refactor fmt for log

- scripts/build.sh
- scripts/release.sh
- scripts/stage.sh
- scripts/upload.sh
Updates release scripts with new repo and upload locations.
> Update release scripts for doctl

- README.md
This adds a few basic usage examples to get user up and running. It also links out to the full tutorial.
> Add basic usage examples and link to tutorial.

- README.md
Update the `README.md` to include installation through package managers.
Closes #29
> Include Package Managers Install Instructions

- README.md
Configuration format is YAML and not JSON.
> update format of configuration in README

- commands/commands.go
- commands/commands_test.go
- commands/ssh.go
- commands/ssh_test.go
- commands/version.go
- do/pagination.go
Cleaning up code by removing unused identifiers.
> Removing unused identifiers

- doit.go
Rename some `doit` to `doctl`.
@bryanl
> old URLs and strings

- commands/command_config.go
- commands/doit.go
- commands/output.go
> print drives column if beta is on

- README.md
- commands/doit.go
> Fix a typo in the usage text

- commands/images.go
> User list images is return distributions

- commands/droplets.go
> Remove output when deleting droplets

- .gitignore
- scripts/build.sh
Reduces clutter in root directory by building test bin in subdirectory
> build test bin in out directory

- commands/droplet_actions.go
- commands/droplet_actions_test.go
thanks @kitschysynq
r: @bryanl
> password-reset, not power-reset

- doit.go
- doit_test.go
- vendor/github.com/digitalocean/godo/storage_actions.go
- vendor/github.com/digitalocean/godo/storage_actions_test.go
- vendor/github.com/digitalocean/godo/tags_test.go
- vendor/manifest
Adds the doctl version to the User-Agent. The user agent now looks like `doctl/1.3.0+godo/0.1.0`
> add doctl version to user agent

- commands/output.go
It would be really, really nice if we could have the PublicIPv6 displayed too. 
Signed-off-by: Ben Howard <bh@digitalocean.com>
> display public ipv6 in droplet list

- commands/errors.go
Current color outputs don’t work well with windows.
Fixes #114
> Use window compatible ansi colors

- args.go
- commands/ssh.go
Would be nice to have the ability to connect by private ip. I connect to systems through a VPN that only connects to private interfaces so it could be convenient for that circumstance.
> add ssh-private-ip flag

- commands/droplets.go
- commands/errors.go
> change the progress report output to stderr in droplet command

- args.go
- commands/droplets.go
- commands/droplets_test.go
> Added Template flag for droplet get operation

- commands/droplets.go
- commands/droplets_test.go
Eases access to droplet values
Better template Usage text
Fixes #156
> Improves the get function template, Usage with sample values

- commands/confirmation.go
- commands/droplets.go
- commands/images.go
- commands/snapshots.go
- commands/tags.go
- do/snapshots.go
- do/volume_actions.go
A few changes for New Year. :100: :fireworks: ~ Fixed golint errors
> Fix golint errors

- commands/droplets.go
Fixes #162.
I feel like this is left there for debugging purposes so I think it's OK to remove this. If this is needed, let me know. =D
cc @nanzhong @aybabtme
> Fixed #162 - removed debug output for extracting volumes

- commands/doit.go
Fixes #176 
This should work, at least it does for me.
cc @aybabtme @nanzhong
> Fixed #176

- commands/actions.go
- commands/droplet_actions.go
- commands/droplets.go
- commands/snapshots.go
- commands/ssh.go
- commands/tags.go
- commands/volumes.go
What do you think about this change? I updated descriptions to match one template and changed a few ones.
I'm not sure is `create` descriptions good, but I'll revert if it is problem. =)
cc @nanzhong
> Updated command descriptions to match template

- README.md
> README: fix links, update doctl command description

- commands/doit.go
- doit.go
> Add flag for overriding API endpoint

- README.md
This PR adds the link for Community's Block Storage tutorial.
/cc @mauricio
> readme: add block storage tutorial link

- commands/command_config.go
- commands/firewalls.go
- commands/load_balancers.go
- commands/ssh.go
- commands/volumes.go
- do/volumes.go
- in error checking
`if err != nil { return err }; return nil` -> `return err`
> commands: General simplifications

- pkg/ssh/ssh_internal.go
Looks like I managed to make this work.
I don't have Windows box on my own, but I tested on one I found and it seems to work very well. If you have Windows box, it could be useful to test further.
Also, tests for internal SSH looks like they are only checking correctness of private key, but if there is something to add, I'll do it. =)
cc @nanzhong @grampajoe
> ssh: windows support for command forwarding

- commands/completion.go
Closes #297 
Ref https://github.com/spf13/cobra/blob/cd30c2a7e91a1d63fd9a0027accf18a681e9d50b/command.go#L74
> Mark completion command as hidden

- CHANGELOG.md
- args.go
- commands/output.go
- commands/volumes.go
Allow creation of formatted volumes, and show volume format information when displaying volumes.
> volumes: Add support for formatted volumes

- commands/doit.go
> Check legacy paths only if applicable to the current environment

- CHANGELOG.md
- Dockerfile
- README.md
- commands/tags_test.go
- snap/snapcraft.yaml
Bringing on the changes from https://github.com/digitalocean/godo/pull/181.
Pretty easy. Mind poking @mauricio and/or @jrm780?
> Support tagging with images

- CONTRIBUTING.md
- Do not mention the specific version that brew installs.
- Rename _tags_ to _labels_.
> README improvements regarding brew and tags/labels.

- errors_test.go
Increased test coverage by adding test for the InvalidURNErr() error method.
> Added test for NewInvalidURNErr().

- args.go
- commands/displayers/kubernetes.go
- commands/doit.go
- commands/kubernetes.go
- commands/load_balancers.go
- do/kubernetes.go
First stab at K8S support, behind a beta flag (`DIGITALOCEAN_ENABLE_BETA=true`).
> k8saas: basic k8s support

- args.go
- commands/account.go
- commands/actions.go
- commands/actions_test.go
- commands/completion.go
- commands/doit.go
- commands/domains.go
- commands/droplet_actions.go
- commands/droplets.go
- commands/floating_ips.go
- commands/images.go
- commands/load_balancers_test.go
- commands/plugin.go
- commands/regions.go
- commands/sizes.go
- commands/snapshots.go
- commands/ssh.go
- commands/sshkeys.go
- commands/tags.go
- do/account.go
- do/account_test.go
- do/images.go
- install/bintray.go
- install/download.go
- install/download_test.go
- install/upload.go
- pkg/system/stat_unix_test.go
Fixes many of the issues called out by [GoReportCard](https://goreportcard.com/report/github.com/digitalocean/doctl). The commit messages describe which sections of the report card are being repaired.
> Goreportcard

- CHANGELOG.md
- README.md
- doit.go
- snap/snapcraft.yaml
Gotta automate this lovely lovely ...
> update changelog for release 1.12.1

- commands/kubernetes.go
The check that verifies the count and size flags aren't passed in was wrong.
Fixes #389
> doks: Fix node-pool flags when creating cluster

- CHANGELOG.md
- Dockerfile
- README.md
- doit.go
- snap/snapcraft.yaml
> Version 1.13.0

- commands/confirmation.go
- commands/confirmation_test.go
Small readability improvement.
> Simplify newline trimming in retrieveUserInput.

- commands/completion.go
This PR models the completion code after kubectl.
https://github.com/kubernetes/kubernetes/blob/b8b689aae0d6879de5192b203590330a11c7b9e3/pkg/kubectl/cmd/completion/completion.go
Closes #386
> Fix zsh completion

- Gopkg.lock
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/CONTRIBUTING.md
- vendor/github.com/digitalocean/godo/databases.go
- vendor/github.com/digitalocean/godo/databases_test.go
- vendor/github.com/digitalocean/godo/doc.go
- vendor/github.com/digitalocean/godo/droplets.go
- vendor/github.com/digitalocean/godo/droplets_test.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/digitalocean/godo/kubernetes.go
- vendor/github.com/digitalocean/godo/kubernetes_test.go
- vendor/github.com/digitalocean/godo/load_balancers.go
- vendor/github.com/digitalocean/godo/load_balancers_test.go
- vendor/github.com/digitalocean/godo/storage.go
- vendor/github.com/digitalocean/godo/storage_test.go
- vendor/github.com/digitalocean/godo/vpcs.go
- vendor/github.com/digitalocean/godo/vpcs_test.go
updated godo vendor using command below:
#dep ensure -update github.com/digitalocean/godo
tested bu building and running the command
#docker build -t doctl .
#docker run --rm -e DIGITALOCEAN_ACCESS_TOKEN="My Token" doctl
> update godo to v1.11.0

- CHANGELOG.md
- CONTRIBUTING.md
- Dockerfile
- README.md
- doit.go
- snap/snapcraft.yaml
Also rewrote README so we won't need to update it on each version bump.
> bump to 1.16.0

- commands/kubernetes.go
Remove the beta flag from Kubernetes commands.
> kubernetes: No longer in beta

- README.md
- snap/snapcraft.yaml
> fix doctl compute ssh in snap

- CHANGELOG.md
- Dockerfile
- README.md
- doit.go
- snap/snapcraft.yaml
(I also caught some issues in the README while uncommenting the snap info.)
> bump version to 1.19.0

- scripts/release.sh
Caught this bug when doing the last release.
> tag the release with the release tag

- CONTRIBUTING.md
- snap/snapcraft.yaml
Streamlining the release process one annoyance at a time :)
> set snap version using tag

- README.md
Been meaning to clean up this README for some time :)
> advise when not to use snap, revise README for flow

- commands/doit.go
> set default location for config file to configPath

- README.md
> add macport to README

- README.md
I've added a link to the nixpkg. It appears to be kept up to date relatively well, and is community maintained.
> Added NixPkgs as Package Manager Option

- README.md
> describe current status of snap in README

- snap/snapcraft.yaml
https://forum.snapcraft.io/t/personal-files-request-for-doctl-was-classic-confinement-request-doctl/11785/21
> modify snap as requested by snapcraft review

- Dockerfile.build
- Dockerfile.cntr
- Makefile
The whole `make docker_build` infrastructure had several issues,
but it is working now :/
> fix make docker_build

- snap/snapcraft.yaml
https://forum.snapcraft.io/t/personal-files-request-for-doctl-was-classic-confinement-request-doctl/11785/28?u=hilz
Not sure if that means the original specified config should work.
Testing in production as can't locally.
> update snapcraft config per snapcraft

- .goreleaser.yml
- CONTRIBUTING.md
- Dockerfile.goreleaser
- README.md
thanks @bentranter it worked for me too :)
> release containers to dockerhub

- CHANGELOG.md
- CONTRIBUTING.md
- Makefile
Also tweaked the `make help` output, Makefile internal documentation, and output `make` commands generate while running for usability
> Retire changelog

- Makefile
Quick improvement I noticed in passing
> clean out dist as part of make clean

- Dockerfile.build
- Dockerfile.cntr
The following two commit messages have more details.
Also, reformatted the commands just a tiny bit.
fixes #310
> Adds openssh as docker container dependency

- Dockerfile.cntr
- Dockerfile.goreleaser
Bringing the Dockerfiles a bit more into alignment as we go...
> fix doctl compute ssh in docker hub container

- doit.go
- go.mod
Noticed that jww isn't used, so removing
> remove jww (unused)

- README.md
since we have it for Linux (feel free to reword)
> add profile refreshing code for macOS for Shell Auto-Completion

- CONTRIBUTING.md
Expands on testing to include a brief walk-through on how to write unit and integration tests, and what the intent of each kind of test is.
> Expand on testing in CONTRIBUTING

- .travis.yml
- CONTRIBUTING.md
- Makefile
review and merge after https://github.com/digitalocean/doctl/pull/562
> deploy on tag push

- .travis.yml
Figured out how to have multiple deploy jobs on travis. Refactoring before adding brew.
> split snap, goreleaser deploy jobs on travis

- args.go
- commands/kubernetes.go
- commands/kubernetes_test.go
Rebased on top of https://github.com/digitalocean/doctl/pull/575 until it's merged, see https://github.com/digitalocean/doctl/commit/12cc7245c12e593216731a7b89aa76a2a79b8d5d for just the diff of this PR.
> DOKS node pool auto-scale fields

- commands/kubernetes.go
Tags are replaced, make sure the doctl help text reflects this.
> commands/k8s: Clarify Tag Update Functionality

- .gitignore
- Makefile
- dockerfiles/Dockerfile.snap
- scripts/_build_snap.sh
- snap/local/snapcraft-core18.yaml
also includes snap/local/snapcraft-core18.yaml, which builds under core18
> optimize building snap via custom docker image

- commands/account.go
- commands/actions.go
- commands/auth.go
- commands/command.go
- commands/command_config.go
- commands/domains.go
- commands/droplet_actions.go
- commands/droplets.go
- commands/floating_ip_actions.go
- commands/floating_ips.go
- commands/image_actions.go
- commands/images.go
- commands/regions.go
- commands/sizes.go
- commands/snapshots.go
- commands/ssh.go
- commands/sshkeys.go
- commands/tags.go
- we can't seem to find a place where these are actually used
> removes obselete do categories

- commands/account.go
- commands/actions.go
- commands/command.go
- commands/completion.go
- commands/domains.go
- commands/droplets.go
- commands/floating_ips.go
- commands/images.go
- commands/snapshots.go
- commands/sshkeys.go
- commands/tags.go
- this was used for our old doc generation that has been completely
removed at this point
Co-authored-by: Hilary Holz <hholz@digitalocean.com>
> removes is index from all commands

- .travis.yml
- integration/init_test.go
- scripts/test.sh
I left this out when I originally wrote the integration tests.
> build a windows exe if we are on windows

- commands/doit.go
Co-Authored-By: Ben Tranter <ben@bentranter.io>
> create config home if necessary

- integration/auth_windows_test.go
- integration/droplet_create_test.go
- integration/init_test.go
looking to get more coverage over all of the basic functionality that surrounds our current core contract for our CLI.
> Compute integration tests

- integration/droplet_kernels_test.go
- integration/init_test.go
please wait to merge this until after the droplet delete test (I will rebase this).
> adds droplet kernels test

- integration/droplet_tag_test.go
Turned this file into a table test since the commands are large the mirror of each other. Now `tag_test` will test both `tag` and `untag`
> test both tag and untag

- integration/init_test.go
- integration/size_list_test.go
A test a day keeps the doctor away? Is that how it goes?
> Add tests for size list command.

- commands/doit.go
the first of many itty, bitty steps
> consolidate and rationalize viper init steps

- integration/databases_create_test.go
different approach here using a template (I know you should template out json) since the response is fixed and we just want to double check / return the same values the server is accepting to render them back to the client side.
> adds first database test to the mix

- do/projects.go
- integration/projects_resources_test.go
this also fixes the same bug we've fixed before (looping over and populating an object that takes a pointer). 
goplayground of why the code previously did not work:
https://play.golang.org/p/V3gn2NFSNGK
> adds test for projects resources assignment

- integration/snapshot_delete_test.go
- integration/snapshot_get_test.go
- integration/snapshot_list_test.go
So I wasn't really able to get around to doing one a day...
> Add snapshot tests.

- integration/projects_delete_test.go
- integration/projects_get_test.go
- integration/projects_list_test.go
- integration/projects_update_test.go
This is only missing a few of the tests under the `projects resources` subcommand. Those will follow on here shortly. All of this encouraged by how fast @andrewsomething is working on his integration test PRs 💃
> adds projects related tests

- integration/init_test.go
whoops - thanks @bentranter for pointing this out.
> add missed doctl name of suite

- go.mod
- go.sum
- vendor/github.com/sclevine/spec/.travis.yml
- vendor/github.com/sclevine/spec/spec.go
- vendor/modules.txt
- just keeping test dependencies up to date
> bumps spec to latest version

- integration/database_user_get_test.go
- integration/projects_delete_test.go
adds one test to make sure that the global `-o` flag for output format is respected.
> adds global output flag test

- integration/volume_create_test.go
- integration/volume_delete_test.go
- integration/volume_get_test.go
- integration/volume_list_test.go
- integration/volume_snapshot_test.go
This PR tests all volume functionality related to doctl.
> adds all volume tests

- integration/image_create_test.go
- integration/image_delete_test.go
- integration/image_get_test.go
- integration/image_list_application_test.go
- integration/image_list_distribution_test.go
- integration/image_list_test.go
- integration/image_list_user_test.go
- integration/image_update_test.go
> adds image tests

- commands/cdns.go
- commands/kubernetes.go
- commands/projects.go
- doit.go
- integration/kubernetes_clusters_create_test.go
The revert includes additional coverage of the kube create node pools functionality that we were previously missing.
> fixes node pools

- integration/firewall_create_test.go
Adds a new, single successful test case for firewall creates.
---
I was going to do these all at once, but I realize I haven't added new test case before, so here's a warmup before adding a bunch 🙂
> Add test for firewall creates

- commands/kubernetes.go
- commands/kubernetes_test.go
- integration/kubernetes_clusters_create_test.go
- we were defaulting to the global file location even though it
can be overridden by a user by an env var
> fixes kubeconfig location display

- integration/certificate_create_test.go
- integration/certificate_delete_test.go
- integration/certificate_get_test.go
- integration/certificate_list_test.go
integration tests for certificate functionality in doctl is complete!
> adds all related certificate tests

- commands/domains.go
- integration/domain_create_test.go
- integration/domain_delete_test.go
- integration/domain_get_test.go
- integration/domain_list_test.go
- this also fixes an incorrect alias that we were providing
> adds domain related tests

- args.go
- commands/databases.go
- commands/databases_test.go
- commands/displayers/database.go
- go.mod
- go.sum
- integration/database_user_create_test.go
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/databases.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/modules.txt
Adds support for the MySQL authentication plugin.
Should we include the setting in user list and get output?
> Databases: user create with auth mode flag

- pkg/ssh/ssh.go
> ssh: fix for snap

- go.mod
- go.sum
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/action.go
- vendor/github.com/digitalocean/godo/balance.go
- vendor/github.com/digitalocean/godo/cdn.go
- vendor/github.com/digitalocean/godo/certificates.go
- vendor/github.com/digitalocean/godo/databases.go
- vendor/github.com/digitalocean/godo/doc.go
- vendor/github.com/digitalocean/godo/domains.go
- vendor/github.com/digitalocean/godo/droplets.go
- vendor/github.com/digitalocean/godo/firewalls.go
- vendor/github.com/digitalocean/godo/floating_ips.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/digitalocean/godo/images.go
- vendor/github.com/digitalocean/godo/keys.go
- vendor/github.com/digitalocean/godo/kubernetes.go
- vendor/github.com/digitalocean/godo/load_balancers.go
- vendor/github.com/digitalocean/godo/meta.go
- vendor/github.com/digitalocean/godo/projects.go
- vendor/github.com/digitalocean/godo/regions.go
- vendor/github.com/digitalocean/godo/sizes.go
- vendor/github.com/digitalocean/godo/snapshots.go
- vendor/github.com/digitalocean/godo/storage.go
- vendor/github.com/digitalocean/godo/storage_actions.go
- vendor/github.com/digitalocean/godo/tags.go
- vendor/github.com/digitalocean/godo/vpcs.go
- vendor/modules.txt
@rbutler actually needs this in his follow on PR #717
> godo: dependency bump

- .github/ISSUE_TEMPLATE/bug_report.md
I decided to keep it pretty simple to start rather than being overly prescriptive. We can always iterate on it if needed.
> Create an issue template.

- dockerfiles/Dockerfile.snap
Series of tests to fix snap builds.
Test 1.
> Test snap build

- .travis.yml
> use skip_cleanup for deploy in travis

- commands/balance.go
- commands/databases.go
- commands/invoices.go
A few small improvements and couple typos caught by the actual writers on the docs team.
> Small copy changes based on feedback.

- commands/billing_history.go
- commands/vpcs.go
A couple extremely small edits for help output consistency.
> Small copy edits for help consistency.

- commands/registry.go
Moves Container Registry Commands to EA
> Draft PR until 04/28/20
> Update Container Registry to EA status

- commands/registry.go
Reverts digitalocean/doctl#788
> Revert "Update Container Registry to EA status"

- README.md
- commands/registry.go
- snap/snapcraft.yaml
Opening this as a draft until approval from the Canonical Snap team.
https://forum.snapcraft.io/t/personal-files-request-for-doctl/17654
Fixes: https://github.com/digitalocean/doctl/issues/709
> Add docker-config plug to snapcraft.yaml

- README.md
We've added a number of new top-level commands and updated some copy since this was last changed.
> Update README with recent help output.

- args.go
- commands/kubernetes.go
cc @adamwg , @waynr , @andrewsomething
> kubernetes - add surge upgrade support for clusters

- commands/apps.go
> Add app as alias of apps

- commands/displayers/invoice.go
- commands/invoices_test.go
- integration/invoice_get_test.go
Accompanies https://github.com/digitalocean/godo/pull/357
> invoices: add category to InvoiceItem

- commands/apps.go
- commands/apps_test.go
- go.mod
- go.sum
- integration/apps_test.go
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/apps.gen.go
- vendor/github.com/digitalocean/godo/apps.go
- vendor/github.com/digitalocean/godo/domains.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/modules.txt
This updates `godo` from `v1.42.0` to `v1.43.0`:
* [#360](https://github.com/digitalocean/godo/pull/360) domains: Allow for SRV records with port 0. - @andrewsomething
* [#362](https://github.com/digitalocean/godo/pull/362) update apps types - @kamaln7
I also added a confirmation prompt before deleting an app.
> Update godo, present confirmation prompt on app deletion

- integration/apps_spec_test.go
Signed-off-by: Pablo Caderno <kaderno@gmail.com>
Closes #867
> Added return error check

- commands/apps.go
Just nips and tucks and removing the `[Beta]` tag
> Improved apps docstrings

- args.go
- commands/load_balancers.go
- doit.go
Signed-off-by: Pablo Caderno <kaderno@gmail.com>
Closes #869
> Fixed golint check

- go.mod
- go.sum
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/apps.gen.go
- vendor/github.com/digitalocean/godo/databases.go
- vendor/github.com/digitalocean/godo/domains.go
- vendor/github.com/digitalocean/godo/droplets.go
- vendor/github.com/digitalocean/godo/firewalls.go
- vendor/github.com/digitalocean/godo/floating_ips.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/digitalocean/godo/images.go
- vendor/github.com/digitalocean/godo/invoices.go
- vendor/github.com/digitalocean/godo/kubernetes.go
- vendor/github.com/digitalocean/godo/load_balancers.go
- vendor/github.com/digitalocean/godo/projects.go
- vendor/github.com/digitalocean/godo/storage.go
- vendor/github.com/digitalocean/godo/strings.go
- vendor/modules.txt
Ran:
```
GO111MODULE=on go get -d github.com/digitalocean/godo@v1.47.0
GO111MODULE=on go mod tidy
GO111MODULE=on go mod vendor
```
> vendor: github.com/digitalocean/godo@v1.47.0

- go.mod
- go.sum
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/apps.gen.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/digitalocean/godo/kubernetes.go
- vendor/modules.txt
> vendor: github.com/digitalocean/godo@v1.48.0

- args.go
- commands/kubernetes.go
- commands/kubernetes_test.go
- do/kubernetes.go
- do/mocks/KubernetesService.go
> kubernetes - add commands related to docr integration

- commands/apps.go
- commands/apps_test.go
- commands/displayers/apps.go
- do/apps.go
- do/mocks/AppsService.go
- integration/apps_test.go
- integration/apps_tier_test.go
Added:
* `doctl apps list-regions`
* `doctl apps tier get`
* `doctl apps tier list`
* `doctl apps tier instance-size get`
* `doctl apps tier instance-size list`
> apps: add region, tier, and instance size retrieval commands

- args.go
- commands/apps.go
- commands/apps_test.go
- do/apps.go
- do/mocks/AppsService.go
- go.mod
- go.sum
- integration/apps_test.go
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/apps.gen.go
- vendor/github.com/digitalocean/godo/apps.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/digitalocean/godo/registry.go
- vendor/modules.txt
Upgrade `godo` to pull in https://github.com/digitalocean/godo/pull/407 & add a `--force-rebuild` flag to `doctl apps create-deployment`
> apps: add the option to force build a new deployment

- .github/workflows/ci.yml
- .travis.yml
- CONTRIBUTING.md
- README.md
- commands/apps_test.go
- integration/apps_spec_test.go
- integration/apps_test.go
- scripts/version.sh
> master to main

- go.mod
- go.sum
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/apps.gen.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/digitalocean/godo/kubernetes.go
- vendor/modules.txt
Updates godo to version 1.57.0: https://github.com/digitalocean/godo/releases/tag/v1.57.0
> update godo to version 1.57.0

- commands/volume_actions.go
- commands/volume_actions_test.go
- do/mocks/VolumeActionsService.go
- do/volume_actions.go
- integration/compute_volume_action_test.go
extending the volume-action cli with a "list" sub command.
> Adding compute volume-action list cli

- .gitignore
- commands/kubernetes.go
- commands/kubernetes_test.go
- integration/kubernetes_clusters_create_test.go
> 1-clicks in existing k8s cluster

- CONTRIBUTING.md
adding prereqs for tagging a release
> Documentation Update

- README.md
Make information about available environment variables more visible
This closes #985
> Update environment variables section to the readme

- commands/kubernetes.go
> updating kubernetes cluster kubeconfig save doc

- go.mod
- go.sum
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/action.go
- vendor/github.com/digitalocean/godo/apps.gen.go
- vendor/github.com/digitalocean/godo/apps.go
- vendor/github.com/digitalocean/godo/databases.go
- vendor/github.com/digitalocean/godo/doc.go
- vendor/github.com/digitalocean/godo/domains.go
- vendor/github.com/digitalocean/godo/droplet_actions.go
- vendor/github.com/digitalocean/godo/droplets.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/digitalocean/godo/image_actions.go
- vendor/github.com/digitalocean/godo/keys.go
- vendor/github.com/digitalocean/godo/kubernetes.go
- vendor/github.com/digitalocean/godo/metrics/metrics.go
- vendor/github.com/digitalocean/godo/metrics/time.go
- vendor/github.com/digitalocean/godo/metrics/values.go
- vendor/github.com/digitalocean/godo/monitoring.go
- vendor/github.com/digitalocean/godo/registry.go
- vendor/github.com/digitalocean/godo/snapshots.go
- vendor/github.com/digitalocean/godo/storage_actions.go
- vendor/modules.txt
Pulls in the latest godo with support for new App Platform features. Fixes: https://github.com/digitalocean/doctl/issues/1059
> Update godo to v1.71.0.

- go.mod
- go.sum
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/apps.gen.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/modules.txt
Updates the godo dependency to the latest version.
Fixes #1064
> Update godo to v1.72.0

- go.mod
- go.sum
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/apps.gen.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/modules.txt
> APPS-5270: bump godo for App Platform "features" support

- commands/sandbox.go
The newer 'nim' invokes newer configurations of the builder system functions, allowing more efficient and secure remote builds.
Also includes a change so that builds of `golang` sandbox projects are remote by default.
> Increment to nim version 3.0.4 to obtain better remote build behavior

- commands/sandbox.go
To support the new e2e tests for sandbox functionality (running under `bats` in the companion `doctl-sandbox-plugin` repo), it will often be necessary to manipulate the `minSandboxVersion` variable so that it can be the next (rather than current) version that is tested.    For clean tests that are not contaminated by (and do not contaminate) any existing installation, we also need to relocate the sandbox installation area for the test.   This is especially important when we add e2e tests for install and upgrade.
This PR simply adds support for two new environment variables, `minSandboxVersion`, and `sandboxDirectory` to be used for this purpose.   These will not be documented for production use by customers.
> Support e2e tests with added env vars

- do/sandbox.go
This change is in support of an upcoming change to serverless clusters whereby they will have two domain names.   The API call to retrieve the sandbox namespace will, by convention, only have one of these names.  We will need to map it, conditionally, to the other.   The prefix of the namespace name ("fn-" or not) is consulted to decide whether the remapping should occur.
All fn* namespaces should be mapped to the cloudflare managed domain - doserverless.co
All other namespaces continue to be mapped to doserverless.io
This is to ensure backward compatibility for existing sandbox namespaces.
> Store API host with different final domain segment

- commands/auth.go
- commands/databases.go
- commands/databases_test.go
- commands/displayers/database.go
- commands/doit.go
- do/databases.go
- do/mocks/DatabasesService.go
- go.mod
- go.sum
- integration/errors_test.go
- vendor/github.com/containerd/continuity/AUTHORS
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/apps.gen.go
- vendor/github.com/digitalocean/godo/apps.go
- vendor/github.com/digitalocean/godo/balance.go
- vendor/github.com/digitalocean/godo/billing_history.go
- vendor/github.com/digitalocean/godo/databases.go
- vendor/github.com/digitalocean/godo/droplets.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/docker/cli/cli/config/configfile/file.go
- vendor/github.com/docker/cli/cli/config/configfile/file_unix.go
- vendor/github.com/docker/cli/cli/config/credentials/default_store_unsupported.go
- vendor/modules.txt
> Sync main branch

- internal/apps/builder/builder.go
- internal/apps/builder/cnb.go
- internal/apps/builder/cnb_test.go
- internal/apps/builder/docker.go
- internal/apps/builder/docker_test.go
* Adds in support for build time environment variables
* Allows overrides w/ the `userOverrides` environment file
* Centralized env logic into `baseComponentBuilder`
> Add support for build environment variables

- Dockerfile
- commands/auth.go
- commands/databases.go
- commands/databases_test.go
- commands/displayers/database.go
- commands/doit.go
- do/databases.go
- do/mocks/DatabasesService.go
- dockerfiles/Dockerfile.snap
- go.mod
- go.sum
- integration/errors_test.go
- snap/snapcraft.yaml
- vendor/github.com/containerd/continuity/AUTHORS
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/apps.gen.go
- vendor/github.com/digitalocean/godo/apps.go
- vendor/github.com/digitalocean/godo/balance.go
- vendor/github.com/digitalocean/godo/billing_history.go
- vendor/github.com/digitalocean/godo/databases.go
- vendor/github.com/digitalocean/godo/droplets.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/docker/cli/cli/config/configfile/file.go
- vendor/github.com/docker/cli/cli/config/configfile/file_unix.go
- vendor/github.com/docker/cli/cli/config/credentials/default_store_unsupported.go
- vendor/modules.txt
This PR updates the `feature/serverless` branch with changes that have meanwhile occurred on the `main` branch.  The reason for the change is that it will make the planned merge of the `feature/serverless` branch into `main` capable of being performed automatically without fixing conflicts.   Conflicts were fixed while performing the main->feature merge in my fork.
> Update feature/serverless with intervening main branch changes

- Dockerfile
- commands/auth.go
- commands/databases.go
- commands/databases_test.go
- commands/displayers/database.go
- commands/doit.go
- do/databases.go
- do/mocks/DatabasesService.go
- dockerfiles/Dockerfile.snap
- go.mod
- go.sum
- integration/errors_test.go
- snap/snapcraft.yaml
- vendor/github.com/containerd/continuity/AUTHORS
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/apps.gen.go
- vendor/github.com/digitalocean/godo/apps.go
- vendor/github.com/digitalocean/godo/balance.go
- vendor/github.com/digitalocean/godo/billing_history.go
- vendor/github.com/digitalocean/godo/databases.go
- vendor/github.com/digitalocean/godo/droplets.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/docker/cli/cli/config/configfile/file.go
- vendor/github.com/docker/cli/cli/config/configfile/file_unix.go
- vendor/github.com/docker/cli/cli/config/credentials/default_store_unsupported.go
- vendor/modules.txt
This update of the `feature/serverless` branch includes commits taken from the `main` branch with some adjustments to overcome conflicts.  These are the commits since the last time the branches were synced.
This is being done to prepare for a subsequent merge of `feature/serverless` into `main`.  Because of file name changes, there are some merge conflicts that would otherwise arise.  Those conflicts are fixed with this PR so that the subsequent merge into main will be painless.
It is important that the merge of this PR be done without squashing.   If squash-and-merge is employed, then the commits just adopted from main will no longer be identifiable as such on the branch and the second merge will be conflicted after all.
> Update feature/serverless with latest changes from main

- args.go
- commands/apps.go
- commands/apps_dev.go
- commands/apps_dev_config.go
- commands/apps_dev_config_test.go
- commands/apps_dev_test.go
- commands/apps_test.go
- commands/charm/charm.go
- commands/charm/textbox/textbox.go
- doit.go
- internal/apps/apps.go
- internal/apps/apps_test.go
- internal/apps/config/appdev.go
- internal/apps/config/config.go
- internal/apps/config/config_test.go
- internal/apps/config/doctl.go
- internal/apps/config/doctl_test.go
- internal/apps/workspace/workspace.go
- internal/apps/workspace/workspace_test.go
@andrewsomething - please review the `doit.go` changes.
> appdev: config updates: add hierarchy and per-component overrides, updated env-file handling

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile
- do/actions.go
- dockerfiles/Dockerfile.snap
- go.mod
Updates supported go versions to 1.19.x and 1.18.x
> upgrade to support go 1.19 & 1.18

- args.go
- commands/displayers/reserved_ip.go
- commands/droplets.go
- commands/namespaces.go
- commands/reserved_ips.go
- commands/serverless.go
- commands/serverless_test.go
- do/serverless.go
- go.mod
- go.sum
- integration/droplet_create_test.go
- integration/floating_ip_create_test.go
- integration/floating_ip_get_test.go
- integration/floating_ip_list_test.go
- integration/projects_resources_get_test.go
- integration/reserved_ip_create_test.go
- integration/reserved_ip_get_test.go
- integration/reserved_ip_list_test.go
- snap/snapcraft.yaml
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/databases.go
- vendor/github.com/digitalocean/godo/floating_ips.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/digitalocean/godo/reserved_ips.go
- vendor/modules.txt
The purpose here is to catch up the `feature/serverless` branch with changes that have meanwhile occurred on the `main` branch.   This is preparatory to the next series of "important" merges into `feature/serverless`.
> Merge main into feature/serverless

- commands/apps_dev.go
* Update output image messaging with correct ports based on component spec
* Update messaging for worker / job type components to remove the port instructions
> check component type for http port when printing run info

- commands/apps_dev.go
- commands/apps_dev_config.go
- commands/errors.go
- internal/apps/workspace/workspace.go
cc @andrewsomething for `commands/errors.go` changes.
> appdev: require git workspaces, update example config file

- internal/apps/builder/cnb.go
> appdev: clearer copying workspace to container message

- commands/apps_dev.go
- internal/apps/workspace/workspace.go
* Updates app dev help messaging
* Unhides the `app dev` command subtree
> unhide the appdev command subtree

- commands/activations_test.go
- commands/namespaces.go
- commands/namespaces_test.go
- commands/serverless.go
- commands/serverless_test.go
- commands/serverless_util.go
- do/mocks/ServerlessService.go
- do/serverless.go
There was a priority bug fix on main that affected serverless and this crossed with my previous update of the feature branch.   So, I'm doing this one more conflict resolution merge from main to feature/serverless.
> Main incorporation (deja vu all over again)

- commands/functions.go
> Adds better output for long running functions invoked synchronously

- commands/displayers/triggers.go
- commands/triggers_test.go
- do/serverless.go
Updates triggers request to use new API endpoints, and updates the trigger structure.
> Updates the triggers API endpoint and structure to use the new API.

- commands/load_balancers.go
- commands/load_balancers_test.go
> LBAAS-2450 Support project id for loadbalancers

- commands/triggers.go
- commands/triggers_test.go
- do/mocks/ServerlessService.go
- do/serverless.go
- Adds subcommands to enable a disable a trigger.
> Adds subcommands to enable/disable a trigger

- commands/auth.go
Reverts digitalocean/doctl#1332
> Revert "commands/auth: stop printing the token to stdout"

- go.mod
- go.sum
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/databases.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/digitalocean/godo/uptime.go
- vendor/modules.txt
Bump godo to v1.86.0 to support database's promote a read replica (clustered database) to become a primary db cluster
> Bump godo to v1.96.0

- scripts/_build.sh
- snap/snapcraft.yaml
This PR adds the trimpath flag to doctl builds.
> add trimpath flag to build

- commands/doit.go
- commands/monitoring.go
- commands/monitoring_test.go
Moves the `uptime` command under monitoring.
> uptime: move under monitoring

- Makefile
This change updates the Makefile to introduce arm64 support for local builds.
> Adds local build support for arm64

- commands/volume_actions.go
This PR resolves a reported broken link in the volumes documentation.
> Broken link fix for Volumes

- commands/databases.go
- commands/displayers/database.go
- go.mod
- go.sum
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/databases.go
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/stretchr/testify/assert/assertion_compare.go
- vendor/github.com/stretchr/testify/assert/assertion_format.go
- vendor/github.com/stretchr/testify/assert/assertion_forward.go
- vendor/github.com/stretchr/testify/assert/assertion_order.go
- vendor/github.com/stretchr/testify/assert/assertions.go
- vendor/github.com/stretchr/testify/assert/doc.go
- vendor/github.com/stretchr/testify/assert/http_assertions.go
- vendor/github.com/stretchr/testify/require/doc.go
- vendor/github.com/stretchr/testify/require/require.go
- vendor/github.com/stretchr/testify/require/require_forward.go
- vendor/modules.txt
This bumps the godo version and makes the needed changes so that Kafka options are displayed.
> databases: Display Kafka options.

- go.mod
- go.sum
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/apps.gen.go
- vendor/github.com/digitalocean/godo/apps_accessors.go
- vendor/github.com/digitalocean/godo/uptime.go
- vendor/modules.txt
See https://github.com/digitalocean/godo/releases/tag/v1.104.0 for the payload.
> Bump godo to v1.104.0

- do/serverless.go
- internal/apps/builder/cnb.go
This PR adds missing error handlings.
> Fix missing error handling

- commands/load_balancers.go
This PR adds additional clarity to the `doctl compute load-balancer update` command.
> Load balancer update clarification

- commands/apps.go
> apps: Add log type for restarted containers

- commands/kubernetes.go
Updates and clarifies the doc strings for the Kubernetes commands. This also adds examples for each command.
> Docs audit: Kubernetes

- commands/functions.go
Updates and clarifies doc strings for Functions management commands. This also adds an example to each command.
> Docs audit: Functions

- commands/firewalls.go
Updates and clarifies doc strings for Firewall management commands. This also adds examples to each command.
> Docs audit: Firewalls

- commands/projects.go
Updates and clarifies doc strings for Project commands. This also provides examples for each command.
> Docs audit: Projects

- commands/vpcs.go
Updates and clarifies doc strings for VPC commands. Also add examples for each command.
> Docs audit: VPC

- internal/apps/builder/cnb.go
https://do-internal.atlassian.net/browse/APPS-8334
Update cn builder image to new apps-images tag
> Update cnb builder image

- .github/workflows/typos.yml
Depends on https://github.com/digitalocean/doctl/pull/1551
> ci: spellcheck github action

- commands/databases.go
- commands/databases_test.go
- do/databases.go
- do/mocks/DatabasesService.go
- integration/database_connection_pool_test.go
This adds the missing update functionality for database connection pools, as identified in https://github.com/digitalocean/doctl/issues/1553.
> databases: update connection pool

- commands/monitoring.go
These have long been out of beta. Somehow we've missed this until now. :facepalm:
> monitoring: remove beta label

- commands/displayers/partner_interconnect_attachment.go
- commands/partner_interconnect_attachment.go
- commands/partner_interconnect_attachment_test.go
- do/mocks/PartnerInterconnectAttachmentsService.go
- do/partner_interconnect_attachments.go
- go.mod
- go.sum
- integration/partner_interconnect_attachment_test.go
- vendor/github.com/digitalocean/godo/CHANGELOG.md
- vendor/github.com/digitalocean/godo/godo.go
- vendor/github.com/digitalocean/godo/kubernetes.go
- vendor/github.com/digitalocean/godo/load_balancers.go
- vendor/github.com/digitalocean/godo/partner_interconnect_attachments.go
- vendor/modules.txt
Testing:
Get bgp auth key:
```
➜  builds git:(VPC-4215/bgp_key) ✗ ./doctl --context new_s2 network --type "partner" interconnect-attachment get-bgp-auth-key 7b48cbc3-cacb-418e-908c-a9a86189a642
Value
0xXXXXXXXXXXXXXX
```
Regenerate service key:
```
➜  builds git:(VPC-4215/bgp_key) ✗ ./doctl --context new_s2 network --type "partner" interconnect-attachment regenerate-service-key 7b48cbc3-cacb-418e-908c-a9a86189a642
```
> [VPC-4215] Support PIA Get BGP auth key and regenerate service key

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Dockerfile
- go.mod
Bumps doctl to Go version 1.24.
> Bump Go version to v1.24

- commands/partner_network_connect.go
Unhide Partner Network Connect commands
> unhide partner network connect

- commands/databases.go
> Fix databases maintenance-window get example command

- args.go
- commands/displayers/genai.go
- commands/genai.go
- commands/genai_openai_key.go
- commands/genai_openai_key_test.go
- do/genai.go
- do/mocks/GenAIService.go
- integration/genai_openai_key_create_test.go
- integration/genai_openai_key_delete_test.go
- integration/genai_openai_key_get_test.go
- integration/genai_openai_key_list_test.go
- integration/genai_openai_key_update_test.go
Added implementation for following APIs - 
- List OpenAI API Keys
- Create OpenAI API Key
- Get OpenAI API Key
- Update OpenAI API Key
- Delete OpenAI API Key
- List agents by OpenAI key
> OpenAI Keys Implementation

- do/serverless.go
This reverts commit 08b3c63852fbf5e4c94af1911488289be5caddcb.
> Revert "Updated minServerlessVersion to 5.0.22 (#1727)"
