digitalocean/doctl

main.go, main_test.go
Hooks into cli's `Before` error handling for global flags and adds tests!
cc @aybabtme @bryanl @macb
=> Extract cli.App building and add tests for global flags.

main.go, main_test.go
Typing `doctl` on its own should not produce an error when `doctl
--help` would not.
=> Don't require API key if no args were passed

droplet.go
This was automatically appending the region on the end of the droplet. The logic was broken due to a type mismatch between the arg definition and the check.
=> Invalid type on --add-region parameter

README.md
Copies in the installation section from the community tutorial, per a few users who have had some difficulty getting the binary into a `$PATH`-included location.
=> Add installation instructions from community tutorial

README.md
So, per #24:
go get github.com/digitalocean/doctl/cmd/doctl
...seems to be the one-liner that works here, but let me know if this should be something different.
=> README.md installation section:  tweak go get path

commands/doit.go, commands/ssh.go, commands/ssh_test.go, pkg/runner/mocks/Runner.go
Add explicit parent to SSH command, so it can create configuration keys in the proper place. This solves the problem of ssh flags not working since they were be being searched for in `doit.ssh.*` instead of `compute.ssh.*`.
Fixes #30
=> Add explicit parent to SSH command

scripts/stage.sh
Release builds will now have a version string that looks like: `doctl version 1.0.0-release`
Fixes: #22
=> Remove dev label from release builds

commands/droplet_actions.go, do/pagination.go, do/pagination_test.go
* Kernel lists had no formating or header options.
* Pagination skipped the second page of results.
Fixes #33
=> Issues with listing droplet kernels

commands/droplets.go, commands/droplets_test.go, commands/errors.go
When deleting droplets, cycle through the following logic:
* check for ambiguous names. e.g. multiple droplets named ubuntu
* build a list of droplets to delete and execute them all at once
* don't allow deleting the same droplet twice (by name or id)
Fixes #18
=> Add more logic around droplet deletes

commands/auth.go, commands/commands_test.go, commands/images.go, commands/regions.go, commands/sizes.go
I noticed a number of commands with a `list` subcommand do not have the `ls` alias. For the sake of consistency, this adds those where missing. It also adds a check to the `assertCommandNames` function to ensure future `list` commands are given the alias.
=> Ensure all 'list' commands are aliased to 'ls'

commands/droplet_actions.go, commands/droplet_actions_test.go
Use image instead of image id when rebuilding droplets. The argument was tagged with `ArgImage` when it should have been tagged with `ArgImage`. Since doctl has to be GIGO, it was happy to pass the blank string upstring to the API.
=> use image instead of image id when rebuilding droplets

args.go, commands/commands_test.go, commands/doit.go, commands/droplets.go, commands/droplets_test.go, commands/output.go, commands/tags.go, commands/tags_test.go, do/droplets.go, do/mocks/DropletsService.go, do/mocks/TagsService.go, do/tags.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/droplets_test.go, vendor/manifest
Allow `doctl` to access functionality exposed by DigitalOcean [tags](https://developers.digitalocean.com/documentation/v2/#tags). 
Adds the following new commands:
* create a new tag: `doctl compute tag create <tag name>`
* retrieve a tag: `doctl compute tag get <tag name>`
* list all tags: `doctl compute tag list`
* list droplets by tag: `doctl compute droplet list --tag-name <tag name>`
* update a tag: `doctl compute tag update <tag name> --name <new tag name>`
* tag a resource (droplet): `doctl compute droplet tag <droplet name or id> --tag-name <tag name>`
* untag a resource (droplet): `doctl compute droplet untag <tag name or id>`
* delete a tag: `doctl compute tag delete <tag name>`
* delete droplets by tags `doctl compute droplet delete --tag-name <tag name>`
=> Add tags commands

doit.go, doit_test.go
The current message reads kind of weird. When I saw it, I found
it a bit confusing, because it just states "x is greater than y".
It took me a couple seconds parse the information and understand
"oh you mean there's a newer version and I should update?".
```
doctl version 1.0.0-dev
"1.0.2" is a newer release than "1.0.0-dev"
```
Since the current version is already printed, we don't need to
repeat "this is version x, version y is greater than version x".
We can just say "this is version x, version y is available!".
Then we can make the message a bit less impersonal, and try to encourage
users to perform an action "hey this version is avail, try it!".
So it ends up like this:
```
doctl version 1.0.0-dev
release 1.0.2 is available, check it out!
```
r: @bryanl
=> make new-version message appeal to action

commands/ssh.go, commands/ssh_test.go
Currently `ssh-user` is always overwritten by user extracted from droplet id. I'm not sure even that there are cases where droplet id contains user, so it's almost always an empty string.
=> ssh: respect ssh-user flag

README.md
Current instructions are not as explicit as they could be. In particular, the links provided in the code blocks are for Linux only and the text doesn't capture attention enough to remind users to change the string.
Also, the distinction between `wget` and `curl` is not necessary on OS X, since `curl` ships by default.
1. highlight the preferred method (package managers)
2. fence install methods by OS
3. make the code block clearly show what link to use
4. skip the "and then you can untar" part, which isn't necessary/adds noise.
r: @bryanl
=> make install instructions more specific

do/pagination.go
I think this is the bug, but I'll let CI run the tests.
Essentially pagination is 1 indexed, and not 0 indexed. So we re-fetch the first page, but never fetch the second, getting a "second page" full of dupes.
=> doctl: pagination is 1 indexed, not 0 indexed

doit.go, doit_test.go
`doctl` reports that there is a new version available even though the most recent release is installed:
```
$ doctl version
doctl version 1.2.0-release
Git commit hash: 4d9207c
release 1.2.0 is available, check it out!
```
This is because the release process adds the `release` label while the git tag for the release does not contain that. See:
https://github.com/digitalocean/doctl/blob/master/scripts/stage.sh#L34
`github.com/blang/semver` is used to compare the versions and `1.2.0` is considered a higher version than `1.2.0-release`. You can test this with:
```go
package main
import (
"fmt"
"github.com/blang/semver"
)
func main() {
v0, err1 := semver.Make("1.0.0")
v1, err2 := semver.Make("1.0.0-release")
if err1 == nil && err2 == nil && v0.GT(v1) == true {
fmt.Printf("%q gt %q", …
```
=> Don't report new release available when already installed.

args.go, commands/commands_test.go, commands/ssh.go, commands/ssh_test.go, doit.go, pkg/ssh/ssh.go, pkg/ssh/ssh_external.go
It doesn't work on Windows, since the custom ssh client for Windows
doesn't have agent support yet, as stated in issue #65.
This feature has been requested in issue #77.
That's my first contribution to doctl, comments are welcome!
=> Add a --ssh-agent-forwarding flag

.gitignore, README.md, commands/auth.go, commands/auth_test.go, commands/commands_test.go, commands/doit.go, commands/errors.go, commands/xdg.go, commands/xdg_windows.go, commands/xdg_windows_test.go, do/account.go, do/sshkeys.go, doit.go, util.go
Introduces `dolt auth init` command which replaces `dolt auth login`.
Instead of trying to fetch the token from the API, the user will have to manually enter it instead.
Also moves the default configuration location to `$XDG_CONFIG_HOME/doctl/doctlcfg`. On Windows, the default location is `%APPDATA%/doctl/config` and on other platform without the environment variable set, it will look in `$HOME/.config/doctl`. 
If the legacy location is detected, a warning will be displayed.
Fixes #59 
Fixes #94
=> Introduce `doctl auth init`

README.md
The links point to a non-existent version.
=> Fix download links for OSX and Linux in README

commands/droplets.go
#124
For production of valid JSON output when creating multiple droplets. Was just outputting concatenated single-item lists before, so we had a root level `][` with no comma (see issue).
=> Multiple droplet creation: valid JSON output

commands/droplets.go, commands/droplets_test.go, doit.go
* Change command for untagging to `doctl compute untag <droplet id or
name> [droplet id or name] —tag-name foo`
* Catch broken pflags earlier in the chain, so string slice fetching
works sanely
fixes: #119
=> Allow untagging droplets

README.md
This is result of bug report #131
Myself I had problem using `doctl auth init` that would make me Auth my PC and DigitalOcean on easy way. 
As far as I noticed that feature is missing in v1.3.1.
Because I think some people will just copy link if they have OS X or Linux x64, it would not be bad to update links in README.md.
This could be applied to [DigitalOcean Community Tutorial](https://www.digitalocean.com/community/tutorials/how-to-use-doctl-the-official-digitalocean-command-line-client) too
=> Update README.md with latest Release version

commands/doit.go
When you type doctl in your terminal, this will fire up:
```
doctl is a command line interface for the DigitalOcean API.
Usage:
doctl [command]
Available Commands:
account     account commands
auth        auth commands
compute     compute commands
version     show the current version
Flags:
-t, --access-token string   API V2 Access Token
-c, --config string         config file (default is $HOME/.doctlcfg)
-h, --help                  help for doctl
-o, --output string         output format [text|json] (default "text")
--trace                 trace api access
-v, --verbose               verbose output
Use "doctl [command] --help" for more information about a command.
```
Opening `$HOME/.doctlcfg` in your favorite text editor will open empty/no-existing file.
Writing anything in it, and …
=> Change default config location from $HOME/.doctlcfg to $HOME/.config/doctl/config.yaml

args.go, commands/confirmation.go, commands/confirmation_test.go, commands/doit.go, commands/droplets.go, commands/droplets_test.go, commands/errors.go
Fixs #109 
Continues work from #110 
@bryanl I would like review if possible, in free time ofc. :D
This is basic yes/no confirmation. User need to answer `y`, `ye` or `yes`. For every other answer, command will be stopped.
For now it is only implemented for Droplet delete action.
List of done things that are working:
Things could be done:
First of all I created confirmation.go because of reusability. It would not be bad to extend it on volume delete, images delete, but this is something we will discuss later. Anyways I decided to make it reusable from beginning.
It is working like, you have to answer `y` or `yes` (case doesn't matters as I convert it to lower). If you answer anything other, operation will be aborted.
I added Force flag to `doit`, but I'm not sure is it right way, I would …
=> [Fixs #109] Adding confirmation on delete actions

README.md, commands/domains.go
@bryanl I found some typos over project.
At `README.md` I updated link as old one redirects to this. 
Also I think project is now @ `digitalocean/doctl` instead of `bryanl/digitalocean`. Not sure is it indeed but I will revert back if it is really `bryanl/digitalocean`.
About `domains.go`, well it's really not droplet :D
Found something more but gonna make issue to ask something first
=> Fixed typos in README.md and domains.go

Dockerfile, README.md
Hi,
I added a Dockerfile, so doctl can be used within a docker container. This can be useful if you are in a container environment, like CoreOS.
=> Add the option to run doctl within a docker container

.gitignore, snap/snapcraft.yaml
This adds snapcraft.yaml which can be used with the snapcraft command to create snap packages. snap is the "new" packaging format that will work across all major Linux distros. 
snaps can be easily created with one command: `cd snap && snapcraft`
snaps can then be easily installed with: `snap install doctl_*_amd64.snap`
And even better, it can be uploaded to the ubuntu store, and users just need to run one to install: `snap install doctl`
Read more:
- http://snapcraft.io/
=> Add snapcraft.yaml

commands/droplets_test.go, commands/images.go, commands/images_test.go
Fixs #133 
This is continued work on #139, which was closed because I pushed commits to it instead of another branch. 
Problem with last PR was test units. At that time, I didn't know how to make test units and it was in TODO state.
This is not the case anymore, I learned more about `doctl` & `go` and it's here. Test passes successfully, I hope test changes will not make another problem.
Multiple delete has been tested, it is working flawless.
Beside that, confirmation like on droplets are added (incl. `force` flag). I don't know is it problem, or no, but I can revert it if it is not good place for it.
=> Ability to delete multiple snapshots and confirmation before delete

commands/tags.go, commands/tags_test.go
Droplet Tagging is released today, tags are more relevant.
First change is that you have possibility to delete multiple tags.
Second one is thing I add one by one is delete confirmation. Now you're asked are you sure or you have to specify `--force` flag.
Also test for multiple delete is added.
=> Added multiple tag delete, tag delete confirmation

args.go, commands/droplets.go, commands/droplets_test.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/droplets_test.go, vendor/github.com/digitalocean/godo/floating_ips_actions_test.go, vendor/github.com/digitalocean/godo/godo_test.go, vendor/manifest
This allows `tag-names` as an attribute for droplet create, in accordance with https://developers.digitalocean.com/documentation/changelog/api-v2/tagging-in-droplet-create/.
cc @hugocorbucci @daveworth
=> allow "tags" attribute for droplet create

commands/droplets.go, commands/droplets_test.go
Fixes #127 
Runs check to ensure tags exist before creating droplet
=> Improves tag handling for droplet create

commands/volumes.go, commands/volumes_test.go
Fixes #137 
I've followed pattern from `droplets.go` and I successfully created Volume filtering.
I hope it's right way to do it, when I test, it's working flawless.
Beyond that, I added Region filtering and ID filtering. Region filtering is present in `droplets.go` but ID one is addition in `volumes.go`.
Output of `doctl compute volume list`:
```
ID                  Name        Size    Region  Droplet IDs
42db5324-9ad6-11e6-aef4-000f53315a41    volume-nyc1-01  1 GiB   nyc1    
5e17d1c0-9ad6-11e6-bd40-000f53315820    volume-nyc1-02  1 GiB   nyc1    
442a1a5f-9ae5-11e6-b290-000f5339d321    volume-sfo2-01  1 GiB   sfo2    [30553301]
```
Output of `doctl compute volume list volume-nyc1-01`:
```
ID                  Name        Size    Region  Droplet IDs
42db5324-9ad6-11e6-aef4-000f53315a41 …
```
=> Added Volume filtering, Fixes #137

commands/output.go
This PR allows users to show the `PrivateIPv4` address of their Droplet:
``` bash
./doctl compute droplet list 
ID      Name    Public IPv4 Private_IPv4    Public IPv6 Memory  VCPUs   Disk    Region  Image       Status  Tags
30026164    master  46.101.202.80   10.135.7.30         8192    4   80  fra1    CentOS 7.2 x64  active
30026165    node-0  139.59.208.44   10.135.8.4          8192    4   80  fra1    CentOS 7.2 x64  active
30026166    node-1  138.68.86.218   10.135.18.66            8192    4   80  fra1    CentOS 7.2 x64  active
30026167    node-2  46.101.237.124  10.135.26.105           8192    4   80  fra1    CentOS 7.2 x64  active
30026168    node-3  46.101.125.172  10.135.26.123           8192    4   80  fra1    CentOS 7.2 x64  active
```
=> Add private IPv4 address to output

args.go, commands/droplets.go, commands/droplets_test.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/droplets_test.go, vendor/github.com/digitalocean/godo/godo_test.go, vendor/github.com/digitalocean/godo/storage.go, vendor/github.com/digitalocean/godo/storage_test.go, vendor/manifest
Depends on https://github.com/digitalocean/godo/pull/117
Build should fail until PR above is merged and vendored code is updated.
=> Add monitoring flag

commands/auth.go
The "Validating token: " message used to end with ": ", which looks like a prompt for more info. The ellipsis implies that doctl itself is doing something instead of waiting for more user input.
This is a really small change. I needed to re-`auth init` on a slow connection and had that "prompt" sitting in for more than a few seconds. I then pasted the access token again because I though it was waiting for something. The error really is on my part, but I think this makes things clearer.
=> Imply that doctl is actively doing something

args.go, commands/ssh.go, commands/ssh_test.go, doit.go, pkg/ssh/ssh.go, pkg/ssh/ssh_external.go
With this PR, we should fix #168. However, this is not really same idea as it's in issue.
Issue is proposing following implementation:
```
doctl compute ssh mydroplet uptime
```
I decided to follow template of SSH unit, so I went with flag (`--ssh-command`).
When I execute `doctl compute ssh mydroplet`, I'll work as usual.
When I execute `doctl compute ssh test1 --ssh-command uptime`, it'll will only return output of command, as expected:
```
22:32:26 up  1:07,  0 users,  load average: 0.00, 0.00, 0.00
```
I want to know do you like it, how it looks and could it be done better.
Just to note, this is only implemented for external SSH (OS X & Linux). I need to look more in Windows implementation of SSH client, but first I want to know is this one OK. If this is right, I'll do the same for …
=> [Fixes #168] Implementing command forwarding for external SSH

Dockerfile
Changed `Dockerfile` to use version `1.5.0` instead of `1.4.0`.
cc @nanzhong
=> Bumping Dockerfile doctl version to 1.5.0

commands/image_actions.go, commands/image_actions_test.go
This Pull Request addresses issue #192.
Executing Transfer command like:
```
$ doctl compute image-action transfer -o json --region sgp1 12345
```
would result in error that Action Type is not available:
```
{"errors":[{"detail":"could not transfer image: POST https://api.digitalocean.com/v2/images/12345/actions: 404 The specified action type is not available."}]}
```
By the [API docs](https://developers.digitalocean.com/documentation/v2/#transfer-an-image), it's also required to send type in the request. This PR implements it.
Response after change:
```
[
{
"id": 12345,
"status": "in-progress",
"type": "transfer",
"started_at": "2017-03-04T18:49:16Z",
"completed_at": null,
"resource_id": 12345,
"resource_type": "image"
}
]
```
cc @viola @caueguerra @aybabtme
=> [Fixes #192] Added type transfer to image-action transfer

README.md
README was stating to use `auth login` which is deprecated as of 1.4.0.
If above can be said better, please let me know and I'll update it.
cc @mauricio @viola
=> replace 'auth login' with 'auth init' in readme

Dockerfile
This is a minor change for something that I noticed while checking out the Dockerfile for this project – Alpine 3.3 and above support the `--no-cache` option in `apk` that will update the package index at runtime and not cache the results locally. This means that `--update` is not required and the additional cache removal step can be skipped.
[Alpine's documentation](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md#disabling-cache) explains further.
=> [Dockerfile] Use apk's --no-cache option instead of updating and removing cache

do/images.go
This PR fixes #198.
Looking by the code, I think this was unintended behavior, as on [L40/images.go](https://github.com/digitalocean/doctl/blob/master/commands/images.go#L40) it states that default for Public Images is `false`.
If it is indeed to show all images, including public ones, this change should be kept with changing default flag value to `true`.
cc @viola @caueguerra @lxfontes
=> Fixes #198 - Hide public images by default

.travis.yml
This PR updates Go version for Travis-CI.
`1.x` represents latest major or minor Go version.
cc @mauricio
=> Update Travis-CI Go version to 1.x

commands/tags.go, commands/tags_test.go, do/mocks/TagsService.go, do/tags.go
Per [our changelog](https://developers.digitalocean.com/documentation/changelog/api-v2/deprecating-update-tag/), tag rename will be deprecated on April 26, 2017.
cc @mauricio @hugocorbucci @magicgrl111
=> Deprecate tag rename (PUT /v2/tags/:name)

commands/volume_actions.go, commands/volume_actions_test.go, do/volume_actions.go, vendor/github.com/digitalocean/godo/storage.go, vendor/github.com/digitalocean/godo/storage_actions.go, vendor/github.com/digitalocean/godo/storage_actions_test.go, vendor/github.com/digitalocean/godo/storage_test.go, vendor/manifest
This PR removes Detach function which was removed from API.
Proposal: Rename `detach-by-droplet-id` to `detach`. As there is only one detach function (there is by name also in API too) I think we could rename it to Detach only.
I would love to hear opinions.
Fixes #207.
cc @mauricio
=> Remove Detach function

commands/certificates.go, commands/certificates_test.go
```
$ doctl compute certificate create --help
create new certificate
Usage:
doctl compute certificate create [flags]
Aliases:
create, c
Flags:
--certificate-chain-path string   path to a certificate chain
--leaf-certificate-path string    path to a certificate leaf (required)
--name string                     certificate name (required)
--private-key-path string         path to a private key for the certificate (required)
```
`$ doctl compute certificate create --name web-cert-01 --private-key-path ~/my-secrets/priv-key.pem --leaf-certificate-path ~/my-secrets/leaf-cer.crt`
```
ID                                      Name           SHA-1 Fingerprint                           Expiration Date         Created At
cf0d1458-0809-4d41-a70c-eb7b76363db6    web-cert-01 …
```
=> Allow certificate-chain-path to be optional.

commands/volume_actions.go, commands/volume_actions_test.go, do/mocks/VolumeActionsService.go, do/volume_actions.go
This PR renames function `detach-by-droplet-id` to `detach`. Providing Droplet ID is as of [April 4th, 2017](https://github.com/digitalocean/godo/pull/136#issuecomment-291612894) required and it's not possible to detach without anymore.
`detach-by-droplet-id` is long for a function and makes its usage inconvenient.
This PR also regenerates mocks as it was forgotten in #208.
cc @mauricio @hugocorbucci @mchitten @magicgrl111
=> Rename DetachByDropletID function to Detach

commands/completion.go
This PR fixes command description typos.
We didn't actually implement `fish` shell (was planned but paused for now) but it was left in description as feature.
/cc @mauricio
=> completion: fix command description typos

.dockerignore
As currently the whole directory is sent to the docker socket including the `.git` directory the build context keeps growing with every commit.
As the Dockerfile downloads everything from external sources ignore the whole repository besides the Dockerfile itself, minimized the build context sent to docker.sock from >80MB to 3.072 kB.
=> Minimize Docker build context

commands/completion.go
This PR makes completion code generation independent on auth status.
With current code, if you try to generate completion code before you authenticate with doctl and DO, it will show following error:
```
Error: unable to initialize DigitalOcean api client: access token is required. (hint: run 'doctl auth init')
```
This makes problem in case we want to integrate code generation into package managers such as brew and snap.
Using `cmdBuilderWithInit` seems to fix the problem if it's appropriate use for that builder.
/cc @mauricio
=> completion: make completion code generation independent on auth status

args.go, args_short.go, commands/certificates.go, commands/certificates_test.go, commands/domains.go, commands/domains_test.go, commands/droplets.go, commands/droplets_test.go, commands/floating_ips.go, commands/floating_ips_test.go, commands/images.go, commands/images_test.go, commands/load_balancers.go, commands/load_balancers_test.go, commands/snapshots.go, commands/snapshots_test.go, commands/sshkeys.go, commands/sshkeys_test.go, commands/tags.go, commands/tags_test.go, commands/volumes.go, commands/volumes_test.go
This PR adds Ask for confirm on all delete actions.
Currently, AskForConfirm is implemented only for Droplets and functions added after confirmation was implemented. Inconsistency can cause confusion and I like keeping up with one pattern. 
This PR also renames `ArgDeleteForce` to `ArgForce` because AskForConfirm can be used for other actions as well, it's not limited to delete actions so `ArgDeleteForce` name can be inappropriate.
/cc @mauricio
=> consistency changes: ask for confirm added to all delete actions

README.md
@mauricio :100: 
~By the way, maybe you should check, but I think snap is containing 1.5.0 instead of 1.6.0.
This is what I get when I execute find (`snap find doctl`) on my box:~
**It has been updated to 1.6.0 in meanwhile:**
```
Name   Version  Developer  Notes  Summary
doctl  1.6.0    joeborg    -      Digital Ocean command line tool
```
=> docs: improve package manager part in readme

commands/extract.go, commands/util.go
needed both on windows / unix platforms
identified while baking 1.7.0 release.
=> moving extract to its own file

commands/output.go
This PR adds Features list and Volumes list to the Droplet's list output.
Volumes list was there before, but under `isBeta()` flag. As volumes are in beta phase, I removed this and it appeared back in the output.
Fixes #213 
/cc @mauricio @viola
=> commands/output: adds features and volumes to droplet's list output

snap/snapcraft.yaml
Automatically install bash and zsh completions on doctl install via snap.
To be in effect, doctl needs to be re-released with new script.
It's not guaranteed to work, but we will see results once we build doctl with new script. It appears to work for juju, so I hope it will work for us as well.
/cc @mauricio @lxfontes
=> doctl/snap: bash/zsh completions on install

commands/confirmation.go
This PR fixes confirmation behavior on Command Prompt and PowerShell for Windows users.
Currently, confirmation doesn't work for Windows users. If you try command such as:
```
doctl compute droplet delete 1
```
and type `y` or `yes`, you would get `operation aborted` error.
This is because Windows shells use `\r\n` instead `\n` for new line, which makes answer verification to fail.
This PR appears to work on both Linux and Windows, so it should be good to go.
/cc @mauricio
=> confirmation: fix confirmation behavior on windows cmd and powershell

README.md
doctl/docs: fix tutorial link in readme
Tutorial link is showing incorrect due to markdown error. This PR will fix it.
/cc @mauricio @viola
=> doctl/docs: fix tutorial link in readme

README.md
This fixes the link and works no matter where the README file is being displayed.
=> Fix Releases link 404

.dockerignore, Dockerfile.build, Dockerfile.cntr, Makefile
`make` will build local go binary
`make {linux_amd64,linux_386,macos}` will compile for Linux/Mac
`make docker_build` will create a container and copy out Linux and Mac Binaries to `builds`
=> Makefile: enable build via make and create local container

CONTRIBUTING.md, README.md, cmd/install-doctl/main.go
We have been working on updating `doctl` tutorial and this is the first step towards it. This PR improves README. We've corrected installation instructions and added several new things, such as more detailed examples for configuration and shell completions.
Also, this PR closes #167.
The releasing part has been moved to the CONTRIBUTING.md.
/cc @hazel-DO @mauricio @viola @lxfontes
=> Rework README.md to match Community's new tutorial

commands/firewalls_test.go, commands/output.go
Currently "compute firewall list" shows following for a rule using icmp
... protocol:icmp,ports:0,address:0.0.0.0/0,address:::/0 ...
Problem is using this syntax ends up with an error.
```
$ doctl compute firewall create --name test --outbound-rules "protocol:icmp,ports:all,address:0.0.0.0/0,address:::/0"
...
Error: POST https://api.digitalocean.com/v2/firewalls: 422 (request UUID) You must specify a positive value for ports.
```
whereas omitting the port field works as expected.
```
$ doctl compute firewall create --name test --outbound-rules "protocol:icmp,address:0.0.0.0/0,address:::/0"
ID                                      Name    Status     Created At              Inbound Rules    Outbound Rules                                          Droplet IDs    Tags          Pending Changes …
```
=> firewall: omit the port field for the icmp

README.md
@xmudrii and i worked on this README update as a side effect of working on the corresponding doctl community tutorial, and some DO-specific markdown made it into the commit here. naturally it won't render on github. :)
=> removing DO-specific markdown

README.md
The package seems well maintained and some people don't use Snaps for whatever reason.
=> Added Arch AUR Package to README

commands/doit.go, commands/xdg.go
Closes #246 
When `XDG_CONFIG_HOME` path is set, `doctl` creates configuration file directly in that directory instead of creating it in the `doctl` subdirectory.
This PR also adds warning if configuration file is present in the root of the `XDG_CONFIG_HOME` directory.
/cc @mauricio
=> xdg: fix config path when XDG_CONFIG_HOME is set

commands/output.go
`size_slug` is present on json but not present on plain text output.
This adds `Size Slug` as an output column.
However, I have *not* added it to `droplet list` due to the amount of info already being displayed.
Related #291
=> Adds `SizeSlug` to format fields

commands/images.go
This PR addresses the problem reported in #279, #261 and #251.
Currently, commands `doctl compute image list-distribution` and `doctl compute image list-application` don't return any output without `--public` flag.
I believe this should not be the case, as you can't have private distributions or applications.
This confuses user, so I decided to make a PR to fix the problem.
The `doctl compute image list` command still shows only private images. I can update flag's default value for this command as well, if that's needed.
However, there is a problem for existing `doctl` users.
The `doctl auth init` command creates configuration file with all keys set to flag's default values. This means that configuration file still has `false` set on the changed flags. Users have to manually update the …
=> commands: show public images for distros and apps by default

commands/xdg_windows.go
Closes #240.
This is not an elegant solution, so any suggestion is appreciated.
Currently, on Windows, we're using the `XDG_CONFIG_HOME` to get the directory where we should store configuration file. However, that environment is Linux-specific, it doesn't exist on Windows.
We have a code to use the `C:\Users\Username\AppData\Local` directory, but it's not user-friendly, especially for XP users.
The `LOCALAPPDATA` variable contains the path to the `C:\Users\Username\AppData\Local` directory, which we're using to store `doctl` configuration file. But the problem is that it's only available on Vista or newer.
For XP users, we're using the `APPDATA` environment variable.
**This can introduce compatibility problems, as it will use the `Document and Settings` directory now instead of `Users`. …
=> commands: fix configuration file location for windows xp users

args.go, commands/auth.go, commands/auth_test.go, commands/commands_test.go, commands/doit.go, doit.go
Related issue: #266 
This is a proposed implementation of support for multiple accounts. The idea behind this is each account is associated with a context, which contains the API access key.
A new global option is added: `context`. It defaults to `default`, and should contain the name of the DO account that will be used.
If it is set to `default`, all existing auth functionality is preserved (using `--access-token` or the corresponding environment variable). This makes this feature backwards-compatible.
To configure a "named" account called, say, `foo`, run `doctl auth init --context foo`. This will prompt the user for the API key and save it in the config file. Whenever `--context foo` is passed to any other command, that API key will be used.
[This …
=> Implement context switching, allowing for multiple configured API access keys

commands/firewalls.go
This PR adds the `displayerType` attribute for the relevant `firewall` commands, ensuring they have the `--no-header` and `--format` flags. Those flags can be used to format output, which helps if you want to automate some processes.
=> cmd: add --no-header and --format flags for firewall list command

commands/firewalls.go
Currently, to delete multiple firewalls, you need to execute several commands to delete them, as one command can delete only one firewall. This PR allows users to delete multiple firewalls using single `firewall delete` command, like they can do for Droplets.
With #303 merged, users can also delete all firewalls in the same time by chaining `delete` and `list` commands, e.g. `doctl compute firewall delete -f $(doctl compute firewall list --no-header --format ID)`.
=> cmd: allow multiple firewalls to be deleted in same time

commands/droplet_actions.go, commands/droplet_actions_test.go, do/droplet_actions.go, do/mocks/DropletActionsService.go
Hi, the upgrade droplet action is no longer supported by the v2 API. (See the [droplet-actions endpoint in the docs](https://developers.digitalocean.com/documentation/v2/#droplet-actions))
Running `doctl compute droplet-action upgrade <droplet-id>` results in:
```
Error: POST https://api.digitalocean.com/v2/droplets/<droplet-id>/actions: 410 The specified action type is no longer available.
```
This PR removes the `upgrade` subcommand from `droplet-action` as well as associated tests and mocks.
Let me know if it looks good or if there's anything else I need to do.
=> Remove upgrade command from droplet-action

commands/droplet_actions.go, commands/droplet_actions_test.go
Adds the [`enable-backups`](https://developers.digitalocean.com/documentation/v2/#enable-backups) droplet action which wasn't implemented in the CLI.
=> Add the enable-backups droplet action

commands/output.go
This PR fixes #320.
The column name should contain no spaces, or otherwise, when provided to the `format` flag, it would cause error (as described in #320).
/cc @mauricio
=> commands: fix volume dropletids column name

doit.go
Update the version string to show `1.8.3-dev` instead of `1.7.2`, as `1.8.3` is the latest version.
Closes #329
=> Update version string to 1.8.3-dev

README.md
The latest release of `doctl` is 1.8.3 (as of now) - https://github.com/digitalocean/doctl/releases/tag/v1.8.3.
Updated installation instructions in the README.
=> Bumped version to 1.8.3 in the README

CHANGELOG.md, Dockerfile, README.md, commands/projects.go, doit.go, snap/snapcraft.yaml
Projects API is no longer in beta. See #353 for details on projects commands, and https://developers.digitalocean.com/documentation/v2/#projects for documentation.
=> projects API GA

commands/commands_test.go, commands/displayers/kubernetes.go, commands/kubernetes.go, commands/kubernetes_test.go, do/mocks/KubernetesService.go
Doing this iTDD style.
- generate the mocks for testing calls to the k8s service
- extract the error into funcs for consistency and easier testing
- extract the sub commands into funcs for testing
- fix reference-on-range bugs
- fix missing `--force` check on `node-pool delete`
- check that all the "by name" helpers work
r: @nanzhong @bouk @fatih
=> k8saas: add tests and fix bugs

CHANGELOG.md, commands/domains.go
Previously, the API required that you provide an IP address when
creating a new domain in order to create an initial A record. This
behavior was changed to be optional:
https://developers.digitalocean.com/documentation/changelog/api-v2/create-domains-without-providing-an-ip-address/
=> No longer require ip-address when creating domains (Fixes: #366).

Gopkg.lock, Gopkg.toml, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/kubernetes_test.go
This reverts commit b127df1949d40b8869b102c6ef2606d7b0c76de4, reversing
changes made to 0d9d1b8409d109d03fbd439f649d47a0bada04ec.
This unbumps godo, while we revisit the `/v2/kubernetes/options` endpoint.
=> Revert "Merge pull request #374 from digitalocean/bump-godo"

commands/displayers/volume.go
Due to a missing space in the droplet ID column name, the `Droplet IDs` column in the output of `doctl compute volumes ls` was always showing `<nil>`, even for attached volumes.
Add the necessary space so that droplet IDs display again.
=> volumes: Fix droplet ID display when listing volumes

README.md, snap/snapcraft.yaml
This fixes the `permission denied` errors mentioned in #263 and #347
=> Change snap to classic confinement

CHANGELOG.md, args.go, commands/kubernetes.go
The default node size slug baked in the binary isn't valid for Kubernetes clusters. Fix that, and improve the help strings a bit while at it.
=> k8s: default to usable settings

commands/droplets.go, commands/droplets_test.go
The functionality was already implemented in `RunDropletDelete` but never exposed. With this change, we allow deletion of droplets by tag name through the CLI.
Ideally, I'd also like to add a test case. However, from a quick glance at `droplet_test.go` I cannot easily see how to do that -- the existing tests (like `TestDropletDeleteByTag`) seems to attach the tag name argument separately from the `Droplet()` function. It looks like we should be testing things differently to actually run through the system-under-test, though chances are I might be missing something. Pointers welcome. :)
=> Expose 'tag-name' argument to the RunDropletDelete command.

commands/auth.go, commands/doit.go, commands/domains.go, commands/floating_ips.go, commands/kubernetes.go, commands/kubernetes_test.go, commands/load_balancers.go, commands/projects.go, commands/sshkeys.go, commands/volume_actions.go, commands/xdg.go
Consists of naming style alignments, code simplifications, and trailing punctuation-free error messages.
=> Fix linter violations.

commands/projects.go
Fairly simple typo fix - "project" was repeated twice in the usage for `doctl projects resources --help` so I removed the extra copy.
=> Fix typo in project resources command

commands/kubernetes.go
We currently try to fetch the credentials before the cluster is provisioned, which can lead to a 404 if the credentials aren't ready yet. This changes the order of operations so that the credentials are fetched after the cluster is done provisioning.
Fixes #399
=> kubernetes: Fetch credentials after cluster is provisioned

CHANGELOG.md, commands/kubernetes.go, commands/kubernetes_test.go
We've seen this issue:
```
$ doctl kubernetes cluster create node-readiness-debug --node-pool name=node-pool-node-readiness-debug1;size=s-2vcpu-4gb;count=1 --region lon1
Notice: cluster created, fetching credentials
Notice: adding cluster credentials to kubeconfig file found in "/Users/treimann/.kube/config"
Notice: cluster is provisioning, waiting for cluster to be running
....................
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1674bc7]
goroutine 1 [running]:
github.com/digitalocean/doctl/commands.waitForClusterRunning(0x18f7640, 0xc000532340, 0xc0005c4330, 0x24, 0x0, 0x0, 0x0)
/private/tmp/doctl-20190125-78561-1oqpqh5/doctl-1.13.0/src/github.com/digitalocean/doctl/commands/kubernetes.go:10 …
```
=> kubernetes: Fix case where kube.Get returns a nil cluster

commands/displayers/certificate.go, commands/displayers/kubernetes.go, commands/displayers/load_balancer.go, commands/displayers/output.go, commands/droplets.go, commands/kubernetes.go, commands/kubernetes_test.go, doit.go, pkg/ssh/ssh_internal.go, pkg/system/chtimes.go, pkg/system/utimes_unix_test.go
i) govet - unkeyed fields
ii) golint - redundant err !-nil checks
iii) staticcheck - improper use of printf-style statements when there are no arguments used.
iv) removed use of oauth.NoContext which is deprecated.
v) run gofmt -s -w
=> Fix multiple linting issues in doctl

Makefile
The Makefile would set the `darwin` target on an unused variable (`NATIVE`) instead of `GOOS`.
=> Makefile: fix Mac native build.

CHANGELOG.md, Dockerfile, README.md, doit.go, snap/snapcraft.yaml
This updates the doctl `version` to `1.15.0` and updates the CHANGELOG to include the addition of Managed Databases.
cc: @hilary
=> bump version and update changelog for databases support

commands/commands_test.go
I forgot to add the database mock assertions in `commands_test` for my databases update. This adds those assertions in.
=> add mock assertions for databases service

args.go, commands/kubernetes.go, commands/kubernetes_test.go
`buildClusterCreateRequestFromArgs` and `buildClusterUpdateRequestFromArgs` incorrectly references the `--tag` field (`doctl.ArgClusterTag`) by (`doctl.ArgTagName` `--tag-name`). The test unfortunately also referenced `doctl.ArgTagName` so this went unnoticed.  Correct this handling, and move to `doctl.ArgTag` which will be shared by volume and snapshot creation.
=> fix --tag for kubernetes create/update

Gopkg.lock, args.go, commands/displayers/snapshot.go, commands/displayers/volume.go, commands/volumes.go, commands/volumes_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/kubernetes_test.go, vendor/github.com/digitalocean/godo/snapshots.go, vendor/github.com/digitalocean/godo/snapshots_test.go, vendor/github.com/digitalocean/godo/storage.go, vendor/github.com/digitalocean/godo/storage_test.go, vendor/github.com/digitalocean/godo/tags.go
Contains two commits.
- Update godo vendor to v1.13.0.
- Add tag support for volumes and volume snapshots.
=> Godo v1.13.0 + Tag Support for Volumes + Vol Snapshots

commands/auth.go
This makes use of the [`ReadPassword` function in `golang.org/x/crypto/ssh/terminal`](https://godoc.org/golang.org/x/crypto/ssh/terminal#ReadPassword) to avoid forcing the user to expose their auth token when entering it on the command line in response to the `doctl auth init` prompt.
This does not yet address the issue of printing the auth token when running `doctl auth init` when one is already configured. I think I will file an issue to initiate discussion as to whether or not displaying the auth token is even a concern (I am accustomed to services like Github which more tightly control visibility of auth tokens).
=> Disable terminal ECHO flag when prompting for auth token

CHANGELOG.md, commands/databases.go
This PR removes the need to opt-in to database commands by setting the `DIGITALOCEAN_ENABLE_BETA` environment variable.
=> Remove beta opt-in from database commands.

CHANGELOG.md, args.go, commands/displayers/volume.go, commands/volumes.go, commands/volumes_test.go
Adds a `--snapshot` flag to the `doctl compute volume create` command, allowing users to create a new volume from an existing volume snapshot.
If merged, this should fix #420.
I wasn't exactly sure how to handle the `--region` flag. In `doctl` it's currently marked as required, but in the [API documentation](https://developers.digitalocean.com/documentation/v2/#create-a-new-block-storage-volume), it's stated that, 
> "The region [...] should not be specified with a snapshot_id".
My initial approach was to remove the `requiredOpt()` argument from the region flag, and update the usage string to indicate that either a region or snapshot must be included.
This is where trouble began.
I suspect there's some issue when using a non-required flag that is already registered as a required flag on a …
=> Create a volume from a volume snapshot

README.md
Users have been running into issues by installing an old version of doctl via Snap. This PR comments out the instructions until a time when we can get the snap updated.
=> Remove snap from README

args.go, commands/kubernetes.go, commands/kubernetes_test.go
Create:
```
doctl kubernetes cluster create foo --maintenance-window monday=00:00
```
Update:
```
doctl kubernetes cluster update foo --maintenance-window any=12:00
```
There is no deletion of a maintenance policy as it's not needed.
Depends on https://github.com/digitalocean/godo/pull/224
=> kubernetes: add maintenance policy flags

Gopkg.lock, Gopkg.toml, args.go, commands/displayers/kubernetes.go, commands/kubernetes.go, commands/kubernetes_test.go, do/kubernetes.go, do/mocks/KubernetesService.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/firewalls.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/kubernetes_test.go, vendor/github.com/digitalocean/godo/projects.go
Add three pieces of functionality to support upgrading Kubernetes clusters:
1. Allow clusters to be created with auto-upgrade enabled, or have auto-upgrade enabled via `doctl k8s cluster update`. Show the auto-upgrade setting when getting or listing clusters.
2. Allow fetching available upgrade versions with `doctl k8s cluster get-upgrades`.
3. Allow for immediate upgrade of a cluster with `doctl k8s cluster upgrade`, which optionally takes a version. By default the latest available upgrade version will be used.
=> kubernetes: Support cluster upgrades

CHANGELOG.md, args.go, commands/kubernetes.go
This PR adds a new flag of `--set-current-context` when creating or updating a cluster, or saving a KubeConfig, that will set the `current-context` of your local KubeConfig to the new cluster. It defaults to true as this should be the expected behavior.
edit: Closes #394
=> Add flag to set current-context in local KubeConfig

commands/completion.go
Currently the command is set as `Hidden` so it is not shown in the help/usage text. This PR removes the `Hidden` setting and manually deletes it from the resulting autocompletion code.
=> Unhide the command "completion" + prevent it from being autocompleted

commands/certificates.go, commands/commands_test.go, commands/databases.go, commands/kubernetes.go, commands/load_balancers.go, commands/projects.go, commands/tags.go
This PR first adds a test ensuring that we consistently accept the `--format` flag for all `get` and `list` commands.  The following commits then fix the the failing tests by adding `--format` support to certificates, databases, kubernetes, load balancers (#340), projects, and tags respectively.
=> Ensure all 'get' and 'list' commands support the 'format' flag.

.gitignore, README.md, commands/kubernetes.go, doit.go, snap/local/doctl-launch, snap/snapcraft.yaml
Fixes #457 (and #451, which is closely related) using snap's `personal-files` interface and a, well, hack. (Injecting knowledge about a packager into our CLI qualifies as a hack to me, but that's me. And the benefit of having strict confinement for our devs is substantial.) 
At present, using the snap version requires a bit of setup.  After installing the snap, connect the config plugs:
```bash
sudo snap connect doctl:doctl-config
sudo snap connect doctl:kubectl-config
```
The setup only has to be done once; upgrading and/or removing and reinstalling the snap does not remove the connections.
We can submit a request for each of the `personal-files` plugs to [auto-connect](https://forum.snapcraft.io/t/process-for-aliases-auto-connections-and-tracks/455). See, for example, …
=> Work with kubectl

README.md
Running the `doctl` container with `--interactive --tty` will work if `doctl` commands issue `Are you sure?` prompts.
Consistent use of --long-flag-names to help users understand the intent of the Docker commands.
=> Support "Are you sure?" prompting

commands/completion.go
This PR allows the completion of aliases of commands in zsh.
For example:
`doctl k8s <tab>` will now properly complete as if the command was typed as `doctl kubernetes <tab>`
Ref:
https://github.com/helm/helm/pull/5680
https://github.com/helm/helm/commit/48f0e3101d49a3de1466ff75fc786ce012f369cc
=> Allow completion of aliases in zsh

scripts/release.sh, snap/snapcraft.yaml
`git fetch`, `git pull`, etc, do not update tags. It has to be
done explicitly.
=> ensure tags are up to date before using

commands/commands_test.go, commands/displayers/output.go, commands/displayers/output_test.go, commands/ssh_test.go, doit.go
Fixes #479 (and a few other similar cases when I tested manually).
According to Go's JSON marshalling logic, a nil slice is rendered as `null` in JSON. Due to some of the filtering we do on the returned API results, there are cases where we send a pointer to a struct containing only a nil slice to the displaying logic. This ends up being rendered as `null`. To correct this, I've added a check to the JSON displaying logic for any `Displayable` type that writes `[]` instead of `null` for this particular case.
In order to write a test for this, I decided to move the TestConfig from the doctl_test package to the doctl package. This let me import it in the commands_test package to reuse it, and should encourage further reuse.
=> Write JSON for nil slices as [] instead of null

CONTRIBUTING.md, Makefile
Edited `CONTRIBUTING` for clarity and flow.
=> Makefile improvements

scripts/stage.sh
This fixes the regression introduced in: https://github.com/digitalocean/doctl/commit/6e988dfadee614295cd2ec979d658794bb32d847
The LDFLAGS are necessary for setting the correct version and labels at build time when cutting a new release.
=> Re-add the logic setting LDFLAGS in scripts/stage.sh (Fixes: #496).

commands/doit.go, commands/kubernetes.go, commands/kubernetes_test.go
Fixes #459
Background: When an operation via doctl is invoked that writes to the user's kubectl config (for example, `doctl kubernetes cluster kubeconfig`), the `--context` flag is used by doctl, but **not** kubectl.
This problematic, because we use a command called `exec-credential` that grabs certificates on the fly from DO Kubernetes. This `exec-credential` call is invoked by kubectl, so if kubectl is not aware of the value of the `--context` flag passed by the user during the kubeconfig command, then `exec-credential` will not use that context either, causing the kubectl command to fail unexpectedly.
This change updates the `mergeKubeconfig` function responsible for updates to the kubectl config to always pass a `--context` flag. If there is no context set, it uses the default …
=> Ensure kubeconfig exec is context-aware

CONTRIBUTING.md, Makefile
Because just having the names is better than nothing, but not much.
=> add descriptions to `make help`

args.go, commands/databases.go, commands/databases_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/tags.go, vendor/github.com/spf13/afero/go.sum, vendor/modules.txt
This adds the `private-network-uuid` field to Database creates, migrates and replica creates so that users can use `doctl` to move/create their Databases inside of their private networks/VPCs.
cc: @hilary @mikejholly
=> dbaas: add private-network-uuid to create, migrate, and replica create

CONTRIBUTING.md, Makefile, scripts/build.sh, scripts/deploydocs.sh, scripts/regenmocks.sh, scripts/shell_check.sh, scripts/stage.sh, scripts/upload.sh, scripts/version.sh
And do a bunch of cleanup 🙄 
https://github.com/koalaman/shellcheck
=> adopt shellcheck

snap/snapcraft.yaml
https://forum.snapcraft.io/t/personal-files-request-for-doctl-was-classic-confinement-request-doctl/11785/26
I posted my deep dive into the issue with `.kube/config` to the snap
forums five days ago. In that post I described a work-around for the
configuration file. We've been engaging with Canonical about
kube-config for six weeks now. Let's go ahead and see whether the
work-around works in production, or whether we can only include the
lines we were given in the thread in our interface definition.
=> try proposed work-around for snap in production

scripts/stage.sh
Before this change, the basename would always be generated to contain the string `.exe`. This fixes the script in a shellcheck-compliant way so that we're back to the old behaviour.
It also fixes the error introduced by the `u` flag in `set -euo pipefail` when the script is invoked without a `label` or set `SKIPBUILD` so that those fall back to an empty default value.
=> Fix distfile basename in staging script

scripts/stage.sh
Back when we were still using `xgo` for cross-compilation, all Windows binaries has the `.exe` suffix. Turns out that was something `xgo` was doing for us, so this PR adds that behaviour to our current manual cross compilation script.
Fixes #509
=> Add .exe suffix to Windows binary filenames

README.md, snap/snapcraft.yaml
tested by:
- building snap
- uploading manually (using snapcraft push) to candidate channel
- install from candidate channel
- use `doctl k8s cluster kubeconfig save ...`
shows that the snap does not work unless .kube/config.lock is included
in snap/snapcraft.yml
=> explicitly include .kube/config.lock in snapcraft.yml

CONTRIBUTING.md, Makefile, scripts/snap.sh
The automated build/release pipeline provided by snapcraft is both fragile and opaque. Rather than continue to wrestle with it given that our snap is rather advanced, I dockerized the build.
=> add `make snap`

snap/snapcraft.yaml
also updated how the version is set because `version-script` has been deprecated
=> set ldflags in snap build

commands/confirmation.go, commands/confirmation_test.go
a small bit bit of cleanup in passing
both of these helpers are only used in the test file, so I moved them to the test file. Notice, however, that, by moving them to the test, I removed four imports from the production module!
Don't prematurely generalize...
=> move test helpers to test

commands/confirmation.go, commands/confirmation_test.go
Reverts digitalocean/doctl#542, as as master currently won’t build due to `retrieveUserInput` not being defined in `AskForConfirm` in commands/confirmation.go. The test suite doesn't report this as a failure, as that function _is_ defined in commands/confirmation_test.go. Might be worth adding a `go build` command to our CI to catch things like this in the future, although I can't imagine they'd be too common.
=> Revert "move test helpers to test"

commands/volume_actions.go, commands/volume_actions_test.go
Fixes #543
Adds support for the wait flag on all volume-action commands. Since each command ends up calling `performVolumeAction` which supports the `--wait` flag, this fix was just a matter of defining that flag on each command.
=> Support --wait flag on volume-action commands

commands/doit.go, commands/errors.go, errors.go
in time we'll leverage cobra's innate usage statement management, but for now let's just stop obscuring the actual error message
=> disable usage statement on error

integration/init_test.go
- was just dumping a text string when we probably should see both stderr and stdout instead.
=> should get command output when it fails

scripts/build.sh
we should deprecate this at some point and remove it, but it's not doing any harm at this point.
=> refactor old scripts/build.sh to use make native

CONTRIBUTING.md
Adds a note to mention the `ORIGIN` environment variable that can be used to control which remote repo we release to. Given that the recommended setup for our team is to work on one of our own forks, it makes sense that some of us have `origin` set to that fork, so this note should clarify that we can release to something like `upstream` via `ORIGIN=upstream make bump_and_release`, for example.
---
@hilary Feel free to decline this if you think it adds too much verbosity to the doc. Just figured I'd raise this since I was pretty surprised when I realized halfway through a release that I was releasing to my own fork 😄
=> Add note about ORIGIN env var for releases

commands/auth.go, commands/auth_test.go
Closes #556
Adds a basic command to list all auth contexts by reading from the user's doctl config file. The current auth context is shown with the word `(current)` next to it.
Testing this truly effectively is impossible due to our global Viper instance. I could create some kind of function to retrieve the config data, but that feels like creating too much of a mess just to make this testable, and sidesteps the actual problem of global Viper.
That said, I've added a relatively exhaustive test to the displaying logic, which I think is the most important part, so I feel like this is adequately covered.
=> Add command to list auth contexts

commands/databases.go
The API itself will default to a sane version for the specified database engine. By using a hard-coded default of 11, attempts to create MySQL or Redis clusters without explicitly specifying the version will fail. Eg:
```
$ doctl databases create --engine mysql doctl-mysql
Error: POST https://api.digitalocean.com/v2/databases: 422 (request "a11fa359-5778-42a5-8474-d776c5c097fd") invalid cluster engine version
```
=> DBaaS: Remove hardcoded default version for creates.

.travis.yml
As feature work is done in forks, we should only be notified when master is red (or, I suppose, when someone does feature development in a branch and has failing tests, but then we can discuss that with them...)
=> notify slack when master goes red

scripts/_build.sh
Fix error like below when invoking `make native` to build doctl executable:
```
$ make native
=> building doctl via go build
scripts/_build.sh: line 6: DIR: unbound variable
make: *** [Makefile:43: _build] Error 1
```
=> Make sure setting variable `DIR` before called on scripts/_build.sh

commands/auth.go
Fixes #573
On Unix, the file descriptor for stdin is 0. On Windows, this isn't the case, so we need to use `syscall.Stdin` to get the correct file descriptor in order to use `terminal.ReadPassword`, as noted in this Go issue: https://github.com/golang/go/issues/11914.
=> Don't assume the fd for stdin is 0

.travis.yml
- restrict candidate snap to push to master
- restrict stable snap, release to pushing new tag, which travis only
identifies by `deploy: on: tags: true`, not by branch conditions
Unfortunately, none of this is clearly documented in travis.
=> fix travis deploy conditions

commands/kubernetes.go, commands/kubernetes_test.go
Currently when trying to create a Kubernetes cluster node pool with `--count=0`, we hit this error:
```shell
$ doctl k c np create blue --count=0 --auto-scale=true --min-nodes=1 --max-nodes=2 --size=s-1vcpu-2gb --name=blue-2
Error: (node-pool.create.count) command is missing required arguments
```
This PR fixes that.
=> DOKS: support creating empty node pool

commands/projects.go, commands/projects_test.go, errors.go, errors_test.go
- This error type was exracted but only being used
in one place. Condensing means we have one less
extracted piece of code to go find / maintain
later (especially when its not shared).
- I've also gone and ahead and implemented what
seems to be the errors original intent, show the
malformed URN with your error (this was not implemented)
=> remove extracted error and make more informative

integration/init_test.go
Not really a huge deal if it fails as `OS` will remove temp dir at restart anyway.
=> os.RemoveAll on temp dir is best effort

integration/auth_test.go, integration/init_test.go
Now that we have this config this test is potentially destructive to a users config, if they run the test locally. We've tried to mitigate this in the test setup / teardown by having it copy / re save the config that was originally there (if it exists).
- missing integration test was added to make sure we don't accidentally reconfigure the spot our config file is stored in.
- formatting changed here because it was not `go fmt` correctly (still wouldn't pass golint but that's another PR)
=> adds default config integration test

commands/doit.go, doit.go
Co-Authored-By: Zachary Gershman <zachgersh@gmail.com>
In addition to running clean on the tests, we tried out the code
with:
- doctl auth init
- doctl compute droplet list
- doctl k8s cluster list
- doctl k8s cluster kubeconfig save
and a few others. (The k8s commands are particularly of interest as
there are interactions between the doctl config and kubeconfig.)
We tried the above command with command line options and using the
values from the doctl config file.
=> nuke NSRoot from space!

integration/droplet_delete_test.go, integration/init_test.go
where `server.URL` is may look weird in the test. Why is it there? It's due to the fact that the `Before` is not evaluated until right before the `it`. If we had it back up in `base` it results in a `nil` dereference due to the fact that the Before has not yet run.
=> adds droplet delete test

do/droplets.go, integration/droplet_neighbors_test.go, integration/init_test.go
- there is also a fix here for a bug that we had
in the neighbors code (arrays + pointers are
always tricky).
- don't actually think we should be using droplet pointers in any of our returns from droplets.go but I didn't want to make that large of a change without adding more tests first.
=> adds droplet neighbors test

commands/command_config.go, commands/doit.go, doit.go
this PR includes several small commits, each with a small, focused refactor:
* streamlining the global viper getters/setters (which will eventually go away, but at least we can have them readable in the meantime)
* inlining requiredKey, more of that viper
* removing the global effect beta system (later we'll add the ability to make a command beta, which will hide it in help unless that specific beta command is enabled)
=> cleanup betacmd and more

.travis.yml, scripts/release_travis.sh
github-changelog-generator behaves a bit differently on travis than it does locally. It appears to need a GITHUB_TOKEN to authenticate. Also, the bump to go 1.13 changed the way GO111MODULE worked.
=> fix use of github-changelog-generator on travis

integration/droplet_get_test.go
if we break config parsing in some way (since the token the only thing that is stored there) this test should start to 401.
=> guards against token parsing from config regression

commands/images.go, commands/images_test.go, integration/image_create_test.go
Updates the new command to create custom images to turn the `--image-name` flag into a positional argument, and adds a default to the image distribution flag.
This is small follow-up to the excellent work done by @VictorAvelar 🎉
=> Make image name positional and add default image

commands/cdns.go, commands/kubernetes.go, commands/projects.go, doit.go
- IsSet behaved differently between live and test
- namespacing was done differently between live and test
- alone of all the config methods, IsSet was not namespaced,
and therefore had different semantics from the other
methods in that it did not reference viper
=> consolidate live and test flag semantics

integration/account_test.go, integration/auth_test.go, integration/auth_windows_test.go, integration/droplet_actions_test.go, integration/droplet_backups_test.go, integration/droplet_create_test.go, integration/droplet_delete_test.go, integration/droplet_get_test.go, integration/droplet_kernels_test.go, integration/droplet_list_test.go, integration/droplet_neighbors_test.go, integration/droplet_snapshots_test.go, integration/droplet_tag_test.go, integration/image_create_test.go, integration/init_test.go, integration/region_list_test.go, integration/size_list_test.go
- this is normally how go test works and removing
suite registration makes this appear more go
test like while still keeping the functionality
we like about spec
=> register your test at the top of the file

integration/account_test.go, integration/auth_test.go, integration/auth_windows_test.go, integration/databases_create_test.go, integration/droplet_actions_test.go, integration/droplet_backups_test.go, integration/droplet_create_test.go, integration/droplet_delete_test.go, integration/droplet_get_test.go, integration/droplet_kernels_test.go, integration/droplet_list_test.go, integration/droplet_neighbors_test.go, integration/droplet_snapshots_test.go, integration/droplet_tag_test.go, integration/image_create_test.go, integration/init_test.go, integration/region_list_test.go, integration/size_list_test.go
with the last merge we were in a spot where the tests were organized better (people couldn't forget to declare their suite) but each new test was a new suite (which made the reporter look weird when running in verbose mode).
This keeps the original ease of declaring a test as part of the suite but also fixes the reporter so all tests appear as part of the same suite (accurate test counts and such).
=> tests organized the same but now all appear as one suite

integration/kubernetes_clusters_create_test.go, integration/projects_resources_test.go
this is a bit of a bear only because it will actually make a kube config AND it relies on us returning a properly formatted (though fake) kubeconfig from the server.
test does work and is exercising a majority of the kube related functionality on create.
=> adds test for kubernetes create

Makefile, integration/projects_list_test.go
- set integration tests to run in verbose mode since
we'd like to see test pass/fail/skip counts anyway.
=> removes mistakenly added focus

integration/firewall_create_test.go, integration/firewall_get_test.go, integration/firewall_list_test.go, integration/firewall_update_test.go
Adds the integration tests for firewall CRUD operations. Next up are all the commands affecting a firewall's Droplets, tags, and inbound/outbound rules.
=> Add integration tests for firewall CRUD operations

integration/compute_floating_ip_action_test.go
- We've got an inconsistency here on our get action. All other gets are taking the flag `action-id` this one has instead chosen to pass the `action-id` as another positional argument.
=> compute floating-ip-action: adds all tests

integration/compute_volume_action_test.go
- this also has a bit of a problem (there is a deprecated command here that we should probably remove)
=> compute volume-action: adds all related tests

commands/kubernetes.go, commands/kubernetes_test.go
Cluster names that happened to be 32 characters were [getting treated as UUIDs](https://github.com/google/uuid/blob/16ca3eab7d2086fd5a82993a291cbf3b87fe38b7/uuid.go#L60-L61) which causes issue #461. 
Based on [The tests](https://github.com/digitalocean/doctl/blob/d055080faf145deac6ce9df725c8b27e1a2432fc/commands/kubernetes_test.go#L19), I'm hypothesizing that the DO api is assuming UUID's to always be represented in the hyphenated form (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
This PR updates the `looksLikeUUID()` function to use a strict regex match rather than `uuid.Parse()`'s more lenient checking, which should address the issue in #461 .
=> Updated looksLikeUUID to only match hyphenated UUIDs (Fixes #461)

commands/domains.go, commands/domains_test.go, do/domains.go, do/mocks/DomainService.go, integration/domain_records_create_test.go
Updates the create and edit domain records commands to send a value of zero when the port is set to zero via a flag, and to not send it otherwise.
This required both of these commands not to use `godo`, in order to save us from having to make a breaking change in `godo` to update the port field to be a int pointer instead of just an int.
In the future, this commit should be reverted once we're able to release a v2 of `godo` that addresses this issue properly.
If merged, we should close https://github.com/digitalocean/godo/pull/269.
=> Accept a port of zero for SRV records

integration/domain_records_create_test.go
Removes the focus call from integration tests so that they run again.
=> Remove focus call from integration tests

scripts/snap_image.sh
Updates the instructions for building a new snap image to include the bit where you have to tag the name, because just a name or ID isn't enough.
=> Update instructions for updating snap image

integration/auth_test.go
Adds an integration test for `DIGITALOCEAN_CONTEXT`, an environment variable used to set the name of the current context for a command. This is essentially what the `--context` flag already does.
=> Add integration test for DIGITALOCEAN_CONTEXT

doit.go, doit_test.go
Adds the OS info to the user agent string that we set on our `godo` client. The OS info is pulled from the runtime's `GOOS` and `GOARCH` variables. The new user agent string will now look like,
```
doctl/1.22.3 (darwin amd64)
```
or
```
doctl/0.0.0-dev (windows 386)
```
---
If the regex in the test is too much, I can remove it.
=> Add OS info to user agent string

commands/kubernetes.go
- we now make sure to print notices for adding
snap permissions AND creating the .kube dir that
we do not have permissions to.
closes #481
=> kubernetes: adds errors for snap permissions

commands/plugin.go
we are going to remove this functionality in a future release of doctl, for now it is just hidden.
=> plugin: deprecate and hide from compute menu

commands/kubernetes.go, commands/kubernetes_test.go
This change adds support for deleting multiple Kubernetes clusters in a single doctl invocation.
Having the frequent need to spin up and subsequently tear down multiple clusters, I find this addition convenient. Additionally, it aligns us closer with some of the other APIs that also support operating on multiple objects at once.
=> Support deleting multiple Kubernetes clusters

commands/kubernetes.go
The flag was read as a string, which did not allow for multiple values to be aggregated and submitted together. Instead, the last `--tag` value would be used only.
Changing to `AddStringSliceFlag` fixes the problem.
=> Fix repetitive usage of --tag flag for Kubernetes node pools

args.go, commands/displayers/kubernetes.go, commands/doit.go, commands/kubernetes.go, commands/kubernetes_test.go, doit.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/.whitesource, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/registry.go, vendor/modules.txt
~The PR depends on the latest (yet unreleased) master version of godo to set labels on Kubernetes requests. **It is only meant to allow the PR to be shared and gather early feedback; the dependency will be reverted to the next godo release once it is out (and block merging until that has happend).**~ (godo has been released and this PR updated accordingly.)
=> Support kubernetes node pool labels

commands/databases.go, commands/domains.go, commands/droplets.go, commands/image_actions.go, commands/kubernetes.go, commands/load_balancers.go, commands/projects.go, commands/regions.go, commands/sizes.go, commands/snapshots.go, commands/volume_actions.go
There's no need to use backticks for single line strings. It creates some unnecessary complications.
=> Clean up overzealous use of backticks for strings.

commands/account.go, commands/actions.go, commands/balance.go, commands/cdns.go, commands/certificates.go, commands/command.go, commands/databases.go, commands/domains.go, commands/droplet_actions.go, commands/droplets.go, commands/firewalls.go, commands/floating_ip_actions.go, commands/floating_ips.go, commands/image_actions.go, commands/images.go, commands/invoices.go, commands/kubernetes.go, commands/load_balancers.go, commands/plugin.go, commands/projects.go, commands/regions.go, commands/registry.go, commands/sizes.go, commands/snapshots.go, commands/ssh.go, commands/sshkeys.go, commands/tags.go, commands/volume_actions.go, commands/volumes.go
As the comment for `CmdBuilderWithDocs` states, it was introduced to transition away from the current `CmdBuilder` implementation incrementally. The original `CmdBuilder` took one description argument and passed it on to Cobra as both the long description and the short description. Now that all commands are using `CmdBuilderWithDocs`, we can get rid of one of the two separate implementations. This PR:
* Adds a second description argument to the few commands (mostly deprecated ones) left that didn't already have them.
* It gives renames `CmdBuilderWithDocs` to `CmdBuilder` and removes old implementation of the latter.
* Replace all usage of `CmdBuilderWithDocs` with `CmdBuilder`.
=> Replace CmdBuilderWithDocs with new CmdBuilder.

commands/auth.go
Before:
```
$ doctl auth init
DigitalOcean access token: 
```
After:
```
$ doctl auth init
Please authenticate doctl for use with your DigitalOcean account. You can generate a token in the control panel at https://cloud.digitalocean.com/account/api/token
Enter your access token:
```
=> auth init: print instructions on how to generate a token

Makefile, dockerfiles/Dockerfile.snap, scripts/snap_image.sh, scripts/version.sh
There are two aspects two this PR, improving the workflow for maintaining the snap image, and fixing the `Dockerfile.snap`. In the end, I decided to leave them in a single PR, in several commits, because I think that provides a better history.
Ultimately, I had to adopt Docker's recommended practice for apt-get usage in RUN statements in a Dockerfile in order to stabilize the build. Nifty!
=> Update snap image, improve snap image workflow

args.go, commands/load_balancers.go, go.mod, go.sum, integration/lb_create_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/README.md, vendor/github.com/digitalocean/godo/billing_history.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
`enable-proxy-protocol` is/has been GA, but seems like it just wasn't bubbled up to `doctl` from `godo` previously. 
`enable-backend-keepalive` is a new feature, currently in beta.
This also bumps `godo` to v1.33.0.
=> load-balancers: add enable-proxy-protocol and enable-backend-keepalive flags

README.md
Adds the `doctl` mascot. I've updated the README to display the `doctl` project name, the badges, and the mascot so that they're centred. I copied the formatting used by React Native's README, so that we're using a formatting approach that is reliable.
I've saved the mascot in our team's shared Space with the CDN enabled, so that we don't need to unnecessarily increase `doctl`'s total file size with an image.
=> Add the doctl mascot

.travis.yml, CONTRIBUTING.md, Dockerfile.build, dockerfiles/Dockerfile.snap, go.mod, vendor/modules.txt
Upgrades doctl, as well as our build infrastructure, to Go 1.14.
You might notice that the `vendor/modules.txt` file looks strange. In Go 1.14, the release notes state the following:
> When -mod=vendor is set (explicitly or by default), the go command now verifies that the main module's vendor/modules.txt file is consistent with its go.mod file.
Our `vendor/modules.txt` file was out of date, so I had to update it with `go mod vendor`. As a result of that, the `go.mod` file was changed, hence the new (and weird looking) comments in there.
I've also verified that the new Docker image and Snap base exist.
---
Finally, it looks like my editor removed some extra whitespace on save.
=> Upgrade doctl to Go 1.14

CONTRIBUTING.md, Makefile, do/mocks/BillingHistoryService.go
Adds a Make target for upgrading `godo`. This also updates the CONTRIBUTING.md doc to use this new Make target. I also ran this target as a test, and it looks like it upgraded the BillingHistoryService's mocks, so that change is included here too.
=> Add Make target for godo upgrade

Makefile, commands/cdns.go, commands/certificates.go, commands/confirmation.go, commands/databases.go, commands/domains.go, commands/droplets.go, commands/firewalls.go, commands/floating_ips.go, commands/images.go, commands/kubernetes.go, commands/load_balancers.go, commands/projects.go, commands/snapshots.go, commands/sshkeys.go, commands/tags.go, commands/volumes.go, commands/vpcs.go, integration/domain_records_delete_test.go, integration/droplet_delete_test.go, integration/firewall_delete_test.go, integration/image_delete_test.go, integration/snapshot_delete_test.go, integration/tags_delete_test.go
This started as wanting to quickly improve the delete confirmation messages for Droplets, and then I went down a bit of a rabbit hole... 
We have a lot of prompts like:
> Are you sure you want to Delete 1 droplet(s)? (y/N) ?
This updates them not have strange capitalization in the middle of sentences and pluralize things correctly. Eg:
> Are you sure you want to delete this Droplet? (y/N) ?
> Are you sure you want to delete 2 Droplets? (y/N) ?
It adds a new `AskForConfirmDelete` method for normal cases but leaves the more generic `AskForConfirm` for ones that need more customization.
It also adds missing integration tests for commands that can delete multiple resources at the same time.
=> Improve delete confirmation messages

commands/images.go, integration/image_list_test.go
We've been reluctant to change this behavior due to the potential to break scripting for existing users, but it is clear that this can be confusing, especially when no private images exist. This PR adds a notice to `compute image list` output about the `--public` flag when the response is empty.
See: https://github.com/digitalocean/doctl/issues/314 & https://github.com/digitalocean/doctl/issues/784
=> Add notice to 'compute image list' output about '--public' flag when response empty.

commands/kubernetes.go
Don't literally display `doctl.ArgClusterNodePool` var.
=> Fix display of 'kubernetes cluster create -h'

commands/kubernetes.go
Make clear that node pool configuration must be surrounded by quotes and fix reversed help output for min-nodes and max-nodes.
Fixes: https://github.com/digitalocean/doctl/issues/793
=> Fix 'kubernetes create' documentation issues.

args.go, commands/registry.go, commands/registry_test.go, integration/registry_docker_config_test.go
Add a command, `doctl registry docker-config`, that prints a Docker config. This is useful for users who want to configure a third-party tool such as a build system to access their registry, and mirrors the functionality offered in the control panel.
=> registry: Add a command to get a Docker config

.travis.yml
I've noticed seemingly random integration test failures on macOS recently when reviewing/merging PRs. These failures all look like:
```
=== CONT  TestRun/doctl/compute/firewall/update/an_updated_name_and_the_old_inbound_rules_are_provided/updates_a_firewall
TestRun/doctl/compute/firewall/update/an_updated_name_and_the_old_inbound_rules_are_provided/updates_a_firewall: firewall_update_test.go:74: 
Error Trace:	firewall_update_test.go:74
spec.go:269
spec.go:262
parser.go:133
Error:      	Received unexpected error:
fork/exec /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/integration-doctl191387348/doctl: too many open files
Test:       	TestRun/doctl/compute/firewall/update/an_updated_name_and_the_old_inbound_rules_are_provided/updates_a_firewall
Messages:   	received error output from …
```
=> Set higher ulmit on macOS builds to prevent "too many open files" error.

args.go, commands/kubernetes.go, commands/kubernetes_test.go
Adds `--vpc-uuid` flag to DOKS cluster create
=> kubernetes: Add support for specifying vpc-uuid

args.go, commands/displayers/droplet.go, commands/droplets.go, commands/droplets_test.go, integration/droplet_create_test.go, integration/droplet_get_test.go, integration/droplet_list_test.go, integration/droplet_neighbors_test.go, integration/projects_resources_get_test.go
Adds the VPC UUID flag for Droplet creates. I paired on this with Cesar as an intro to `doctl`.
Closes #802
=> Add VPC UUID flag to Droplet creates

args.go, commands/registry.go, commands/registry_test.go, go.mod, go.sum, integration/registry_docker_config_test.go, integration/registry_login_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/registry.go, vendor/modules.txt
By default, credential used to access container registries do not expire. When logging into the registry as part of a CI/CD process, this causes a number of issues. This PR exposes the `expiry_seconds` query parameter to the Docker config commands to allow for short lived credential.
=> Expose expiry_seconds for Docker config commands.

commands/droplets.go
Improvements to the help output for the `compute droplet create` command including some updated language, a full usage example, and pointing users to the commands under `doctl compute image` to find images.
Fixes: #814
=> Improve help output for compute droplet create command.

commands/1_clicks_test.go, commands/droplets.go, commands/droplets_test.go, commands/kubernetes.go, commands/kubernetes_test.go
This adds the 1-click list command to both kubernetes and droplet with the "type" specified depending on context.
=> Add mp 1 click to k8s and droplet

README.md
`doctl` is available in the official repo (it's a community repo but official non the less).
proof: https://www.archlinux.org/packages/community/x86_64/doctl/
=> Add to README - available in Arch Linux repo

README.md, commands/droplet_actions.go
Customer feedback on the product docs page pointed out that the current help is inadequate. This improves on it. It also marks `ArgSizeSlug` as required.
=>  Improve help for 'doctl compute droplet-action resize'

args.go, commands/apps.go, commands/apps_test.go, do/apps.go, do/mocks/AppsService.go, go.mod, go.sum, integration/apps_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/invoices.go, vendor/modules.txt, vendor/sigs.k8s.io/yaml/.travis.yml, vendor/sigs.k8s.io/yaml/OWNERS, vendor/sigs.k8s.io/yaml/README.md, vendor/sigs.k8s.io/yaml/go.mod, vendor/sigs.k8s.io/yaml/go.sum, vendor/sigs.k8s.io/yaml/yaml.go
This depends on https://github.com/digitalocean/godo/pull/358 and will need to be updated with a vendor change once a godo release is cut; it's currently pointing directly at that commit.
This PR fixes incorrect handling of yaml specs and also adds support for following logs.
=> apps: fix yaml spec handling and add support for log following

args.go, commands/apps.go, commands/apps_test.go, go.mod, go.sum, integration/apps_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
This defaults the deployment ID to the current deployment, and the component name to '' so aggregate logs are used.
APPS-1547
=> apps: add defaults for deployment id and component name

commands/apps_test.go, go.mod, go.sum, integration/apps_spec_test.go, integration/apps_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/modules.txt
* upgrade godo to v1.45.0
* fix apps tests as a result of breaking godo changes
=> upgrade godo to v1.45.0

args.go, commands/displayers/kubernetes.go, commands/kubernetes.go, commands/kubernetes_test.go
This change allows to set node pool taints during node pool create and update operations.
Refs digitalocean/DOKS#3
=> Kubernetes: add support for node pool taints

commands/auth.go, commands/doit.go, commands/kubernetes.go
This change adds a PersistentPreRun command hook to only create the default configuration directory if no custom config path is set.
I see that the oconfigHome() is used by the Kubernetes command for the cache directory so I opted to leave the function as is to not break any other commands that might be relying on the function to create the config directory if it doesn't already exist. 
The test were left unmodified as there appears to be coverage for using a custom cfg file path already, but happy to add a test to confirm that the directory is not created when specifying a custom cfg file. 
Closes #833
=> commands/doit: Prevent creation of config home when using `--config`

commands/account.go, commands/certificates.go, commands/completion.go, commands/image_actions.go, integration/cdn_create_test.go
Corrected all the misspellings in the codebase based on `misspell`. Closes #870.
=> Correct misspellings in the codebase

commands/apps.go
This checks that `app.ActiveDeployment` is not nil before assigning `deploymentID`. It also looks for an in progress deployment which is useful in the case someone is running `doctl apps logs --type build $ID` on a newly created app.
Closes: #878
=> app logs: Protect against panic when no deployment is found.

commands/volume_actions.go
Fixes #889 
```bash
❯ ./builds/doctl compute volume-action resize -h | grep GiB
--size int        New size in GiB (required)
```
=> Add the size unit to volume-actions help

Dockerfile
Previously, while building docker image, any change in this repo will create new intermediate image and all the binary after that need to be downloaded again. 
`ADD . /go/src/github.com/digitalocean/doctl/`
To avoid this, we can download the binary first and add the code later. 
Pros: This saves significant amount of time where network is slow and doing frequent code changes
=> Perf: Make use of cached binary instead of downloading

commands/registry.go
before:
```
zsh/4 10008  (git)-[docr/add-gc-subcommands]-% ./doctl registry repository list -h
This command retrieves information about repositories in a registry, including:
- The repository name
- The latest tag of the repository
- The compressed size for the latest tag
- The manifest digest for the latest tag
- The last updated timestamp
Usage:
doctl registry repository list [flags]
Aliases:
list, ls
Flags:
--format Name   Columns for output in a comma-separated list. Possible values: Name, `LatestTag`, `TagCount`, `UpdatedAt`
-h, --help          help for list
--no-header     Return raw data with no headers
Global Flags:
-t, --access-token string   API V2 access token
-u, --api-url string        Override default API endpoint
-c, --config string         Specify a custom config file …
```
=> registry: improve formatting on repositories long desc

commands/displayers/key.go
Displays public key. Previously it's not showing public key information.
With this PR, it shows Public key as well.
Fixes #894
=> SSH Key: make public key accessible

args.go, commands/vpcs.go, commands/vpcs_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/registry.go, vendor/github.com/digitalocean/godo/vpcs.go, vendor/modules.txt
Also updates godo to v1.50.0; required here to use the new `default` fields in `VPCUpdateRequest`.
=> vpc: add default option to vpc update

commands/displayers/key.go, commands/sshkeys.go
Updates the SSH key operations so that we're only showing the SSH public key for the GET operation.
Below is an example output after these changes,
```
> doctl compute ssh-key list
ID          Name        FingerPrint
18077907    Test Key    fc:46:a6:64:41:e5:80:a4:17:53:ae:02:4f:29:a4:8e
> doctl compute ssh-key get 18077907
ID          Name        FingerPrint                                        Public Key
18077907    Test Key    fc:46:a6:64:41:e5:80:a4:17:53:ae:02:4f:29:a4:8e    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBykkcZtToFp7nNUM6RQS5XqXWRhFSzcZTftrqTFMH45QZZb1MNk4yB3p1OFszlC30/O5mWRujryJjuyZ7H+tca96Chh1rJpwOFscVoame6YThPt9+nrAq30VY2tM6nR8d4iDD+1fXx5wa95CNH+Ns/r8dO/vfxSJaGe5Brn6JQOSsjvI/J5n8S7Q7B7csz03MHW+rpwyg6NhVDJHwMGdHU6bG+QyC18G8e8cWz2p0AiUIuaVaZfghx5B2WiibDnxZfh/p5VWgs85FasAQ7 …
```
=> Only show SSH public key for list operation

commands/droplets.go
Might fix #895 -- I'm not very experienced in Golang.
```
❯ ./builds/doctl compute droplet list
ID           Name             Public IPv4       Private IPv4    Public IPv6    Memory    VCPUs    Disk    Region    Image                     VPC UUID                                Status    Tags    Features              Volumes
213635352    hacktoberfest    142.93.240.125    10.116.0.2                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64    0c20a2e6-b9ca-43fd-8b22-def8741321ac    active            private_networking    
213653028    hacktoberfest    142.93.5.117      10.116.0.3                     1024      1        25      nyc1      Ubuntu 20.04 (LTS) x64    0c20a2e6-b9ca-43fd-8b22-def8741321ac    active            private_networking
```
```
❯ ./builds/doctl …
```
=> Add support for getting Droplets by name

commands/actions.go, commands/certificates.go, commands/databases.go, commands/domains.go, commands/droplet_actions.go, commands/droplets.go, commands/errors.go, commands/firewalls.go, commands/floating_ip_actions.go, commands/floating_ips.go, commands/image_actions.go, commands/images.go, commands/kubernetes.go, commands/load_balancers.go, commands/projects.go, commands/registry.go, commands/sshkeys.go, commands/tags.go, commands/volume_actions.go, commands/vpcs.go
When a user provides multiple arguments to a command then only accepts one, we provide unclear error messaging. For example:
```
$ doctl databases sql-mode get aaa-bbb-ccc ddd-eee-fff
Error: (sql-mode.get) command is missing required arguments
```
This PR adds a new helper method, `ensureOneArg`, that returns a `MissingArgsErr` if no args are passed or a `TooManyArgsErr` (introduced in https://github.com/digitalocean/doctl/pull/902) if more than one is passed. This allows for clearer messaging:
```
$ ./builds/doctl databases sql-mode get aaa-bbb-ccc ddd-eee-fff
Error: (sql-mode.get) command contains unsupported arguments
$ ./builds/doctl databases sql-mode get
Error: (sql-mode.get) command is missing required arguments
```
=> Improve error messaging when more args than expected are passed.

recorder.go
In https://github.com/digitalocean/doctl/issues/908, when the reporter tried to produce a trace, it resulted in a panic. We're not checking this error.
=> Check error in RoundTrip.

commands/registry.go
Removes EA prefix from container registry sub-command
=> apps: remove EA prefix from registry commands

args.go, commands/displayers/registry.go, commands/registry.go, commands/registry_test.go, do/mocks/RegistryService.go, do/registry.go, go.mod, go.sum, integration/registry_create_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/CONTRIBUTING.md, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/registry.go, vendor/modules.txt
As of GA, creating a container registry requires specifying a subscription tier. Add support for listing available subscription tiers, and add a `--subscription-tier` option for create, defaulting to the "basic" plan.
=> Support subscription tiers for DOCR

commands/kubernetes.go
Along with the broader Kubernetes community and industry, we're moving away from using the word "master" to describe the Kubernetes control plane. We've never explicitly referred to either in our API or control panel, but we do mention it in the docs for `doctl k8s cluster get`. Update those docs to be more accurate by describing the k8s API server rather than the nebulous "master node".
=> kubernetes: Stop using "master" to describe the control plane

README.md
I've added `fish` item in the README.md's auto completion section.
I added fish completion (ref: [Add fish completions](https://github.com/digitalocean/doctl/pull/767)), but I found that I forgot to update the doc.
=> Update fish auto completion document

commands/completion.go
To test from this branch, run:
```
make build
docker run -it --mount type=bind,source="$(pwd)"/builds,target=/app alpine /bin/sh
apk add zsh
zsh
autoload -Uz compinit
compinit
source <(./app/doctl completion zsh)
```
No error should be reported and completion should function as expected.
Closes: https://github.com/digitalocean/doctl/issues/916
=> completion/zsh: Use correct word boundary pattern for BusyBox sed

.github/workflows/ci.yml, .travis.yml, Makefile, commands/displayers/registry.go, commands/registry.go
Migrates the tests from Travis to GitHub Actions.
Also fixes a `gofmt` failure so that those checks would pass.
Tested at https://github.com/bentranter/doctl/pull/1.
=> Migrate tests to GitHub Actions

args.go, commands/registry.go, commands/registry_test.go, do/mocks/RegistryService.go, do/registry.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/images.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/registry.go, vendor/modules.txt
The intent here is to provide users of DOCR a way to optionally garbage collection untagged manifests while retaining the previous default behavior of only garbage collecting unreferenced blobs.
=> registry: add support for garbage collection types

commands/displayers/apps.go, commands/displayers/util.go, integration/apps_tier_test.go
Makes the output look a little nicer 😄 
before:
```
❯ go run ./cmd/doctl apps tier list
Name            Slug            Egress Bandwidth    Build Seconds
Starter         starter         1.07 GB             6000
Basic           basic           42.95 GB            24000
Professional    professional    107.37 GB           60000
```
after:
```
❯ go run ./cmd/doctl apps tier list
Name            Slug            Egress Bandwidth    Build Seconds
Starter         starter         1.00 GiB            6000
Basic           basic           40.00 GiB           24000
Professional    professional    100.00 GiB          60000
```
=> apps: display tier units in base-1024

commands/registry.go, commands/registry_test.go, integration/registry_garbagecollection_test.go
In the [product docs for garbage collection](https://www.digitalocean.com/docs/container-registry/how-to/clean-up-container-registry/) we mention a confirmation prompt when initiating a garbage collection but I neglected to include this behavior during the initial implementation. This PR addresses that.
=> registry: confirm user wishes to start garbage collection

.travis.yml
Docker is rate-limiting pulls. Log into the sammytheshark user before building snaps so that we are not an anonymous user being rate-limited by the shared Travis IP address. 
https://blog.travis-ci.com/docker-rate-limits
https://www.docker.com/increase-rate-limits
=> travis: Log into Docker before pulling images.

commands/volume_actions.go, commands/volume_actions_test.go, integration/compute_volume_action_test.go
added subcommand 'compute volume-action get' to check on status of action.
=> Add GET operations to volume-actions doctl

commands/apps.go, commands/apps_test.go
* Updates decoding for `app spec` to ignore unknown fields. 
This should help alleviate confusion where the user is on an older version of doctl before the relevant godo models were updated for a particular feature. Previously, the create/update would succeed but the values would be stripped from the payload.
=> apps: disallow unknown fields during spec parsing

Makefile, commands/validations.go
Happened to notice that our gofmt_check makefile target is not running correctly in CI:
https://github.com/digitalocean/doctl/runs/1751541753?check_suite_focus=true#step:5:8
Output before change:
```
asb@asb-home:~/development/gocode/src/github.com/digitalocean/doctl$ make gofmt_check
==> ensure code adheres to gofmt (with vendor directory excluded)
/bin/sh: 1: read: arg count
asb@asb-home:~/development/gocode/src/github.com/digitalocean/doctl$ echo $?
0
```
Output after change:
```
asb@asb-home:~/development/gocode/src/github.com/digitalocean/doctl$ make gofmt_check
==> ensure code adheres to gofmt (with vendor directory excluded)
gofmt checking failed:
./commands/validations.go 
make: *** [Makefile:112: gofmt_check] Error 1
asb@asb-home:~/development/gocode/src/github.com/digitalocean/do …
```
=> Fix gofmt_check makefile target.

args.go, commands/displayers/kubernetes.go, commands/kubernetes.go, commands/kubernetes_test.go, do/kubernetes.go, do/mocks/KubernetesService.go
This PR vendors godo v1.57.0 and adds subcommands and flags to support optional cascading deletes for a Kubernetes cluster. 
cc @adamwg , @MorrisLaw
=> kubernetes: add support for optional cascading deletes

args.go, commands/databases.go, commands/databases_test.go, commands/displayers/database.go, do/databases.go, do/mocks/DatabasesService.go, integration/database_firewall_add_test.go, integration/database_firewall_list_test.go, integration/database_firewall_remove_test.go, integration/database_firewall_update_test.go, vendor/github.com/digitalocean/godo/databases.go
adding the following functionality:
doctl databases firewalls list <db uuid>
doctl databases firewalls add <db uuid> --rule type:value
doctl databases firewalls remove <db uuid> --rule type:value
doctl databases firewalls update <db uuid> --rule type:value [--rule type:value]
=> Doctl support for database firewalls management

commands/kubernetes.go
Description: Now that surge upgrades is stable, enable surge upgrades by default as it is a better user experience during upgrades. 
cc @adamwg
=> kubernetes - enable surge upgrade by default during cluster creation

commands/apps.go
This description felt misleading. You do not provide a spec as an argument. It uses the existing spec. I've replaced it with the description for the endpoint in the API docs:
https://developers.digitalocean.com/documentation/v2/#create-an-app-deployment
=> apps: Improve help for create-deployment.

commands/displayers/kubernetes.go
After merging https://github.com/digitalocean/doctl/pull/956, I discovered additional changes were required. The changes to `godo.KubernetesAssociatedResources` meant we were not outputting pointers to a struct rather than strings. `main` currently outputs:
```
$ ./builds/doctl kubernetes c list-associated-resources 087d13f4-a226-4ee4-92b9-35d6b3d9ebb1
Volumes           Volume Snapshots    Load Balancers
[0xc0007170e0]    []                  [0xc000717180]
```
After the changes in the PR, it correctly outputs:
```
$ ./builds/doctl kubernetes c list-associated-resources 087d13f4-a226-4ee4-92b9-35d6b3d9ebb1
Volumes                                   Volume Snapshots    Load Balancers
[28db039f-43bd-11eb-8cf0-0a58ac1467fa]    []                  [a91a98de-9b5f-4198-91cd-f852e36f8265]
``` …
=> k8s list-associated-resources: Output strings.

.travis.yml
We build an publish "candidate" builds of the Ubuntu Snap on each push to `main`.  These packages seem to have fallen behind:
```
$ snap info doctl | grep candidate
latest/candidate: v1.54.1+git1.1a2b5dd  2021-01-20 (427) 10MB -
```
They are being build, but not actually being uploaded. 
> Skipping a deployment with the snap provider because this branch is not permitted: main
https://travis-ci.org/github/digitalocean/doctl/jobs/760024996#L302
Looks like it defaults to master if not explicitly set: https://docs.travis-ci.com/user/deployment
=> travis: Use main for Snap candidate builds.

commands/registry.go, commands/registry_test.go, integration/registry_kubernetes_manifest_test.go
The Kubernetes secret manifest  we generate makes it easy for users to pull private images into their DOKS cluster. Now that we have the dosecret-operator to make the secret available in all namespaces, generate operator friendly manifests for users to apply into their DOKS cluster. Applying the manifest generated here to a DOKS cluster is the same as doing:
```
doctl kubernetes cluster registry add
```
cc @adamwg , @timoreimann
=> registry - generate a DOSecret operator friendly secret manifest

commands/apps.go, commands/apps_test.go, integration/apps_test.go
In this pull request issue #964 is addressed:
- `--wait` flag was added to the `doctl apps create-deployment`
- defaults to `false`
- waits for deployment to enter `ACTIVE` phase
- on phases `ERROR`, `CANCELED` and `UNKNOWN` returns error
=> feat: wait flag for apps create-deployment command

.github/workflows/ci.yml, .gitignore, .travis.yml, Dockerfile, dockerfiles/Dockerfile.snap, go.mod, go.sum
Creating a draft PR for feedback while I continue testing the changes
=> Upgrade to Go 1.16

do/apps.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/vpcs.go, vendor/modules.txt
Requires a new godo release for: https://github.com/digitalocean/godo/pull/443
Fixes: https://github.com/digitalocean/doctl/issues/975
=> apps: Support pagination.

args.go, commands/apps.go, commands/apps_test.go, commands/displayers/apps.go, commands/displayers/util.go, do/apps.go, do/mocks/AppsService.go, integration/apps_spec_test.go, integration/apps_test.go
1. Added `doctl apps propose`
2. Updated `doctl apps spec validate`
3. Updated other commands to accept reading app specs from stdin by setting the path to `-`
API docs: https://developers.digitalocean.com/documentation/v2/#propose-an-app-spec
Usage: `doctl apps propose --spec spec.yaml [--app app-id]`
```
App Name Available?    Is Static?    Free Static Site Usage    $/month    $/month on higher tier    $/month on lower tier
yes                    no            3 of 3                    5.00       17.00                     n/a
```
```
App Name Available?    Suggested App Name     Is Static?    Free Static Site Usage    $/month    $/month on higher tier    $/month on lower tier
no                     sample-dockerfile-2    no            3 of 3                    5.00       17.00 …
```
=> apps: add `apps propose` command, expand spec validation

commands/completion.go
Update the fish documentation to correct for calling it zsh, as well as using the correct startup file, and changing the bash-only `<()` syntax to fish's `(|psub)`
=> Fix fish documentation

commands/auth.go, commands/auth_test.go, commands/command_config.go
Hello,
From the issue #965, I've created a command to remove an account from the list account:
Before:
After:
Feedbacks are welcome
=> New Command - remove account from config file

README.md
This updates the command listed in the README.md to completely remove the configuration (on MacOS) with quotes around the path so the space in `Application Support` doesn't get confused for an argument separation.
```
rm -rf "$HOME/Library/Application Support/doctl"
```
Fixes #979
=> Update README with the appropriate command to remove configuration

integration/auth_remove_context_test.go
This adds integration tests for the new command added in #981
Edit: To run just this new test (locally), I used: 
`go test -v -mod=vendor ./integration/init_test.go ./integration/auth_remove_context_test.go`
Results:
```
=== RUN   TestRun
Suite: doctl
Total: 2 | Focused: 0 | Pending: 0
=== RUN   TestRun/doctl
=== RUN   TestRun/doctl/auth/remove/a_context_is_not_provided/should_error
=== PAUSE TestRun/doctl/auth/remove/a_context_is_not_provided/should_error
=== RUN   TestRun/doctl/auth/remove/a_valid_context_is_provided/allows_you_to_remove_that_context
=== PAUSE TestRun/doctl/auth/remove/a_valid_context_is_provided/allows_you_to_remove_that_context
=== CONT  TestRun/doctl/auth/remove/a_context_is_not_provided/should_error
=== CONT …
```
=> Add integration test for new remove auth command

commands/firewalls.go, commands/firewalls_test.go, go.mod, go.sum, integration/floating_ip_create_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/firewalls.go, vendor/github.com/digitalocean/godo/floating_ips.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
This PR updates `godo` to `v1.61.0` to be able to add support for DOKS clusters as peers in Cloud Firewalls rules.
=> Add support for DOKS as Firewalls peers

commands/kubernetes.go
This PR adds the capability of ignoring empty node-pool arguments. Some background to motivate this:
The documentation doesn't mention that the --num-nodes string should not terminate with a `;` character. Therefore, when trying to use an argument like `--num-nodes:"name=pool-name;count=3;"` the command fails with an error, because the trailing `;` character results in an empty arg.
=> Allow node-pool args to be empty

commands/apps.go, commands/apps_test.go, integration/apps_test.go
(reopened PR to disregard 400+ vendor files committed)
per github issue #970 - adding a wait flag for doctl apps create command. The integration test is taking 30 seconds to complete. This causes a timeout error- if timeout is removed it works. Looking for a second pair of eyes to help determine why the test takes so long.
applies changes suggested from previous pr such as:
- replaced ticker with for loop (thanks @bentranter)
- clearer error messages
=> adding the --wait flag to the apps create command

.goreleaser.yml
When GitHub generates source tarballs on the fly, there is no guarantee of byte-for-byte equivalence. This can cause issues for distribution packagers and others that wish to verify their downloads. 
This can be tested locally using: `goreleaser --snapshot ` The resulting `dist/` directory should include a tarball with the project source and the resulting SHA256 file should have the checksum of that file.
=> goreleaser: Release stable source tarball (fixes: #1001).

commands/auth.go, integration/auth_test.go
"Fixes" a bizarre issue where running `doctl auth switch` mangles all auth contexts that contain a `.` character.
Prior to this change, when the command was run, it appears that Viper decides that anything containing a `.` indicates that the value should be split at the `.`, and then anything after it should become the key of a nested entry in a map in the config YAML file.
I have no idea why this fix works, but it does. I'm still looking into the root cause, but I figure that we might as well get this change out.
=> Fix auth key mangling when switching contexts

args.go, commands/apps.go, commands/apps_test.go, do/apps.go, do/mocks/AppsService.go, go.mod, go.sum, integration/apps_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
This PR introduces a new flag on `apps logs` so users can specify the number of live log lines they want to fetch from an application. Currently, running `apps logs` will return all log lines.
It behaves as `docker logs` and `kubectl logs` would:
```sh
doctl apps logs <app-id> --tail 10
doctl apps logs <app-id>
```
Note: I ran `make mocks` and most of the mock files changed, so I only committed changes to `mocks/AppsService.go` to keep the PR small. I tried using several different versions of `mockgen` but they all resulted in a large diff. Let me know if there's a specific version of `mockgen` I should use, or if I should commit all the mock changes in this PR.
=> apps: Add --tail flag to support tailing live application logs

.github/workflows/release.yml, .github/workflows/snapcraft-candidate.yml, .goreleaser.yml
Migrates workflows from travis-ci.org to GitHub Actions.
- migrates changelog generator to use goreleaser
- adds workflow to build and publish a snap release candidate on push to main
- adds job to the release.yml workflow to build a publish a snap stable release on push of a tag
For APICLI-490
=> Adds release workflow

.github/workflows/release.yml
Fixes failing Snap release https://github.com/digitalocean/doctl/runs/3284170811?check_suite_focus=true
This is the same fix used for candidate releases from https://github.com/digitalocean/doctl/pull/1011
=> workflow/snapcraft-stable: Fetch all tags.

.github/workflows/release.yml
This should build Darwin ARM64 releases again. 
https://github.com/digitalocean/doctl/runs/3284170730?check_suite_focus=true#step:6:29
=> workflow/github-release: Build with Go 1.16.x

args.go, commands/displayers/load_balancer.go, commands/load_balancers.go, commands/load_balancers_test.go, go.mod, go.sum, integration/lb_create_test.go, integration/lb_get_test.go, integration/lb_list_test.go, integration/lb_update_test.go, integration/projects_resources_get_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
This brings in the change from godo: https://github.com/digitalocean/godo/pull/482 to doctl. We may need a new version release for godo before this can go in. This will probably also require some updates to doctl from DOKS side.
=> doctl/load-balancers: add flag to toggle automatic DNS record creation for certs attached to load balancers

commands/kubernetes.go, commands/kubernetes_test.go
It's been decided that we will not support toggling the HA feature via the `update` command for the EA release. So this PR removes that the HA feature from the `update` command.
While this is technically a breaking change, it will not impact any users since it is a internal-only feature at this moment.
cc: @adamwg
=> k8s/doctl: remove ha flag from update command

commands/auth.go
I think that the help instructions in the `doctl auth list` command are (no longer?) valid, and that switching auth context must be done using the `doctl auth switch --context <name>` command.
This PR fixed the help text.
(I’m sorry if I’m mistaken – I just started using `doctl` today and run into this when trying to switch between contexts.)
=> Fix `doctl auth list` command’s help

commands/displayers/registry.go, commands/registry.go, commands/registry_test.go, do/mocks/RegistryService.go, do/registry.go, go.mod, go.sum, integration/registry_repo_list_v2_test.go, integration/registry_repo_manifest_list_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/README.md, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/links.go, vendor/github.com/digitalocean/godo/registry.go, vendor/modules.txt
CON-3907
Required bump to godo 1.73
=> registry: Add support for ListRepositoriesV2 and ListManifests commands.

do/pagination.go
The motivation for these changes is to ensure that results are ordered as they were intended to be by the endpoint being called. Currently, pages may be inconsistently ordered after the first, depending on the order in which the async page loads are completed.  This likely hasn't been an issue since there would need to be 3+ pages (at least 401 results) to be observed. 
Out-of-order results can be observed by temporarily updating pagination `perPage` to some small value like `5` and running a command with more than a handfull of pages of results. 
**current pagination**
```
$ builds/doctl registry repository list
Name       Latest Tag    Tag Count    Updated At
1            2021-12-08 17:02:20 +0000 UTC
bulk_05    bulk_01       1            2021-12-08 17:02:49 +0000 UTC
bulk_02    bulk_01 …
```
=> pagination: updated pagination to give deterministic and natural ordering

args.go, commands/kubernetes.go, integration/kubernetes_clusters_kubeconfig_save_test.go
per #856- adding the option to add an alias for a kubernetes context, as such:
`go run cmd/doctl/main.go kubernetes cluster kubeconfig save k8ds-test --alias=newalias_k8ds`
=> APICLI-528: adding option to pick context name in 'kubeconfig save'

commands/databases.go
We received some user feedback via the `doctl` docs where users were trying to downsize database nodes, which is not allowed. I've updated the resize command to reflect this. I also reworded the doc to be a little clearer.
=> Database Resize Command Clarification

go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
This PR bumps `godo` to incorporate digitalocean/godo#506 changes (released [here](https://github.com/digitalocean/godo/pull/507)), allowing `doctl` users to create and manage apps that have `functions` components.
I verified locally that commands like `apps create` and `apps spec get` work as expected with the new component type.
=> Update godo to support new app component type

snap/snapcraft.yaml
The version was taken by running `version: git` which is a short hand for `version: $(git describe)` which can at times add the commit hash to the end of the version. This change forces the version to be set by the script in the `override-build` section lower in `snapcraft.yml` .
=> Snap Version Fix

.github/workflows/release.yml, .github/workflows/snapcraft-candidate.yml
The extra `v` is no longer set on the snap name. it was originally set by `version: git`. The new version name will be `doctl_1.70.0_amd64.snap`
=> remove v from snap name:

.github/workflows/release.yml, .github/workflows/snapcraft-candidate.yml, scripts/version.sh, snap/snapcraft.yaml
This adds a new `--snap` flag to `scripts/version.sh` that is aware if it is being run from a tag and outputs desired snap version. I've added this as a new function to ensure that I don't unintentionally change any other usages of this script.
From a non-tagged version, `+git${SHA}` should be appended to the version. Eg.
```
./scripts/version.sh --snap
v1.70.0+git2cdebf6f
```
From a tagged version, it should print tag:
```
./scripts/version.sh --snap
v1.70.0
```
=> Update scripts/version.sh to output desired snap version.

snap/snapcraft.yaml
Following up on https://github.com/digitalocean/doctl/pull/1100, the leading `v` needs to be stripped before setting setting the ldflags to make sure `doctl version` is correct. We convert the string to an int. `v1` will fail and lead to `0` being set as the major version.
https://github.com/digitalocean/doctl/blob/455a4e5d1c2b8aa1ef5f65954aa3562eaf8ae56e/doit.go#L84-L87
=> Strip leading 'v' before setting ldflags.

.github/workflows/ci.yml
In order to test and merge PRs to the sandbox feature branch (e.g. https://github.com/digitalocean/doctl/pull/1107) we need the PR workflow to run.
=> Run PR workflow for feature branches.

.github/workflows/ci.yml, commands/activations.go, commands/activations_test.go, commands/databases.go, commands/functions.go, commands/functions_test.go, commands/sandbox-extra.go, commands/sandbox.go, commands/sandbox_test.go, do/mocks/SandboxService.go, do/sandbox.go
This PR adds more tests for the sandbox commands. They are mostly very basic and only test that the correct arguments are passed through to nim. Though I did make some changes to start some deeper testing. Where possible, I've moved to using `CmdConfig.Out` so that we can test the actual command output as well. There should be no functional changes.
=> sandbox: Add additional tests.

commands/command_config.go, commands/commands_test.go, commands/sandbox.go, commands/sandbox_test.go
This change works in conjunction with a change to the sandbox plugin.  
The sandbox plugin build has been changed to
1.  Include a `version` file in the download.  This file becomes part of the installed sandbox support.
2. Label downloads by encoding the version in the name of the tarball to download.
By convention, version strings encode the Nimbella CLI version followed by the sandbox plugin "shim" version. 
There is an exemplar of this change already out there that can be use to test the present change.   It is at version 2.3.1-1.0.0.
The present change
1.  Adds a constant in `sandbox.go` representing the minimum version of the plugin that this `doctl sandbox` can run with.
2. Generalizes functions that determined if the sandbox is installed, so that they also detect if the sandbox is …
=> Versioning and update for 'doctl sandbox'

commands/command_config.go, commands/sandbox.go, commands/sandbox_test.go, do/mocks/SandboxService.go, do/sandbox.go
This change restores functionality to `doctl sandbox connect` that was lost due to changes in the functions cloud.   It uses DigitalOcean APIs to retrieve the necessary information that used to be retrieved by invoking administrative functions.   It also expands the functionality of the command as follows.
```
Usage:
doctl sandbox connect [<token>|<namespace>] [flags]
```
The argument is now optional.  If it is omitted, the function namespaces of the account are searched to find an eligible sandbox namespace.  If it is provided, it can now be either a namespace name, or a JWT issued by the UI for the namespace (previously only a JWT was accepted).
=> Fix doctl sandbox connect and support additional options

commands/activations.go, commands/activations_test.go, commands/sandbox.go, commands/sandbox_test.go
This change eliminates a bug in `doctl sandbox activation logs`.   The command was not behaving correctly when one of the flags `--poll`, `--tail`, or `--watch` was specified (these are actually equivalent). 
With these flags set, the command will now keep running, streaming its output to the console, making it appropriate to run in a separate window as designed.
To make this change, I changed the protocol between `doctl` and the sandbox plugin so that the plugin doesn't independently decide when the capture of output should be suppressed.   Rather, `doctl` directs this behavior with a prefixed command.
This in turn required incrementing the minimum required version of the sandbox.  The required version has been staged and will be available to `doctl sandbox upgrade`.
=> Correct behavior for 'sandbox actv logs --poll'

commands/sandbox.go, commands/sandbox_test.go
We deliberately omitted CRUD operations in the `functions` subtree and omitted the `packages` subtree entirely.  This was to avoid confusion between the portion of the sandbox in the local filesystem and the portion in the cloud, and maintain the idea that you push the former to the latter with `deploy`.   As this leaves developers with no way to delete resources from the namespace, we need an `undeploy`.   Given that this is a destructive operation, I made an `--all` flag obligatory when you wish to undeploy everything, and allowed specific resources to be listed on the command line.
```
Usage:
doctl sandbox undeploy [<package|function>...] [flags]
Flags:
--all        remove all packages and functions
```
This PR will remain a draft until I have added supporting unit tests.
=> Add an 'undeploy' command

commands/sandbox.go
Also changes the minimum required nim release to 2.3.7, since that is the point at which we officially started bundling node 16.x rather than 14.x.
Older versions of nim and hence the sandbox would almost certainly work with node 16 but were not explicitly tested with it.
=> Upgrade node version to 16.13.0

.goreleaser.yml
Built a local snapshot with goreleaser and realized `doctl version` shows the `release` label. This makes it so that the `snapshot` label is used when building with `goreleaser build --snapshot`
=> goreleaser: Don't use release label for snapshots.

README.md
The README instructions for auto-completions on Linux for zsh don't currently work.
Cobra handles zsh completion generations differently so sourcing them is not enough to activate the completions: https://github.com/spf13/cobra/blob/master/shell_completions.md#zsh-completions
Either `compdef _doctl doctl` needs to be added after sourcing, or the generated completions need to be added to a file on the $fpath.
The help message for doctl completion zsh actually has the correct instructions:
```
❯ doctl completion zsh --help
Generate the autocompletion script for the zsh shell.
If shell completion is not already enabled in your environment you will need
to enable it.  You can execute the following once:
$ echo "autoload -U compinit; compinit" >> ~/.zshrc
To load completions for every new …
```
=> fixed the instructions for auto-completions on zsh

commands/sandbox.go
The Nimbella CLI version 2.3.9 contains two fixes relevant to doctl sbx commands.
1.  The use of initial './' sequences in .include file entries was causing incorrect behavior. Although unnecessary, these sequences should be harmless.
2.  Incremental deploy (used by 'doctl sbx watch') was not detecting environment changes. If the change was made to project.yml or to a contained .env file the watcher would "fire" as per the spec. However, when calculating whether actions had changed it failed to include the environment clause and the affected actions would be unchanged.
=> Adopt nim 2.3.9, which fixes two bugs

commands/sandbox.go, pkg/extract/extract.go, pkg/extract/extract_test.go
This replaces shelling out to `tar` with a new utility package. It is the first step to getting sandbox support working for Windows. The Node download for Windows only comes as a zip, hence the support for extracting zips in the utility package.
=> sandbox: Use Go native libs to extract archives.

commands/command_config.go, commands/sandbox.go
As mentioned in https://github.com/digitalocean/doctl/pull/1122, the Node download for Windows only comes as a zip. Additionally, I found that Windows (or at least the version of PowerShell I was testing in) will not run it without the `exe` file extension. So this required special casing Windows in a few places.
=> sandbox: Support Windows node downloads.

commands/displayers/registry.go, commands/registry.go, commands/registry_test.go, do/mocks/RegistryService.go, do/registry.go, go.mod, go.sum, integration/registry_create_test.go, integration/registry_get_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/github.com/digitalocean/godo/monitoring.go, vendor/github.com/digitalocean/godo/registry.go, vendor/modules.txt
=> docr: add region support

commands/sandbox.go
The fix in Nimbella CLI 2.3.10 addresses a problem with remote build when using the default package.
=> Incorporate a newer Nimbella CLI version with a bug fix

commands/projects.go
Apps can be assigned to projects.  This patch adds support for getting an project resource that is an app by running 'doctl resources get do:app:APP_UUID'.
=> Add ability to get 'app' project resources

commands/tags.go, commands/tags_test.go, integration/tags_apply_test.go, integration/tags_remove_test.go, pkg/urn/urn.go, pkg/urn/urn_test.go
Somehow we've never added support for tagging arbitrary resources. There is a `doctl compute droplet tag` command that allows you to tag a single Droplet, but there is no wider support for other resources or tagging multiple in one request. The PR adds new `doctl compute tag apply` and `doctl compute tag remove` commands. 
These can tag multiple resources using their URNs (e.g. `--resource do:droplet:123456 --resource do:kubernets:aaa-bbb-ccc`). The API itself does not use URNs, but it seemed like an natural approach here as we already use this pattern for other commands like assigning resources to project. So this also adds a small utility package for working with URNs.
=> tags: Support applying and removing tags from resources.

commands/activations.go, commands/activations_test.go, commands/const.go
An earlier change broke the functionality of `activations logs --follow`.   It is necessary to translate the `--follow` flag to one of the flags actually recognized by `nim` (`--watch`, `--poll`, or `--tail`) before invoking `nim`.
=> Fix bug in sandbox activations logs --follow

CONTRIBUTING.md
Removes outdated release note docs related to a release failure.
Also removes the bullet point about installing `github-changelog-generator`, as that gets installed for you when you run `make changes`.
=> Remove outdated release note docs

commands/sandbox-extra.go, commands/sandbox.go, do/sandbox.go
Improves the output from deploy so that there is more context for the actual error.  Also ensures that a non-zero exit code is posted on a deploy error.
The change requires a change in `nim` and in the sandbox plugin code so the minimum required version is incremented in addition to the other required changes.
=> Improvements to error output display

commands/command_config.go, commands/commands_test.go, commands/sandbox.go, commands/sandbox_test.go, do/sandbox.go
Beta users of `doctl sandbox` have reported that a common user error is handled in a confusing way.   If the user has done `doctl sandbox install` but not `doctl sandbox connect`, and then tries other sandbox commands, the errors that come back are arbitrary and confusing because they are attempting to invoke various APIs on the serverless backend.   This change inserts a pre-check for being connected, prior to calling out to the sandbox plugin, meaning that the user always gets the informative message saying that the sandbox needs to be connected.
It is important that the pre-check not double the overhead of most calls, which is what would happen if we invoked the plugin to do the credential check.   So, the check uses a simple file existence check, which is slightly weaker since it …
=> Fail early and cleanly when the sandbox was never connected

commands/sandbox.go
The sole purpose of this PR is to establish serverless (and the shorter sls) as additional aliases of sandbox (and sbx).
=> Make serverless and sls aliases of sandbox

commands/sandbox.go
This change fixes two small bugs.
1.  If the GOARCH in the `doctl` instance is 386, it is used unmodified when downloading `nodejs`.   But, `nodejs.org` uses `x86` not `386`.   Furthermore, the combination of that arch with GOOS=linux can't be supported because `nodejs` does not provide a download for that combination.  This now results in an error.
2. The command `doctl sbx init` creates a `project.yml` in which there are fields that App Platform detection for a functions component will reject.   The fix for this is in `nim` 3.0.8` which is incorporated by incrementing the `minSandboxVersion` field.
=> Fix two small bugs (1) handling of arch=386, (2) sbx init adds unsupported config

commands/sandbox.go
This change increments the included `nim` version from 3.0.8 to 3.0.10.   Benefits:
- a more comprehensible error message when a function build for `nodejs` includes an invalid `package.json` file
- the ability to see more information about remote build errors when debugging is enabled
=> Increment nim version (improves error reporting)

commands/sandbox.go, commands/sandbox_test.go
This change allows the developer to know the version of the sandbox support, which is distinct from the doctl version.
Because `doctl sandbox status` relies on error returns for common cases (not installed, not at the right version, not connected) I decided on the following.
If you issue `doctl sandbox status` and the status is connected, you get all the information, including version:
``` 
> doctl sbx status
Connected to function namespace 'fn-5a...' on API host 'https://faas-....doserverless.co'
Sandbox version is 3.0.10-1.2.1
```
If the status is other than connected, you just get the error as before.
However, as long as sandbox support is installed, you can always get version information by specifying a flag.  The output differs according to whether your sandbox support is up to date. …
=> Add version info to 'sandbox status'

do/sandbox.go
It has been requested by security to switch from GET to POST when connecting to the sandbox.
The portal API has already been amended to accept both for the time being so we can cut over.
This PR accomplishes the switch.   Once this is approved and merged, a new `doctl` release will be needed before support for GET can be removed from the portal API.
=> Switch from GET to POST when connecting to sandbox

commands/sandbox-extra.go, commands/sandbox.go, commands/sandbox_test.go, do/mocks/SandboxService.go, do/sandbox.go
The current output of `doctl sbx status --languages` is not helpful in telling the user what keywords will actually be accepted on `doctl sbx init <path> --language <?>`.   It conflates "runtime categories" like `nodejs` with real languages (like `JavaScript`) and might also imply to some users that they need to (or even can) specify the exact release of a language runtime in the `doctl sbx init` command.
This change attempts to be clearer about the terminology and give a more helpful display.  It is designed so that the static table of languages compiled into `doctl` is inclusive of all languages for which `nim` had samples, but the actual table that is displayed is responsive to the backend reporting which runtimes are currently available.   This means that changes to the `doctl` code …
=> Improve friendliness of the languages table

commands/account_test.go, do/account.go, integration/account_test.go
When calling `doctl account ratelimit`, we return an error if we receive a 429 from the API. This isn't helpful. The rate limit info is in the response headers. We should return them despite the 429 error so the user knows when their limit resets.
=> account: ratelimit command should not error when limit exhausted.

commands/projects.go, commands/projects_test.go
This PR adds App Platform apps to the documented list of resources
supported by projects and adds an example URN for an app.
=> Add AppPlatformApp to Projects documentation

commands/sandbox.go
A problem was identified when a variable with a multi-line value (string containing newlines) is substituted into `project.yml` via the symbolic substitution mechanism.   The newlines come in "raw" which results in multiple lines of YAML and (usually) a parsing error.   This is fixed in `nim` 3.1.1, which now
- escapes newlines (turns them into `\\n` values) by default (release 3.1.0)
- also updates the `dotenv` parser dependency to support the documented syntax for putting multi-line values in `.env` file (release 3.1.1).  Using the previous release, a multi-line value could only be specified in the process environment.  In typical use cases you will want these in the `.env` file along with other substitutions.
This PR increments the `minSandboxVersion` number to incorporate the change.
=> Fix project.yml templating of multi-line variables

commands/functions.go, commands/functions_test.go
In `doctl sls fn invoke` the syntax `--param  key:value` is mandated for passing parameters.   Because the code is currently handing off to the sandbox plugin, where the syntax is `--param key value`, there is a translation between the two in the code.   This change fixes a flaw in the translation:  it was not taking into account that the value might contain a colon.   So, for example, `--param url:https://example.com` was failing with a spurious and confusing error message.
=> Fix bug in handling --param values with colons

commands/sandbox.go
The normal snap confinement for `doctl` won't allow it to exec anything outside its install area.   So, the sandbox will not work.
The circumvention is to use the `--devmode` flag on `snap install doctl` to disable the confinement.
This PR simply adds language to the output of `doctl sbx install` to give the user a clue that this will be necessary.   A proper fix will take more time.
=> Add warning language when installing under snap

commands/sandbox.go, snap/local/doctl-launch, snap/snapcraft.yaml
In order to support running when installed as a Snap, we need to ship the sandbox and node in the snap package. To do so, we:
- Override the sandbox directory both during install and at runtime so that the sandbox is installed to `/snap/doctl/current/opt/sandbox`
- Run `doctl sandbox install` during the snap build.
- When run as a snap, the sandbox credentials directory ignores the `OVERRIDE_SANDBOX_DIR` environment variable as `/snap/doctl/current/opt/sandbox` is not writable. The default directory in the user's home will always be used (`$XDG_CONFIG_HOME/doctl/sandbox/creds`).
- Make sure the credential directory is actually created as this normally happens when `doctl sandbox install` is run, but that happens on the build host for snaps.
- Handle `ErrSandboxNotConnected` in both …
=> sandbox: Support running when installed as a Snap.

commands/functions.go, commands/functions_test.go, commands/sandbox.go, snap/local/doctl-launch, snap/snapcraft.yaml
We have several fixes to serverless (sandbox) support that were essentially bug fixes and were applied to `main` so they could go out as point releases.
As we are about to add to `feature/serverless` with changes that should _not_ immediately go out in releases, it would be helpful to have the branch up to date with main.
I realize there are other ways to do this (e.g, with a rebase) so, if that is the preferred method, please just close this, do the rebase, and let me know.   I don't believe I can do the change as a rebase because I won't have the permissions to force-push the result.
=> Bring feature/serverless in line with fixes applied to main

commands/activations.go, commands/functions.go, commands/sandbox-extra.go, commands/sandbox.go, commands/sandbox_test.go
The `doctl` command for developing and testing functions has historically been called `sandbox` but has the aliases `serverless` and `sls` as well as `sbx`.
This change inverts the primary command and full-word alias so that the command is now called `serverless` and `sandbox` becomes an alias.   The shorter aliases `sls` and `sbx` are retained.
The change also adjusts all of the help texts and error texts (all texts made visible at runtime) to avoid the term "sandbox" altogether.    This was not accompanied by a wholesale editing of purely internal uses (e.g. function names, variable names, comments): the term sandbox is still used there, and also for the directory name of the "hidden" area where the software is installed.
By avoiding the word "sandbox" certain concepts had to be given …
=> Rename sandbox to serverless

commands/displayers/functions.go, commands/functions.go, commands/functions_test.go, commands/sandbox.go, do/sandbox.go
This change substitutes the word `functions` for the word `actions` in several places commonly visited while using `doctl serverless`.
1.  The output of `doctl serverless functions list` has been redone using a `doctl` displayer so it no longer depends on the formatting done by the `aio` component of `nim`.
2.  Version 4.0 of `nim` is incorporated.   This brings several changes.
a.  In deploy operations, a `functions` object is accepted in lieu of an `actions` object (but `actions` is still accepted for backward compatibility).
b.  When `project.yml` is generated in `doctl serverless init`, the `functions` syntax is used rather than `actions`.   While this is not intended to be a breaking change (the deploy operation will accept the new syntax), it makes the public exposure of this change …
=> Change 'actions' to 'functions' in externals where feasible

commands/displayers/size.go, integration/size_list_test.go
The `/v2/sizes` response grew a description field awhile back. It would be useful to output that in doctl's list.
=> sizes: Output the description field.

.github/workflows/release.yml, .github/workflows/snapcraft-candidate.yml
Our workflows publishing snap packages seem to have stopped working 7 days ago.  It looks like it now installs a newer version of the `snapcraft` binary even though we are pinned to a specific release of the action.
```
Installing Snapcraft...
/usr/bin/sudo snap install --classic snapcraft
snapcraft 7.0.4 from Canonical* installed
```
The version of the action we are using is incompatible with the version of snapcraft it installs, leading to this failure:
```
--with is no longer supported, export the auth to the environment variable 'SNAPCRAFT_STORE_CREDENTIALS' instead                                               
Login successful                                                               
/snap/bin/snapcraft upload doctl_v1.76.2+git0e3d4cb9_amd64.snap --release candidate
This login …
```
=> Fix Snap publishing in workflows.

commands/activations.go, commands/command_config.go, commands/displayers/functions.go, commands/functions.go, commands/functions_test.go, commands/sandbox-extra.go, commands/sandbox.go, commands/sandbox_test.go, do/mocks/SandboxService.go, do/sandbox.go
The accumulated changes on feature/serverless are ready to be in a release, assuming the co-requisite docs changes become ready.   The changes are
1.  change cobra and help texts to de-emphasize ‘sandbox’ as a command and eliminate it as a concept
2. change 'actions' to 'functions' where feasible, including an improved  output format for `doctl sls fn list`
3.  interactions with the serverless backend now use a distinguished user agent string
4.  the mechanism for storing credentials now no longer goes through the sandbox plugin
=> Merge current feature/serverless contents preparatory to a release

dockerfiles/Dockerfile.snap, snap/snapcraft.yaml
When cutting the last release, I happened to notice that the Snap builds were still on Go 1.17. Of course things did not end up as straight forward as simply bumping the version string. Rebuilding the image using the Dockerfile in currently in main now creates an unusable image:
```
$ docker run sammytheshark/doctl-snap-base:latest
Traceback (most recent call last):
File "/snap/snapcraft/current/bin/snapcraft", line 5, in <module>
from snapcraft.cli import run
ModuleNotFoundError: No module named 'snapcraft'
```
So I've brought in a fix from the upstream Dockerfile this is based on. I also brought in a few small improvements that make the image smaller and the layers more cachable.
=> snap: Update build env to use go 1.18

commands/activations_test.go, commands/command_config.go, commands/commands_test.go, commands/functions_test.go, commands/sandbox.go, commands/sandbox_test.go, commands/sandbox_util.go, do/mocks/SandboxService.go, do/sandbox.go
The `SandboxService` is our abstraction of the serverless capabilities for mocking and testing purposes.  
The original version of this abstraction left out status checking and installation, leaving some serverless code paths to be abstracted directly in `CmdConfig`, outside the abstraction boundary.   We worked around this deviation for testing purposes, but it creates a conflict going forward because the service itself only partly separates serverless concerns from other concerns. 
Specifically, we are about to temporarily complicate the service, giving it a direct path to the functions backend cluster, as part of an effort to reduce dependence on the plugin for serverless capabilities (ultimately, it should get simplified again as serverless APIs are regularized, but this will take …
=> Refactor sandbox service for better encapsulation

commands/auth.go
Received a few pieces of feedback about how the `auth remove` command could be clearer. I've added an example of the command's use here.
=> auth remove example

commands/displayers/namespaces.go, commands/namespaces.go, commands/namespaces_test.go, commands/serverless.go, commands/serverless_test.go, do/mocks/ServerlessService.go, do/serverless.go
This change
1. adds the _hidden_ command `doctl serverless namespaces` (alias `ns`) 
2. adds the _hidden_ flag `--beta` to the `doctl serverless connect` command.   Alternative syntax and behavior for this command are enabled by the flag.
These changes enable the new multiple namespaces feature as it will be when released except that
1.  To use these features now requires that you be feature-flipped for `serverless_portal_public_api` .
2. When released, the `namespaces` command will no longer be hidden.
3. When released, the `--beta` flag will be dropped and the behavior guarded by it will become the default behavior.
New commands under `doctl serverless namespaces`:
```
create       Creates a namespace
delete       Deletes a namespace
list         Lists your namespaces
list-regions Lists …
```
=> Support multiple namespaces

go.mod, go.sum, vendor/github.com/containerd/continuity/AUTHORS, vendor/github.com/docker/cli/cli/config/configfile/file.go, vendor/github.com/docker/cli/cli/config/configfile/file_unix.go, vendor/github.com/docker/cli/cli/config/credentials/default_store_unsupported.go, vendor/modules.txt
This updates a number of  vendored dependencies to make WhiteSource (which seems to have changed its name to Mend?) happy. None of these CVEs impact us as we do not use any of the effected code paths. 
Fixes: https://github.com/digitalocean/doctl/issues/1196, https://github.com/digitalocean/doctl/issues/1164, https://github.com/digitalocean/doctl/issues/1139
=> Update vendored dependencies.

commands/databases.go
This adds mentions mongodb in help text where appropriate.  Also, PostgreSQL version 11 is used as an example in a few places. It's still offered, but the control panel defaults to version 14. So I updated those as well.
=> databases: Mention mongodb in help text.

do/serverless.go
Properly speaking, the ListNamespaces API should return only self-managed namespaces, not AP-managed namespaces.   latter should not be modified except via AP.   Currently, the API does appear to return AP-managed namespaces.   As a short-term fix, this change does this filtering in doctl code.
=> Filter AP namespaces from all ListNamespaces responses

commands/databases.go, commands/databases_test.go, commands/displayers/database.go, do/databases.go, do/mocks/DatabasesService.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/balance.go, vendor/github.com/digitalocean/godo/billing_history.go, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
**What**
Supports fetching database options for the following dimensions:
- engines
- regions
- versions
- layouts (node counts + available slugs)
**Why**
Support for this was added on the [public openapi docs](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_list_options). Being able to interact with this via `doctl` will enable discovery of available database options when users consider creating a cluster
=> Add support for listing database options

do/serverless.go
Historically, we have not incorporated a `package.json` file in the serverless plugin.   There is a copy of `nodejs`, a primary javascript source file, and a `node_modules` directory which is almost always enough to get a valid execution.
However, `nodejs` will start by looking for, and optionally reading, `package.json`.   If it is not there, it goes up the parent directory hierarchy until it finds one and reads that.  The result is harmless if there is none or if there is a valid one (the results don't end up getting used in our case).   However, if there is an _invalid_ one in a parent directory, the serverless plugin will fail to initialize with a hopelessly confusing error.
This has only been reported by a user once, but once is enough.  This change includes the purely defensive …
=> Incorporate package.json in serverless plugin

commands/databases.go, commands/databases_test.go
The DO API allows DB pools to be created without a user specified. This PR modifies the  `databases pool` options and removes user as a required field. Without user specified, pool uses the connection credentials of the inbound user.
example usage:
```bash
doctl databases pool create $DB_UUID p-04 --db defaultdb --size 2 -t $DIGITALOCEAN_TOKEN
```
```
User    Name    Size    Database     Mode           URI                                                                                                                           
p-04    2       defaultdb    transaction    postgresql://:@${HOST}/p-04?sslmode=require
```
=> Set user as optional field in calls to databases pool

Dockerfile
**Why**
The instructions presented in [Building with Docker](https://github.com/digitalocean/doctl#building-with-docker) are no longer possible, `doctl` requires go v1.18. See below:
```
docker build . --tag=doctl . 
[+] Building 44.5s (16/18)
=> [internal] load build definition from Dockerfile
...
#16 13.94 ../../commands/displayers/functions.go:58:16: undefined: time.UnixMilli
#16 13.94 note: module requires Go 1.18
#16 23.31 make: *** [Makefile:48: _build] Error 2
------
executor failed running [/bin/sh -c cd /go/src/[github.com/digitalocean/doctl](http://github.com/digitalocean/doctl) &&     make build GOARCH=$GOARCH]: exit code: 2
```
To keep `doctl` usable with just Docker, this PR bumps the Dockerfile from `golang:1.16-alpine` to `golang:1.18-alpine`
**Result**
Able to build, run, …
=> bump dockerfile version 1.16 -> 1.18

args.go, commands/apps_dev.go, commands/apps_dev_config.go, commands/apps_dev_config_test.go
* Adds `doctl app dev config set|unset` for local build configuration
* Adds `appDevConfig` struct which simplifies working across the `dev config` and the default `doctl falgs`
=> Add support for an app dev config and management

args.go, commands/apps_dev.go, commands/apps_dev_config.go, internal/apps/builder/builder.go, internal/apps/builder/cnb.go, internal/apps/builder/cnb_test.go, internal/apps/builder/docker.go
* Adds support for overriding the `build_command` for cnb builds
=> Add support for build command overrides

commands/apps_dev.go, commands/apps_dev_config.go, commands/apps_dev_test.go, commands/commands_test.go, doit.go, internal/apps/builder/builder.go, internal/apps/builder/builder_mock.go, internal/apps/builder/builder_test.go, internal/apps/builder/cnb.go, internal/apps/builder/cnb_test.go, internal/apps/builder/container.go, internal/apps/builder/container_mock.go, internal/apps/builder/docker_test.go
* Adds copy-on-write semantics to CNB builds
* `forced` to `true` for now because I don't see a reason users would want local CNB build artifacts but it is passed in as an option to be configureable later on
* Rename `ContainerEngineClient` interface to `DockerEngineClient` interface because contracts have docker cli specific types
=> Add copy on write support for CNB builds

commands/apps_dev.go, snap/snapcraft.yaml
Adds `app-dev-build` plug w/ the `docker` interface
> This will require the user to have docker installed via snap and execute `snap connect doctl:app-dev-build docker:docker-daemon` to grant permissions
=> Add snap support for docker interface for app dev builds

commands/serverless.go, snap/snapcraft.yaml
The snap builds have failed after the serverless refactor as the command now requires doctl to be configured with an API token. 
https://github.com/digitalocean/doctl/runs/8207250662?check_suite_focus=true#step:4:610
This change allows us to by pass that requirement if `SNAP_SANDBOX_INSTALL` is  set.
=> serverless: work-a-round for installing in snap build.

commands/serverless.go, do/serverless.go
The set of supported languages in DigitalOcean Functions actually includes TypeScript.   TypeScript does not require its own runtime but is supported by setting up the function project correctly to run in one of the `nodejs` runtimes.
This change (1) corrects the "languages" display (which is actually organized by runtime) to stop assuming there will eventually be a TypeScript runtime but rather correctly indicating that TypeScript is supported in the `nodejs` runtime.
(2) It also incorporates a later version of the serverless plugin which knows how to properly set up a functions project for Typescript and correctly associates the `.ts` file suffix with the `nodejs` runtime.
=> Add support for typescript in the nodejs runtime

commands/namespaces.go, commands/serverless.go, commands/serverless_test.go, do/serverless.go
This change unhides the support for multiple namespaces.
It should probably not be merged until feature flippers are opened to make the capability available to all (it is still in beta as of now).
The change also fixes a bug in error returns from serverless functions get.
=> Unhide the multiple namespaces feature

commands/serverless-extra.go, commands/serverless.go
In the run-up to `doctl` release 1.80 I neglected to amend the help text for `doctl serverless connect` to properly reflect what is now possible with multiple namespaces. Since this capability was hidden during the beta, the text did not get amended earlier.
In amending that text, I also touched on a few other help texts as I will note in comments.
=>  Improve help texts taking into account multiple namespaces

go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
Bump godo to v1.86.0 to support DOCR push to deploy for app platform.
=> Bump godo to v1.86.0

commands/apps_dev.go, internal/apps/workspace/workspace.go
Accepting an app spec via `stdin` does not play well with the `Interactivity` config. Rather than implicitly disable interactivity in that scenario we are removing support for `stdin` to `app dev build --spec=-`; users can still load arbitrary specs with a path based syntax.
=> disable stdin from `app dev build` command

commands/command_config.go, commands/displayers/triggers.go, commands/serverless.go, commands/serverless_test.go, commands/serverless_util.go, commands/triggers.go, commands/triggers_test.go, do/mocks/ServerlessService.go, do/serverless.go
This PR adds support (still hidden) for a future release of `doctl serverless` that includes support for scheduled functions.   Concretely, it supports triggers, associated with functions, where the trigger has a `cron` expression governing when the function is invoked.
Support consists of the following:
1.  In `doctl sls deploy`, if the `project.yml` contains a `triggers` object nested in a function object, the triggers are deployed, associated with the function.   This is accomplished by adopting the latest serverless plugin version, which incorporates the latest deployer version.
2. In `doctl sls undeploy`, if there are triggers associated with any functions that are being undeployed, they are undeployed as well.   There is also a new flag, `--triggers` (currently hidden) which allows …
=> Add doctl serverless trigger support (for scheduled functions)

commands/functions.go, commands/functions_test.go, commands/serverless.go, commands/serverless_test.go, do/mocks/ServerlessService.go, do/serverless.go
This change covers internal improvements not intended to be visible to typical `doctl` users.
1. Toward the goal of reducing the separate plugin for serverless:
1.  Remove dependence on the plugin for `doctl sls fn list`
2. Remove dependence on the plugin for `doctl sls status`
2.  Adds a (permanently) hidden pair of flags to `doctl sls connect` permitting connection to serverless clusters that are not in production (and hence unknown to the serverless portal).   This is needed to support internal testing and debugging use cases for which we currently use the `nim` CLI (which should be phased out).
=> Finish eliminating plugin usage in 'doctl sls functions' + testing improvements

do/serverless.go
The current `doctl` release uses `nim` 4.2.6, which has two known problems affecting `doctl sls undeploy` operations.
1.  If a user is not in the scheduled functions beta, an `undeploy` operation will nevertheless try to find any triggers that need to be undeployed.  In the process of doing so, it wiIl fail (because the triggers API is blocked) and so there will be a visible (somewhat cryptic) error and a non-zero exit code.  In fact, the `undeploy` operation as requested has actually succeeded (fixed in 4.2.8).
2. In the unlikely event of a failure in the middle of an undeploy operation, triggers can be left even though their function has been removed (fixed in 4.2.7).
This change simply increments the `nim` version to 4.2.8 to pick of fixes for these issues.
=> Fix possible failures in undeploy

commands/activations.go, commands/apps.go, commands/commands_test.go, commands/domains.go, commands/functions.go, commands/images.go, commands/monitoring.go, commands/namespaces.go, commands/snapshots.go, commands/sshkeys.go, commands/tags.go, commands/triggers.go, commands/volumes.go
This pull request
- Adds missing `ls` and `rm` aliases to their respective `list` and `delete` subcommands
- Changes the alias order of `doctl compute volume delete` to `d, rw` in order to be consistent with other `delete` alias uses
- Adds the test suggested in the linked issue in order to ensure any future `list` and `remove`  sub-commands have the expected aliases.
Fixes https://github.com/digitalocean/doctl/issues/1262
Please let me know if I missed any aliases!
@andrewsomething
=> commands: Consistent aliases for "list" and "delete"

commands/load_balancers.go, integration/lb_create_test.go
Adds `--wait` flag to the doctl compute load-balancer create command. 
It polls the [/v2/load_balancers/$LOAD_BALANCER_ID endpoint](https://docs.digitalocean.com/reference/api/api-reference/#operation/loadBalancers_get), blocking until the load balancer's status attribute moves from new to active.
Closes #1264 
Feature enhancement.
=> Add --wait flag to load_balancer create

commands/activations.go, commands/activations_test.go, commands/functions_test.go, do/mocks/ServerlessService.go, do/serverless.go
This change alters the logic for `doctl sls actv get` and `doctl sls actv result` to use the OpenWhisk API directly rather than using the plugin.   The `list` and `logs` commands are still using the plugin (to be addressed in a future PR).
=> Avoid plugin in serverless activations [ get | result ]

commands/apps_dev.go, commands/auth_test.go, commands/doit.go
The `flagName` method that is used when [binding flags to viper](https://github.com/digitalocean/doctl/blob/de1918ad1ee4b1e523c335fa9254e85d415d18aa/commands/doit.go#L221-L230) only supports  nesting a setting three levels deep.
https://github.com/digitalocean/doctl/blob/de1918ad1ee4b1e523c335fa9254e85d415d18aa/commands/doit.go#L287-L292
This causes issues for some deeply nested commands. This is particularly problematic for the `doctl apps dev config set/unset` commands which contain `--dev-config` flag. The resulting setting for it is `config.set.dev-config` which conflicts with the top level `config` setting that should be a string. 
When Viper is init-ed, there is a race to register the setting. Sometimes, it results in the config file containing:
```
config:
set:
dev-config: ""
``` …
=> apps: Nest dev-config settings under 'dev'

commands/activations_test.go, commands/functions_test.go, commands/namespaces.go, commands/namespaces_test.go, commands/serverless.go, commands/serverless_test.go, commands/serverless_util.go, do/mocks/ServerlessService.go, do/serverless.go
As reported in issue #1284, it is possible for `serverless connect` to work but subsequent commands to report "not connected".   This only happens when `doctl` is installed via `snap` and only in some system configurations (most seem to work, which is why this has not been noticed before).
There is clearly a snap-specific bug in the handling of the credentials directory.   The type `serverlessService` contains two fields, `serverlessDir` which represents where the plugin is installed, and `credsDir` which represents where credentials should be stored.   Except under `snap`, these are the same, but for `snap` installs they are different.    The fields are initialized correctly.   They are also used correctly in _some_ places but, sadly, not _all_ places.   In particular, the status check …
=> Fix bugs in credentials directory management and connection checking

README.md
I *think* that https://archlinux.org/packages/community/x86_64/doctl/
is part of the official Arch Linux repository, so it's not necessary
to link to it separately.
Fixes #1291
=> Remove broken link to AUR package

commands/serverless.go, commands/serverless_test.go, do/mocks/ServerlessService.go, do/serverless.go
Implements `doctl sls undeploy` subtree in goland instead of using the nim plugin.
=> Implement sls undeploy in native golang

commands/droplets.go
Looks like I missed a mention of region being required in the Droplet create description when doing https://github.com/digitalocean/doctl/pull/1234
=> droplet: Remove mention of region being required.

args.go, commands/apps.go, commands/apps_dev.go, commands/apps_test.go, do/apps.go, do/mocks/AppsService.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/droplet_actions.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
Specifically, I'm adding support for project ids in two places:
* `doctl apps create` can now take in a `--project-id` parameter. This parameter will be used to assign the created app and resources to the project you specified!
* `doctl apps list` can now take a `--with-projects` flag. Adding this flag will make the `project_id` field populate on each app.
This also bumps the godo version to 1.89
=> Add more support for project_id in doctl

commands/serverless-extra.go, commands/serverless_test.go, do/serverless.go
The purpose of this change is to make the incorporated serverless plugin smaller and simpler to maintain.  Customers will notice no change, since a plugin still has to be installed to support the `deploy`, `get-metadata`, and `watch` commands.  The download time for the plugin, already not too bad, is not that much improved since it is dominated by the size of the `node` binary.   However, from a long-term code maintenance standpoint the change should be a win.
This change goes along with a corresponding change in the plugin repo:
digitalocean/doctl-sandbox-plugin#6.   Most of the important changes are there.  The present change increments the plugin minimum version and makes a few other minor adjustments.
=> Use the smaller deployer-only plugin instead of the original one

commands/serverless.go, do/mocks/ServerlessService.go, do/serverless.go
A corollary to recent efforts to reduce dependence on the serverless plugin:  we are also trying to eliminate internal usages of `nim` in our own development processes, replacing it with `doctl`.   In order for that to work, `doctl` needs some enhancements to work with serverless backend clusters that are not in production (and hence not (yet) known to the portal).
The changes are all in the area of credential management.    Basically, they allow both setting and interrogating credentials via their low-level OpenWhisk characteristics without using the namespace APIs.
Only those commands whose `nim` equivalents are actually used in this way have been changed.   The additional flags are all hidden, since this low-level credential manipulation is not something DigitalOcean customers would …
=> changes to support usage in serverless backend development

commands/serverless-extra.go, do/serverless.go
1. Improvement to poll loop behavior when waiting for remote builds.
2. Propagate DO API token to remote builds so trigger deploys work.
3. Make --remote-build the default when running as a snap.
The first two of these are actually changes to the functions deployer component and are brought in by incrementing the `minServerlessVersion`.
=> Minor fixes to serverless deploy

commands/kubernetes.go, integration/kubernetes_clusters_list_test.go
By default, the `kubernetes cluster list` command displays a short layout. When using the format flag to specify output that is not in the default display, we need access to the full version.
Fixes: https://github.com/digitalocean/doctl/issues/1306
For more context see: 
https://github.com/digitalocean/doctl/blob/53e2a26d8486aa510f1b202c0c91bf576baa668b/commands/kubernetes.go#L2088-L2089
https://github.com/digitalocean/doctl/blob/53e2a26d8486aa510f1b202c0c91bf576baa668b/commands/displayers/kubernetes.go#L53-L82
=> k8s list: Support formating with non-default columns.

do/serverless.go
The fix is in deployer version 5.0.16
=> Fix bug: web=false was ignored on remote build

commands/triggers.go, commands/triggers_test.go
This changes the triggers get sub-command to use the displayer rather than marshaling JSON itself. By default, it will use the table display and the output flag is supported for JSON. It also sets the displayer type so that the `--format` flag is now supported.
=> function triggers: Use displayer for get sub-command and set displayer type.

commands/serverless.go, commands/serverless_test.go, do/serverless.go
Up until now, the output of `doctl sls connect` included the label but the output of `doctl sls status` did not.   The reason was that the label was not stored locally and so an additional protocol handshake would be needed to obtain it.  
This change makes the status message more similar to the connect message by including the label in the stored credentials so it is available on the same basis as other relevant information about the namespace, then using common code to format the output message in both cases.
It would arguably be possible to go further with this change, making the label more prominent (and the generated id less prominent) in the message.   I did not do this because a major change in the format of these output messages could break some scripts.  I do not think we commit …
=> Include label in credentials store and status msg

commands/activations.go, commands/functions.go, commands/namespaces.go, commands/triggers.go
This change simply adds aliases, allowing the singular words `activation`, `function`, `namespace` and `trigger` to be used for their plural counterparts.
=> add "singular" aliases for "plural" serverless commands

do/mocks/ServerlessService.go, do/serverless.go
In PR #1297, the `doctl sls undeploy` command was re-implemented in pure golang.  This change appears in release 1.85.0 and beyond.
There was an omission from the rewrite.  After deleting all the functions of the namespace, the (now-empty) packages that contained some of those functions should also be deleted.   This change restores that behavior.
This should not be considered a critical bug.  As far as I know, no customer has complained about it.  For the most part, the management of packages is done by the functions deployer in a transparent fashion (created on demand, used if present) and empty packages are not very likely to cause semantic problems.   However, 
1.  the contract to remove "all" resources from the namespace is violated unless we remove packages because packages are …
=> Delete packages when cleaning a namespace via 'undeploy --all'

commands/serverless-extra.go, commands/serverless.go, do/serverless.go
This allows `doctl serverless get-metadata` to execute without a valid DO API token (or any OpenWhisk credentials).   It doesn't need these things because it's a purely file-system local operation and does not use any remote APIs.
The idea is to support this operation in contexts where a DO API token is not available, such as the App Platform detection phase.
Note that the plugin has to get installed somehow.    To support installing without the need for a DO API token, this PR also supports a special flag for installing in container images:
```
DOCKER_SANDBOX_INSTALL=true doctl serverless install
```
This basically reuses support already in place for snap installs.   IMO it would not be a good idea to make _all_ installs run without credentials.   It's not a security problem, but, in the …
=> Allow container image installs and 'doctl sls get-metadata' to run without credentials

commands/auth.go
Token shouldn't be output in cleartext.
=> commands/auth: stop printing the token to stdout

commands/displayers/activations.go
This fixes an issue with `activation list` where all activations were categorized as `warm` (incorrectly). The annotation is called `initTime` (not `init`) and if it is only present when the activation is `cold` so a `nil` result fetching the activation implies a warm start.
Now the output is correctly formatted.
```
01/13 02:52:47    success            python:3.9    0.0.3      44386f88573a4287b86f88573a128774    warm     39      507ms       f
01/13 02:52:45    success            python:3.9    0.0.3      5d6cd4e61b2d4c67acd4e61b2d6c677b    warm     42      515ms       f
01/13 02:50:47    success            python:3.9    0.0.3      e0a5156653e244c6a5156653e214c606    cold     1072    942ms       f
01/13 01:50:19    developer error    python:3.9    0.0.2 …
```
=> Fix warm/cold start categorization.

do/serverless.go
Current behavior causes the `project.yml`  to have  invalid property `websecure` instead of `webSecure`
=> Fixes how webSecure project property gets marshaled to yaml

commands/serverless.go, commands/serverless_test.go
Updates error message to point at the actual command.
```
$ doctl serverless connect
Error: you must create a namespace with `doctl namespace create`, specifying a region and label
$ doctl namespace create
Error: unknown command "namespace" for "doctl"
Run 'doctl --help' for usage.
$ doctl serverless namespace create -h
`Use `doctl serverless namespaces create` to create a new functions namespace.
Both a region and a label must be specified.
Usage:
doctl serverless namespaces create [flags]
Flags:
-h, --help            help for create
-l, --label string    the label for the namespace (required)
-n, --no-connect      don't immediately connect to the created namespace
-r, --region string   the region for the namespace (required)
Global Flags:
-t, --access-token string   API V2 access token …
```
=> serverless: fix hint for creating functions namespace.

.do/.gitignore, args.go, commands/databases.go, commands/databases_test.go, integration/database_create_backup_test.go, integration/database_create_restore_from_cluster.go
Adds the following command:
`doctl db create new_db_name --restore-from-cluster=original-cluster-name —engine="pg1" —num_nodes=100 —seize=biggest —region="nyc3"`
Note: This does not mimic the control panel behavior. This is parity to the API. To mimic the control panel behavior, we'd do something more like this:
`doctl databases fork new_db_name --restore-from-cluster=original-cluster-name`
which will be in another PR.
=> APICLI-1692: Add backup-restore functionality to db create

commands/apps.go, go.mod, go.sum, integration/apps_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
This PR fixes a potential race which can occur when using the --wait flag on the App Platform create and update operations.  Previously, the wait logic would list deployments to determine the deployment to track. In some cases the wrong deployment would be selected and the --wait would block indefinitely.
APPS-6813
=> App Platform: fix race on Create/Update --wait flag

args.go, commands/databases.go, commands/databases_test.go, integration/database_create_fork_test.go
Add the following to doctl:
`doctl databases fork new_db_name --restore-from-cluster-id=original-cluster-id`
This is similar behavior to the control panel experience. We retrieve the db details and pass them in to the database create request for the user. 
Addresses #992 
APICLI-1856
=> databases: add "fork" feature

commands/auth.go, commands/auth_test.go, commands/command_config.go, commands/doit.go
**Background**
We've had several requests report that they are seeing a discrepancy in doctl authentication. When they create a context with an uppercase letter, the context name is stored in all lowercase and causes the following:
- When the context is used in uppercase, doctl accepts it but doesn't allow the authentication.
- When the context is used in lowercase, doctl accepts it and allows the authentication.
Currently, this is what happens:
```
$ doctl auth init --context Chandan
Please authenticate doctl for use with your DigitalOcean account. You can generate a token in the control panel at https://cloud.digitalocean.com/account/api/tokens
Enter your access token: 
Validating token... OK
$ doctl auth ls
chandan
default (current)
$ doctl auth switch --context Chandan
Now using …
```
=> Auth "init", "switch", "remove" Forces Lowercase

commands/version.go, doit.go, doit_test.go
Updates the `version` command to respect the `-o json` flag. Opening as a draft since this is missing a test and the output is ugly.
Example output:
``` 
$ go run cmd/doctl/main.go version -o json
{
"version": "doctl version 0.0.0-dev",
"notification": "release 1.94.0 is available, check it out!"
}
```
=> doit: respect json output flag

doit.go, doit_test.go
Relates to #1376 (forgot to add this before merging 🤦‍♂️ )
Adds a field for `latestRelease` in the `doct version -o json` output. I chose `latestRelease` over `latestTag` since we're pulling this info from the releases API endpoint.
=> doit: include latest release in version json

commands/databases.go
In the command to create a database, there's an error that we're currently ignoring. If that err is not nil and the next line runs that tries to access a field on a nil database, doctl will panic. This PR checks that error, which will prevent the panic.
=> databases: prevent potential panic on db create

commands/databases.go
Previously, the docs for `replica promote` was the same as that of `replica delete`. This was probably from a copy-paste error. This change fixes that, and updates the command alias so that it's not also `rm` (it's now `p`).
Not sure how I feel about the `p` alias, so if you have any ideas on a better one, let me know and I can change it.
=> databases: fix replica promote doc string

commands/displayers/account.go, integration/account_test.go
A bit of an edge case that most users will never run into, but calling `doctl account get` using a user context token panics:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0ad1a]
goroutine 1 [running]:
github.com/digitalocean/doctl/commands/displayers.(*Account).KV(0xc0002d00b8)
/home/runner/work/doctl/doctl/commands/displayers/account.go:49 +0x23a
github.com/digitalocean/doctl/commands/displayers.DisplayText({0x12b0c38, 0xc0002d00b8}, {0x12a7040, 0xc0001a0008}, 0x0, {0x0, 0x0, 0x2?})
/home/runner/work/doctl/doctl/commands/displayers/output.go:91 +0x34b
github.com/digitalocean/doctl/commands/displayers.(*Displayer).Display(0xc00078fc50)
/home/runner/work/doctl/doctl/commands/displayers/output.go:6 …
```
=> account: protect against panic in user context.

commands/command.go
I think the triple backtick that I changed is the reason that [this page](https://docs.digitalocean.com/reference/doctl/reference/compute/droplet/create/) has this content:
=> Fix typo causing incorrect token highlighting

commands/cdns.go, commands/databases.go
=> docs: typo fix on comments

commands/account.go, commands/account_test.go, commands/command_config.go, commands/doit.go, doit.go, integration/account_test.go, integration/projects_delete_test.go, integration/retry_flag_test.go
This enables support for retrying failed requests. A few things to note:
- I've chosen to expose the `http-retry-max` flag to users to give them insight into the new default behavior. I've marked the `http-retry-wait-max` and `http-retry-wait-min` flags as hidden as the defaults should be fine for most users, but it still allows for configuration if needed.
- For the wait settings, I've used an `int` rather than a `float64` as I feel that it is friendlier on the command line.
- I've used the `http` prefix on these so that the environment variables end up consistent with the same settings ion Terraform, e.g. `DIGITALOCEAN_HTTP_RETRY_MAX`.
- I've bypassed retries for the `doctl account ratelimit` command. The purpose of the command is to return the rate-limit headers regardless of response …
=> Add support for retrying failed requests.

commands/load_balancers.go
While reviewing another load balancer create command change, I noticed a few small opportunities for improvements:
- Change miss-named variable`cmdRecordCreate` to `cmdLoadBalancerCreate` (seems like an old copy & paste error)
- Add `lb` as aliase for `load-balancer` for better cli ergonomics.
- Improve description of `--tag` flag.
=> Miscellaneous load balancer create command improvements

commands/databases.go, commands/databases_test.go, integration/database_create_test.go
We're missing support setting tags when creating a database cluster. This adds it.
=> databases: Support setting tags a create time.

args.go, commands/databases.go, commands/databases_test.go, do/databases.go, do/mocks/DatabasesService.go, integration/database_connection_test.go
While doing https://github.com/digitalocean/doctl/pull/1411, I noticed another database feature we do not support well. Database clusters now return connection details for both their public hostnames and private hostnames only accessible via VPC. This adds a `--private` flag to the existing `databases connection` command that will return the private connection details instead of the public ones when passed.
=> databases: Support displaying private connection.

doit_test.go
This PR simplifies tests.
From the [doc](https://pkg.go.dev/testing#T.Setenv):
> Setenv calls os.Setenv(key, value) and uses Cleanup to restore the environment variable to its original value after the test.
=> doit: simplify tests by using t.Setenv

commands/apps_test.go, commands/auth_test.go, commands/monitoring_test.go, commands/registry_test.go
This PR fixes the commands test. It reverses passed parameters to the [assert.Equal](https://pkg.go.dev/github.com/stretchr/testify@v1.8.0/assert#Equal) according to the signature (`actual` after `expected`):
```
func Equal(t TestingT), expected, actual interface{}, msgAndArgs ...interface{}) bool
```
Additionally, the PR replaces `assert.Error(t, test.err, err)` with `assert.Equal(t, test.err, err)`.
=> commands: fix test asserts

.github/workflows/release.yml, .github/workflows/snapcraft-candidate.yml
Closes #1420 
Update `.github/workflows/stack-ci.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
find doctl_v*.snap -print -exec echo ::set-output name=snap::{} \;
```
**TO-BE**
```yaml
find doctl_v*.snap -exec echo "snap={}" >> $GITHUB_OUTPUT \;
```
=> Replace deprecated command with environment file

CHANGELOG.md, commands/charm/confirm/confirm.go, commands/databases.go, commands/namespaces.go, commands/projects.go, commands/serverless.go, commands/serverless_samples.go, commands/ssh_test.go, do/serverless.go, internal/apps/builder/builder.go, pkg/extract/extract_test.go
This PR fixes spelling mistakes and removes duplicated words.
=> Fix typos in command descriptions, comments, and tests

do/registry.go
This PR fixes possible resource leaks by adding a statement that closes a response body.
From the [documentation](https://pkg.go.dev/net/http):
> The caller must close the response body when finished with it
Also, see this [article](https://golang50shad.es/index.html#close_http_resp_body) for a deep dive into the problem.
=> Add missing closing response body

commands/monitoring.go
Expanding on `doctl monitoring alert -h` docs to mitigate confusion between `doctl monitoring alert` and `doctl monitoring uptime alert`
=> Alerts: Expand on Monitoring Alerts Doc

commands/billing_history_test.go, commands/registry.go, commands/registry_test.go
This PR replaces deprecated functions `godo.Int, godo.String` with `godo.PtrTo`.
=> commands: Use godo.PtrTo instead of deprecated godo.Int, godo.String

commands/firewalls.go, commands/kubernetes.go, commands/projects.go
This PR corrects spelling mistakes in command descriptions.
=> commands: Fix typos in descriptions

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/snapcraft-candidate.yml
The latest versions are:
- [checkout@v4](https://github.com/marketplace/actions/checkout)
- [setup-go@v4](https://github.com/marketplace/actions/setup-go-environment)
- [docker/login-action@v3](https://github.com/marketplace/actions/docker-login)
- [goreleaser/goreleaser-action@v5](https://github.com/marketplace/actions/goreleaser-action)
Restore cache is not needed because [setup-go@v4 ](https://github.com/marketplace/actions/setup-go-environment#v4)has caching enabled by default.
=> Bump GitHub actions; enable dependabot for github-actions

commands/activations_test.go, commands/kubernetes.go
This PR refactors code to use `strconv.Atoi` instead of `strconv.ParseInt`+`int` type casting.
=> commands: strconv.Atoi instead of strconv.ParseInt for ints

commands/displayers/domain.go, commands/domains.go, integration/domain_records_list_test.go
Domain records can have `flags` and `tag` attributes. We do not currently display those in command output. The adds support for optionally displaying those fields using the `--format` flag as needed.
Fixes: https://github.com/digitalocean/doctl/issues/1436
=> domain records: Support displaying flags and tag.

args.go, commands/databases.go, commands/databases_test.go, commands/displayers/database.go
**What**
- Adds the ability to provide `--storage-size-mib` when doing CreateCluster or ResizeCluster operations on a database
- Includes the StorageSizeMib as a column in the databases display output
=> Support scalable storage for PostgreSQL/MySQL databases

integration/database_connection_test.go, integration/database_create_restore_from_cluster.go, integration/database_create_test.go, integration/monitoring_test.go
I realized that we had accidentally committed  an integration test with `suite.Focus`. This means it was the only integration test that was being run. :disappointed:  This PR removes the `suite.Focus` usage and updates some database tests to reflect recent changes.
Additionally, it skips two tests (`monitoring/alerts/create` and `monitoring/alerts/update`). They are currently failing due to a deeper issue that will take more time to resolve.
=> Re-enable integration tests.

commands/apps_dev.go, internal/apps/builder/cnb.go
[APPS-7962](https://do-internal.atlassian.net/browse/APPS-7962 )
This change updates the CNB builder image to our latest for apps that use Ubuntu-18 and Ubuntu-22 for local builds.
[APPS-7962]: https://do-internal.atlassian.net/browse/APPS-7962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> APP-Platform: Update CNB builder image

commands/certificates.go
Clarifies doc strings for Certificates and adds examples to each command.
=> Docs Audit: Certificates

commands/cdns.go
Clarifies docs strings for CDNs and adds examples for each command.
=> Docs Audit: CDNs

.github/workflows/ci.yml, Makefile, scripts/check_focused_test.sh
This helps to prevent merging branches with tests that have been marked `Focused`. Marking a test `Focused` can be useful in development, but allowing a test to be checked in to main while focused means other tests are not actually run in CI.
=> Add check to prevent focused tests being committed.

commands/apps_test.go, commands/displayers/apps.go, integration/apps_test.go
Address  #1460 
Adding "Phase" to `apps get-deployment` display so users know if deployment is still in progress, cancelled, or finished etc. Currently there's only a "Progress" display but, for example, a progress field with "6/7" could mean a lot of things (i.e. is the deployment still in progress? is it cancelled and stoped at 6th step? etc.) 
Before:
```
% doctl apps get-deployment 3785-4bc2  e652-401c-8794
ID                                      Cause               Progress    Created At                       Updated At
e652-401c-8794    app spec updated    6/7         2023-09-12 13:49:39 +0000 UTC    2023-09-12 13:49:50 +0000 UTC
```
After:
```
go run cmd/doctl/main.go  apps get-deployment 3785-4bc2  e652-401c-8794
ID                                      Cause               Progress …
```
=> Apps: Display "phase" for apps get-deployments

internal/apps/builder/cnb.go
App Platform's default build image in the Online Service is `CNBBuilderImage_Heroku18`. This change makes `CNBBuilderImage_Heroku22` the default to bring parity to local dev tooling.
=> apps: Set default apps dev build image to `CNBBuilderImage_Heroku22`.

internal/apps/builder/cnb.go
This PR updates CNBBuilderImage tag to `v0.64.0` (current stable version)
This fixes the following error:
```
ERROR: failed to export: get run image top layer SHA: image "<image-0>" has no layers
```
=> Update tag for CNBBuilderImage

commands/invoices.go
Updates and clarifies doc strings for Invoice command. Additionally, this adds examples for each of those commands.
=> Docs Audit: Invoices

commands/image_actions.go, commands/images.go
Updates and clarifies the doc strings for the `image` and `image-action` commands. This also adds examples for each command.
=> Docs audit: Images and Image Actions

commands/droplets.go
Updates and clarifies doc strings for Droplet commands. This also provides examples for each command.
=> Docs audit: Droplets

commands/monitoring.go, commands/uptime_alerts.go, commands/uptime_checks.go
Clarifies doc strings for Monitoring related commands and adds examples for each one.
=> Docs audit: Monitoring

args.go, commands/ssh.go, doit.go, pkg/ssh/ssh.go, testscript.sh
A work around for #1003
Passing in the `--wait` flag for `doctl compute droplet create` will return to user before the droplet is ready to accept ssh connections. This PR adds a `--ssh-retry-max` flag for `doctl compute ssh` command to retry for a successful connection to the droplet a certain amount of times before returning to user:
An example of what a CI script would look like:
```
#!/bin/bash
DROPLET_ID=$(go run cmd/doctl/main.go compute droplet create --image ubuntu-20-04-x64 --size s-1vcpu-1gb --region nyc1 wb2 --ssh-keys 40563907 --wait -o json | jq '.[] | .id')
go run cmd/doctl/main.go compute ssh $DROPLET_ID --ssh-retry-max 15  
doctl compute droplet delete $DROPLET_ID
```
=> ssh: add retries

commands/load_balancers.go, commands/load_balancers_test.go, doit.go
Currently, when you pass an empty value to the the load balancer allow/deny rules flag we are not updating the LB firewall rules. To match the behavior of our public API we should allow an empty flag allow/deny rules flag to remove the firewall rules from the LB.
At current passing an empty flag does not populates the LB firewall field. We should be separating the behavior of the allow/deny rules flag not being specified and the flag being specified but empty
This change allows an empty value in the fw rules flags to update the LB firewall to empty.
When not specifying the fw rules flags the LB firewall will not be updated.
=> LBAAS-2899: doctl not removing LB firewall rules on update

commands/regions.go, commands/sizes.go
This updates the doc string for the region and size commands, and adds an example for each.
=> Docs audit: Regions and Sizes

commands/reserved_ip_actions.go, commands/reserved_ips.go
Updates and clarifies doc strings for Reserved IP and Reserved IP Action commands. Also add examples for each command.
=> Docs audit: Reserved IPs

commands/snapshots.go
Updates and clarifies doc strings for Snapshot commands. Also add examples for each command.
=> Docs audit: Snapshots

commands/volume_actions.go, commands/volumes.go
Updates and clarifies doc strings for the Volume and Volume Actions commands. Also add examples for each command.
=> Docs audit: Volumes and Volume Actions

commands/droplets.go, commands/droplets_test.go, integration/droplet_create_test.go
Fixes #630
Adds a new optional flag to the `doctl compute droplet create` command, `--project-id`, that allows you to pass a project UUID. If a project UUID is passed, that Droplet will be assigned to that project after it is created.
This pattern of create-then-assign can probably be expanded to any resource that returns an URN, but since we've received quite a few requests for this functionality for Droplets, I figured this is a good starting point.
=> droplet create: assign to project after create

commands/command_config.go, commands/droplets.go
This refactors how we move created resources to projects to make it generic-ish. As long as the resource implements the `URN()` method, we can use a helper that performs the assign resources call.
This is not quite ideal due to how the commands are architected. Because we double-wrap the raw godo resources (first in a wrapper struct, then in the type alias for a slice of those wrapped structs), Go's type system isn't able to recognize those slices as implementing a slice of `urner` interfaces. What it can do though, is recognize each individual element of those slices as implementing the `urner` interface, so the method I created will only accept a single `urner`, despite the call to assign resources accepting a slice of URNs.
I think the tradeoff is worth it, since each command that can …
=> droplets: refactor how to assign resources

commands/images.go
In an unrelated issue, it was pointed out that the help for the images commands claims that we return more detail about images than we really do.
```
$ doctl compute image ls | head -n 1
ID           Name           Type           Distribution    Slug           Public    Min Disk
```
Yes the help output says we include other details like available regions.
=> image: update help output to be accurate.

args.go, commands/databases.go, commands/databases_test.go
This PR aims at adding `kafka ACL option` to `user create` command under `databases` in doctl.
i.e.
Creates a new user for a database. New users are given a role of `normal` and are given an automatically-generated password.
Flag:
` --acl topic:permission`                    A comma-separated list of kafka ACL rules, in topic:permission format.
Usage:
` doctl databases user create <database-cluster-id> <user-name> --acl <topic>:<permission>,<topic>:<permission>`
Examples:
The following example creates a new user with the username `example-user` for a database cluster with the ID `ca9f591d-f38h-5555-a0ef-1c02d1d1e35`: 
`doctl databases user create ca9f591d-f38h-5555-a0ef-1c02d1d1e35 example-user --acl new_topic:consume,test:admin`
=> Add kafka acl option to user create

commands/certificates.go, commands/certificates_test.go, do/certificates.go, do/mocks/CDNsService.go, do/mocks/CertificatesService.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/certificates.go, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
[NETPROD-3585](https://do-internal.atlassian.net/browse/NETPROD-3585)
[NETPROD-3585]: https://do-internal.atlassian.net/browse/NETPROD-3585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NETPROD-3585] Added name filter in doctl for certificates

commands/kubernetes.go
Ensure that the first backquoted string in kubernetes create flags is a string that should be used as the type in the usage message, because those backquotes cause pflag's usage parser to extract them and treat them as a flag name to try to determine the data type of the flag. The practical effect of this was that the help was borderline unreadable because the description was forced so far right and narrow.
Here's a screenshot of the effect of these changes:
=> kubernetes: improve usage message

commands/cdns.go
Updates the `doctl compute cdn list` command with a correctly formatted example and description.
=> Updates list CDNs example

commands/apps_dev.go
https://do-internal.atlassian.net/browse/APPS-8465
The run-image being used in `doctl apps dev build` is outdated.
Local builds are failing with: `failed to export: get run image top layer SHA: image <image-1> has no layers`
This PR updates the tag to fix the issue.
=> Update cnb run-image tag

commands/apps.go
Resolves PDOCS-2445. Documents the `run_restarted` value for `doctl apps logs $app_id --type`.
=> Document App Platform crash log value

pkg/extract/extract.go
This PR fixes impossible condition `nil != nil`.
Consider the following code:
```go
f, err := os.Create(path)
if err != nil {
return err
}
f.Chmod(info.Mode())
if err != nil {
return err
}
```
The second `if err != nil` effectively becomes `if nil != nil` due to the preceding `if err != nil` check.
There are two ways to fix this: the first is to simply delete the second `if err != nil`, and the second is to handle an error from `f.Chmod`, which is the option I have chosen.
=> Fix useless error check in extractTarGz

commands/registry.go
Resolves PDOCS-2515. This PR corrects an example where the registry name was incorrectly prepended to the repository name. The example should be correct now.
=> Corrects DOCR list manifests example

args.go, commands/displayers/vpc_peering.go, commands/doit.go, commands/vpc_peerings.go, commands/vpc_peerings_test.go, commands/vpcs.go, commands/vpcs_test.go, do/mocks/VPCsService.go, do/vpcs.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/vpc_peerings.go, vendor/github.com/digitalocean/godo/vpcs.go, vendor/modules.txt
VPC Peering is a closed beta feature and not available for public use.
[Testing doc ](https://docs.google.com/document/d/1kE451w61E_zhOZ04bTTkvEBJiLSQZWlHVtupRs8oalg/edit)
[VPC-3359]: https://do-internal.atlassian.net/browse/VPC-3359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [VPC-3359] Implemented vpc peering methods

commands/auth.go, commands/auth_test.go
addresses https://github.com/digitalocean/doctl/issues/1543
Updates the `doctl auth list` command to respect the -o json flag.
Example output:
```
$ go run cmd/doctl/main.go auth list -o json
[
{
"name": "default",
"current": true
},
{
"name": "personal",
"current": false
},
{
"name": "work",
"current": false
}
]
```
=> doctl auth list: respect json output flag

commands/kubernetes.go
👋 
Just a very small typo correction in the DOKS 1-click example text when running `doctl kubernetes 1-click install --help`
It removes the extra `>` which should not be there. Running the command with the extra `>` would result in `Notice: No addons specified for cluster:`
=> Fix typo in DOKS 1-click example text

commands/firewalls.go
Also tweaks one description to be more similar to existing text.
=> Fix spelling in firewall documentation

CONTRIBUTING.md, _typos.toml, args.go, commands/command_config.go, commands/databases.go, commands/functions.go, commands/serverless_test.go, do/serverless.go, integration/droplet_neighbors_test.go, scripts/version.sh
Can setup a github action too
https://github.com/crate-ci/typos/blob/master/docs/github-action.md
=> ci: Configure crate-ci/typos and auto fix what I can

commands/functions.go, commands/volume_actions.go
This one is a bit pedantic:
error: `parm` should be `param`, `pram`, `parma`
But there is a real one in the help output for for `volume-actions ls`.
=> misc: clean up additional typos found in CI.

.github/workflows/ci.yml, go.mod
Upgrades the GitHub CI workflows and `go.mod` entry for Go 1.22. Just in time for Go 1.23 to be released 😅
=> go: upgrade to 1.22

commands/volume_actions.go
Updates volume attachment docs for the new limit.
CC: @hazel-nut
=> volumes: fifteen volumes may be attached to a Droplet

.github/workflows/snapcraft-candidate.yml, snap/snapcraft.yaml
This switches the snap candidate builds to use the official `snapcore/action-build` GitHub Action rather than our bespoke Docker build.Additionally it updates the snap base to `core22`, 
This built successfully in my fork (note it is red as the upload failed due to the missing credentials, but the build itself succeeded):
https://github.com/andrewsomething/doctl/actions/runs/10359056705/job/28674610325#step:3:98
Once we've successfully built, uploaded, and validated a new candidate snap, I'll follow on with a new PR for the release workflow. Then finally, after successfully cutting a new release, we can rip out the Docker build scripts.
=> snap: use snapcore/action-build for candidate builds

.github/workflows/release.yml
Follow up on https://github.com/digitalocean/doctl/pull/1566 Candidate build was successful: 
https://github.com/digitalocean/doctl/actions/runs/10359332118/job/28675519869
```
$ snap info doctl | grep candidate
latest/candidate: v1.110.0+git50ad7727 2024-08-12 (1718) 45MB -
```
I've installed the candidate build and validated it is working as expected, including the Docker and K8s integrations as well as the serverless plugin.
=> snap: use snapcore/action-build for release build

.github/workflows/release.yml
This updates the goreleaser config to match the version of Go from `go.mod`
=> Use Go 1.22.x in release builds

commands/apps_dev.go, internal/apps/builder/cnb.go
This PR updates CNBBuilderImage tag to `v0.73.1` (current stable version) and `apps-run` to `c047ec7`
Fix: #1518 
This fixes the following error:
```
ERROR: failed to export: get run image top layer SHA: image "<image-0>" has no layers
```
=> Update cnb builder tags

args.go, commands/databases.go, commands/databases_test.go, go.mod, go.sum, integration/database_user_create_test.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/golang.org/x/oauth2/token.go, vendor/modules.txt
**This PR aims at adding support for OpenSearch acl option to database user** 
```
Creates a new user for a database. New users are given a role of `normal` and are given an automatically-generated password.
To retrieve a list of your databases and their IDs, call `doctl databases list`.
Usage:
doctl databases user create <database-cluster-id> <user-name> [flags]
Aliases:
create, c
Examples:
The following example creates a new user with the username `example-user` for a database cluster with the ID `ca9f591d-f38h-5555-a0ef-1c02d1d1e35`: doctl databases user create ca9f591d-f38h-5555-a0ef-1c02d1d1e35 example-user
Flags:
--acl topic:permission                      A comma-separated list of kafka ACL rules, in topic:permission format.
-h, --help                                      help for …
```
=> Update DOCTL to include new OpenSearch acl changes

Makefile
Fix for:
```
$ make _install_github_release_notes
go: modules disabled by GO111MODULE=off; see 'go help modules'
make: *** [Makefile:163: _install_github_release_notes] Error 1
```
=> misc: use 'go install' in _install_github_release_notes make target

commands/databases.go, commands/databases_test.go, commands/displayers/database.go, do/databases.go, do/mocks/DatabasesService.go
This PR allows users to obtain a certificate for connecting to the database.
Related to https://do-internal.atlassian.net/browse/APICLI-2506, https://github.com/digitalocean/doctl/issues/1512
=> databases: add get-ca to retrieve db certificate

commands/databases.go, commands/databases_test.go, do/databases.go, do/mocks/DatabasesService.go, go.mod, go.sum, integration/database_create_restore_from_cluster.go, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
Add 'doctl databases install_update <database_uuid>' command and unit tests.
=> [DBAAS] | Add API endpoint for applying cluster patches

commands/databases.go
Reviewing https://github.com/digitalocean/doctl/pull/1582, I noticed a type outside of the scope of that PR. While fixing that, I've also added some additional detail to the help output.
=> dbaas: Fix typo and add additional detail in config update help.

args.go, commands/kubernetes.go, commands/kubernetes_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/modules.txt
This allows setting custom subnets on DOKS clusters and create vpc-native clusters.
=> doks: add custom subnets flags

commands/databases.go, commands/databases_test.go, commands/displayers/database.go, do/databases.go, do/mocks/DatabasesService.go, go.sum, integration/database_config_get_test.go, integration/database_config_update_test.go
This PR is adding a support for Kafka advanced configuration: Get, Update.
```
doctl databases configuration get <db-cluster-id> -e kafka
```
```
doctl databases configuration update <db-cluster-id> -e kafka --config-json '{"group_initial_rebalance_delay_ms":2000}'
```
=> [databases]: add support for Kafka advanced configuration

commands/databases.go, commands/databases_test.go, commands/displayers/database.go, do/databases.go, do/mocks/DatabasesService.go, go.mod, go.sum, integration/database_config_get_test.go, integration/database_config_update_test.go, vendor/github.com/digitalocean/godo/databases.go, vendor/modules.txt
This PR is adding a support for Opensearch advanced configuration: Get, Update.
```
doctl databases configuration get <db-cluster-id> -e opensearch
```
```
doctl databases configuration update <db-cluster-id> -e opensearch --config-json '{"ism_history_max_age_hours":10}'
```
=> [databases]: add support for Opensearch advanced configuration

commands/databases.go, commands/databases_test.go
ISSUE #1585 
* added bool flag into resize command
* added wait functionality into resize
* adjusted test
=> ISSUE: 1585 | Add --wait flag to databases resize command

commands/databases.go, commands/databases_test.go
This PR enhances the `doctl databases migrate` command by adding a `--wait` flag. The flag allows users to wait for the migration process to complete, simplifying script automation and removing the need for users to implement their own polling mechanisms.
1. **Feature Implementation:**
- Updated the `RunDatabaseMigrate` function to support the `--wait` flag.
- Added logic to poll the `/v2/databases/$DATABASE_ID` endpoint until the status attribute moves from `"migrating"` to `"online"`.
- Display messages (`notice`) to inform users when the migration is in progress and when it completes.
2. **Unit Tests:**
- Enhanced the `TestDatabaseMigrate` function to include a test case for the `--wait` flag.
- Mocked the `Get` method to simulate database status polling.
- Ensured the function …
=> [feat:] Add `--wait` Flag to doctl databases migrate Command

commands/kubernetes.go
If a user creates a DOKS cluster through doctl and deletes it through some other means while doctl is waiting for the creation the command panics. This fixes the panic and returns an appropriate error.
=> doks: fix panic during create

commands/droplet_actions.go, commands/droplets.go, commands/images.go, commands/registry.go
This fixes improperly displayed options as described here:
https://github.com/digitalocean/doctl/issues/1594
=> Fixing not properly displayed options

args.go, commands/apps.go, integration/apps_test.go
This PR introduces a new --output-json flag for the RunAppsGetLogs function in the DigitalOcean CLI (doctl). When this flag is used, the logs are outputted in JSON format without the service name and timestamp prefix.
- Added --output-json flag to the RunAppsGetLogs function.
- Modified the log processing logic to remove the service name and timestamp prefix when the --output-json flag is used.
Closes #1536
=> fix(app): #1536 fix logging format to work with pino-pretty

integration/database_replica_create_test.go, integration/database_replica_delete_test.go, integration/database_replica_get_and_list_test.go
This patch adds the remaining database replica integration tests. It also corrects some of the parameters for the replica promote test.
Tested with `make test_integration`.
Closes #1359
=> Add Database Replica Integration Tests

commands/droplet_actions.go, commands/droplets.go
Updates the help text to reflect the current default for Droplet backup plans.
=> droplets: update help text to accurately describe default backup plan.

go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/droplet_autoscale.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/monitoring.go, vendor/modules.txt
Bumps godo to v1.128.0 in order to pull in various App Spec changes allowing doctl to unmarshal files with the new fields.
=> Bump godo to v1.128.0.

commands/firewalls.go, commands/load_balancers.go, commands/projects.go, commands/vpc_peerings.go, commands/vpcs.go
I have fixed some other places and replaced **<id>** with **<resource-id>** in command descriptions as it's more common and descriptive pattern.
=> Fixing positional resource id descriptions

args.go, commands/droplets.go, commands/droplets_test.go, do/droplets.go, do/mocks/DropletsService.go, go.mod, go.sum, integration/droplet_list_test.go, vendor/github.com/digitalocean/godo/droplets.go, vendor/github.com/digitalocean/godo/sizes.go, vendor/modules.txt
Adds a `--gpus` flag to the `doctl compute droplets list` command.
=> droplets: support listing GPU Droplets.

commands/load_balancers.go
Now that global load balancer is in GA and internal load balancer is in EA, remove the beta notes on these associated load balancer fields
=> LBAAS: remove beta notes on LBaaS fields

commands/apps_dev.go, internal/apps/builder/cnb.go
This PR updates CNBBuilderImage tag to v0.75.2 (current stable version) and apps-run to `f7a0bf0`
=> Use cnb builder v0.75.2

args.go, commands/apps.go, commands/apps_test.go, do/apps.go, do/mocks/AppsService.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/modules.txt
This PR adds a command to restart apps, with an option to restart specific components only.
~TODO: update godo version in go.mod once godo is released with Restart method.~ (this is done)
=> APPS-9765 Add command to restart apps

commands/apps.go
This PR changes the alias for:
- `console` command to `cs` (`l` is already used for `logs` command)
- `propose` command to `p` (`c` is already used for `create` command)
=> Fix conflicting aliases in apps commands

commands/databases.go
Adds example for database configuration and links to API docs for fields.
=> Adds example for database configuration

args.go, commands/apps.go
This adds a parameter named `--update-sources` to the `apps create` and `apps update` commands. If set, the respective update of the app spec also causes the underlying sources to be reevaluated and their respective latest state to be reflected in the created deployment.
On the `apps create` flow, this only applies to `--upsert` cases.
=> APPS: Add an --update-sources parameter to create and update app

commands/apps.go, commands/apps_test.go, do/apps.go, do/mocks/AppsService.go
I host [a bunch of apps](https://www.vestris.com/) on DO which is working really great. 
Trying to use the UX less. This change lists apps if you specify anything other than a UUID, I use this as `doctl apps logs slack-strava` vs. `doctl apps logs 4bf2666d-8fa9-4edd-8013-298ce3a8d52a` that I always have to get from the command line or UI.
Closes https://github.com/digitalocean/doctl/issues/1615.
=> Added support getting logs for an app by name.

CONTRIBUTING.md, Makefile, scripts/bumpversion.sh
PR:
- replace sembump
- update the release notes in the contributing guide
=> remove sembump tool as no longer installable with go tools

commands/droplet_autoscale.go
Remove option to hide the autoscaler commands now that it is publicly GA'd.
=> Enable droplet-autoscaler commands

commands/displayers/database.go, integration/database_list_test.go
In order to make the default display of  `doctl databases list` legible in a terminal, it does not display all attributes. To achieve this, the `Databases.Cols()` displays different columns if `Databases.Short = true`. It is `false` when generating help output. So columns not shown are indicated as available as `format` options. Exposing those to `Databases.ColMap()` regardless of whether the sort version is used allows them to be used with the `format` flag while still retaining the default behavior for the list view. 
Before this change, running the following command would error:
```
$ doctl databases list --format ID,Name,Engine,Version,URI,Created
Error: unknown column "URI"
```
Now it should successfully display the given fields.
=> databases: support displaying URI and Created in list with format flag

commands/kubernetes.go
Go 1.24 introduces stricter checks for format string validation. This commit fixes instances where non-constant format strings were used in calls to functions like `fmt.Errorf`, `fmt.Printf`, and similar.
=> Fix: Ensure constant format strings in fmt and printf calls

commands/apps.go
Resolves [PDOCS-2922](https://do-internal.atlassian.net/browse/PDOCS-2922). Clarifies App Platform create and update commands to explicitly state when the create and update workflows pull from source.
[PDOCS-2922]: https://do-internal.atlassian.net/browse/PDOCS-2922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Clarifies create and update commands for App Platform

args.go, commands/load_balancers.go, commands/load_balancers_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/kubernetes.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
support load balancers network_stack
=> LBAAS-3620: support load balancers network_stack

args.go
Happened to notice this and wanted to get it in before a release. Changes `network_stack` to `network-stack` to be consistent with other flags.
=> load-balancers: make network-stack flag consistent

args.go, commands/displayers/kubernetes.go, commands/kubernetes.go, commands/kubernetes_test.go
This PR adds the `scale-down-utilization-threshold` and the `scale-down-unneeded-time` flags for users to configure their cluster autoscaler configuration.
=> add cluster autoscaler configuration for cluster create and update

commands/displayers/kubernetes.go, integration/kubernetes_clusters_get_test.go, integration/projects_resources_get_test.go
Fixes the broken projects list test for the K8s resource, and adds a new k8s cluster get test to check for the newly added autoscaler fields.
This should fix the test failures introduced in #1649
=> k8s: fix autoscaler integration test cases

args.go, commands/displayers/image.go, commands/images.go, integration/droplet_backups_test.go, integration/droplet_snapshots_test.go, integration/image_create_test.go, integration/image_get_test.go, integration/image_list_application_test.go, integration/image_list_test.go
In this PR we are adding the field `Created` to doctl images command. This is useful for us to manage our images/snapshots available for the autoscale group. Once this field is available in godo and DO API.
=> add Created field to images command

commands/kubernetes.go
👋 Just a minor correction to the description of how to rerieve the list of available versions.
`doctl k8s get-upgrades k8s-lon1` should be `doctl k8s cluster get-upgrades k8s-lon1`
=> k8s: update upgrade command documentation

commands/displayers/partner_interconnect_attachment.go, commands/partner_interconnect_attachment.go, commands/partner_interconnect_attachment_test.go, do/mocks/PartnerInterconnectAttachmentsService.go, do/partner_interconnect_attachments.go, integration/partner_interconnect_attachment_test.go
Testing:
```
/doctl --context s2 network --type "partner" interconnect-attachment list-routes bb6da12f-eddc-4250-b40b-f9bef1cebcd1
```
=> [VPC-3918] List PIA remote routes

args.go, commands/partner_interconnect_attachment.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/partner_interconnect_attachments.go, vendor/modules.txt
On create the `bgp-auth-key` was missing, without this field it is not possible to create a partner interconnect attachment with bgp config. (related PR https://github.com/digitalocean/godo/pull/793)
=> add bgp auth key field

args.go, commands/displayers/kubernetes.go, commands/kubernetes.go, commands/kubernetes_test.go, integration/kubernetes_clusters_get_test.go, integration/projects_resources_get_test.go
Includes an up of godo version to `v1.138.0` to use newly introduced `RoutingAgent` flags.
Can be merged now.
=> add option to enable/disable routing-agent plugin

commands/droplets.go, commands/droplets_test.go, integration/droplet_create_test.go
Earlier on giving a random name or UUID for --project-id `Error: 404 Not Found` is thrown but still a droplet gets created in default project. 
```
`
doctl % doctl compute droplet create demo --image ubuntu-20-04-x64 --size s-1vcpu-1gb --region nyc1 --project-id first-project
Error: POST https://api.digitalocean.com/v2/projects/first-project/resources: 404 (request "9f376d2ade") not found
doctl % doctl compute droplet create demo --image ubuntu-20-04-x64 --size s-1vcpu-1gb --region nyc1 --project-id 8d22f3 
Error: POST https://api.digitalocean.com/v2/projects/8d2710122f3/resources: 404 (request "07b307e2a") not found`
```
Added a check to validate if project-id exist or not.
Following execution shows examples with correct, incorrect and no --project-id.
```
doctl % docker run --rm -it …
```
=> Check for --project-id before droplet creation

commands/apps_dev.go, commands/apps_dev_test.go, internal/apps/builder/cnb.go
For every new builder image release, we have to manually update the `CNBBuilderImage_Heroku22` and `apps-run` images.
If this combination is not correct, user will encounter error similar to  https://github.com/digitalocean/doctl/pull/1573
This PR tries to fix this by getting `apps-run` image from `CNBBuilderImage`'s metadata.
=> APPS-10741: Get stack run image from CNB Builder Image

args.go, commands/load_balancers.go, commands/load_balancers_test.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/databases.go, vendor/github.com/digitalocean/godo/godo.go, vendor/github.com/digitalocean/godo/load_balancers.go, vendor/modules.txt
add ability to set load balancer tls cipher policy via doctl
=> LBAAS: add tls cipher policy as load balanacer arg

go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
Updates `godo` to `v1.145.0` to bring over the changes in [this release](https://github.com/digitalocean/godo/releases/tag/v1.145.0).
=> Update godo dependency to v1.145.0

commands/apps_dev.go, internal/apps/builder/cnb.go
For the command: `doctl apps dev build`, all builder images are pulled before the app is built.
This results in unnecessary bandwidth and storage usage, as it pulls builders for both `ubuntu-22` and `ubuntu-18` stacks, even though only one is actually used during the build.
With this change, doctl will pull the `ubuntu-18` builder image only if the AppSpec explicitly specifies this stack.
=> Enhancement: Pull ubuntu-18 builder image only when the app requires ubuntu-18

args.go, commands/apps.go, commands/apps_test.go, commands/displayers/apps.go, do/apps.go, do/mocks/AppsService.go, go.mod, go.sum, vendor/github.com/digitalocean/godo/CHANGELOG.md, vendor/github.com/digitalocean/godo/apps.gen.go, vendor/github.com/digitalocean/godo/apps.go, vendor/github.com/digitalocean/godo/apps_accessors.go, vendor/github.com/digitalocean/godo/egress_gateways.go, vendor/github.com/digitalocean/godo/godo.go, vendor/modules.txt
This PR adds a new command to list an app's currently running instances. Using godo's `GetAppInstances()`. Doctl's implementation also follows godo's `GetAppInstancesOpts` to keep it future proof and aligned.  
This PR depends on https://github.com/digitalocean/godo/pull/831 to be merged and released. 
Usage will be
- ~`doctl apps instances $app_id`~
- `doctl apps list-instances $app_id`
Expected result
=> Feat: Add command to get current running instance of an app

commands/databases.go, commands/displayers/database.go
Updates the `doctl databases options` commands to include Valkey results.
=> dbaas: support displaying Valkey options

commands/apps_dev.go, commands/apps_dev_test.go, integration/kubernetes_clusters_create_test.go
The images `CNBBuilderImage_Heroku22` and `RunImage` are required only for buildpack-based builds.
For Dockerfile-based builds, we don't need these, as the local Dockerfile is used to build the image.
This PR adds a check to pull `RunImage` only if the `BuilderImage` exists i.e. its a buildpack-based build.
This PR also fixes k8s integration tests by updating the NodePool slug as per the PR #1694
=> fix: Pull RunImage only if cnb-builder image exists

do/serverless.go
Updating the min `functions-deployer` version to `5.0.21`
=> SERVERLESS-3399: update minimum serverless version to 5.0.21

.github/workflows/release.yml
The current `on.push.tags` pattern in the `tagged-release` workflow incorrectly matches some invalid tags and misses valid SemVer tags. Specifically:
- ✅ It **matches invalid tags** like:
- `v2x3.4` (because `.` matches any character)
- `v1-2-3` or `v1.2x3`
- `v10.0.0` is ignored due to `[1-9]` limitation
- ❌ It **misses valid tags** like:
- `v0.1.0`
- `v1.24`
- `v1.2`
This PR replaces the regex:
```
from: 'v[1-9].[0-9]+.[0-9]+'
to:   '^v[0-9]+\.[0-9]+(\.[0-9]+)+$' 
```
=> fix(realease): correct tag regex to strictly match SemVer vX.Y.Z format.

Dockerfile
Add `/app` to `$PATH` in the Dockerfile to ensure that the `/app` directory is included in the container's executable search path.
For example, when you define `cmd` in a Kubernetes manifest, you need to specify the full path to the binary.
```bash
command = [
"/app/doctl", # <- THIS
"registry",
"garbage-collection",
"start",
"-f",
"--include-untagged-manifests",
"registry-name",
]
```
=> Add /app to $PATH in Dockerfile

commands/auth.go, commands/auth_test.go
For feature parity with other CLIs such as `gh auth token` when user needs to grab API token for usage outside of `doctl` commands. For instance, to pass to scripts which talk to DO's API.
=> Enable output of current context token

.github/workflows/release.yml
This PR reverts changes made in https://github.com/digitalocean/doctl/pull/1715 which were causing the release pipeline to not getting triggered
=> Reverting tag regex changes

commands/registry.go, integration/registry_garbagecollection_test.go
This is a fix for https://github.com/digitalocean/doctl/issues/1750 and https://github.com/digitalocean/doctl/issues/1749
As I commented in the issue the new `registries` command is what caused this bug.
When `Registries()` built the command, the flags of it's sub-commands mapped to the exact same names as those in the sub-commands created by `Registry()` for the `registry` command.
These flags are all written to a global table in the `viper` library (the `pflags` member of `var v *Viper` in `viper.go`).
So the flags created by `Registry()` were being overwritten by the `Registries()` flags.
My solution was to distinguish the flag names using `overrideNS`.
I think in future it would be worth it to refactor how the flag names and name spaces are constructed to avoid this completely, but at …
=> distinguish subcommands with overrideNS

.github/workflows/release.yml
This change runs integration tests before we mark a release as latest.
=> Adding integration tests as a pre requirement for releases

.github/workflows/beta-release.yml, .github/workflows/release.yml, scripts/bumpversion.sh
Adding a beta tag where all release activities will be tested and only post completion will the release be marked as latest
End-to-End Flow:
Developer: make tag BUMP=minor
Creates: v1.23.0-beta tag
Beta workflow triggers:
✅ Runs integration tests (Ubuntu + macOS)
✅ Creates beta release (marked as pre-release)
✅ Auto-creates stable tag v1.23.0
Stable workflow triggers:
✅ Verifies beta tag exists
✅ Creates stable release (marked as latest)
✅ Publishes to Snapcraft
=> Adding support for beta tag automation
